Repository betagouv/service-national-universel, pull requests merged in 2023-11, with the labels that each got.

#3158 feat(app/api): 828 - Préinscription et Réinscription : évolution de l'écran "Non éligible"
  api/src/controllers/cohort-session.js
  api/src/controllers/young/reinscription.js
  app/src/scenes/noneligible/DesktopNonEligible.jsx
  app/src/scenes/noneligible/MobileNonEligible.jsx
  app/src/scenes/noneligible/index.jsx
  app/src/scenes/preinscription/components/EngagementCard.jsx
  app/src/scenes/preinscription/components/EngagementPrograms.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepNonEligible.jsx
  app/src/scenes/reinscription/index.jsx
  app/src/scenes/reinscription/steps/stepEligibilite.jsx
  app/src/scenes/reinscription/steps/stepNonEligible.jsx
  app/src/utils/navigation.js
Labels: UI/UX

#3237 feat(api/admin/app): pass user timezone in req header
  admin/src/scenes/phase0/components/ChangeCohortPen.jsx
  admin/src/scenes/volontaires/create.jsx
  admin/src/services/api.js
  api/src/__tests__/young-auth.test.js
  api/src/__tests__/young-inscription.test.js
  api/src/auth.js
  api/src/controllers/cohort-session.js
  api/src/controllers/referent.js
  api/src/controllers/young/account.js
  api/src/controllers/young/index.js
  api/src/controllers/young/inscription2023.js
  api/src/controllers/young/reinscription.js
  api/src/index.js
  api/src/middlewares/validateCustomHeader.js
  app/src/scenes/auth/desktop/signin.jsx
  app/src/scenes/auth/mobile/signin.jsx
  app/src/scenes/home/index.jsx
  app/src/scenes/inscription2023/components/ModalSejour.jsx
  app/src/scenes/inscription2023/steps/correction/stepEligibilite.jsx
  app/src/scenes/phase1/changeSejour.jsx
  app/src/scenes/preinscription/index.jsx
  app/src/scenes/preinscription/steps/stepConfirm.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/reinscription/index.jsx
  app/src/services/api.js
  app/src/services/cohort.service.js
  app/src/services/young.service.js
Labels: WIP

#3251 feat(api,app): 1382 - Preinscription : amélioration de la recherche d'établissement
  api/src/controllers/elasticsearch/schoolramses.js
  app/src/components/CreatableSelect.jsx
  app/src/components/dsfr/forms/AsyncCombobox.jsx
  app/src/scenes/inscription2023/components/ShoolInFrance.jsx
Labels: enhancement, UI/UX

#3265 feat(api,app): 1392 - CLE : étapes Profil et Validation de l'email
  api/src/auth.js
  api/src/models/young.js
  app/src/scenes/preinscription/index.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
  packages/lib/sessions.js
Labels: inscription

#3277 fix(app): 1382 - Amélio saisie établissement (retours PO)
  app/src/components/CreatableSelect.jsx
  app/src/components/dsfr/forms/AsyncCombobox.jsx
  app/src/scenes/inscription2023/components/ShoolInFrance.jsx
Labels: UI/UX, quick win

#3279 feat(api, app): 1396 - Inscription CLE : Etape coordonnées
  api/src/controllers/young/inscription2023.js
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
  app/src/services/useParcours.jsx
  app/src/utils/parcoursConfig.js
Labels: CLE

#3263 feat(app): 1394 - CLE onboarding page
  admin/.gitignore
  api/src/controllers/cle/classe.js
  app/.gitignore
  app/src/app.jsx
  app/src/assets/icons/QuestionMarkBlueCircle.jsx
  app/src/assets/onboarding-cle.png
  app/src/components/dsfr/layout/DSFRContainer.jsx
  app/src/components/dsfr/layout/DSFRLayout.jsx
  app/src/components/dsfr/layout/Header.jsx
  app/src/components/dsfr/nav/Menu.jsx
  app/src/scenes/cle/OnBoarding.jsx
  app/src/scenes/inscription2023/components/DesktopPageContainer.jsx
  app/src/services/useAuth.js
  app/src/services/young.service.js
  packages/ds/src/dsfr/Field.tsx
  packages/ds/src/dsfr/List.tsx
  packages/ds/src/dsfr/index.ts
  packages/ds/src/dsfr/layout/PaddedContainer.tsx
  packages/ds/src/dsfr/types.d.ts
Labels: WIP

#3280 feat(app): 1422 - Change Wording to RL1 relance for CLE
  app/src/scenes/cle/OnBoarding.jsx
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
  app/src/scenes/inscription2023/steps/stepDone.jsx
  app/src/scenes/preinscription/Done.jsx
  app/src/services/useParcours.jsx
  app/src/utils/parcoursConfig.js
Labels: CLE

#3282 feat(api, app): 1396 - Inscription CLE : étape Représentants légaux
  api/src/controllers/young/inscription2023.js
  app/src/scenes/inscription2023/steps/stepRepresentants.jsx
Labels: CLE

#3288 feat(app): 1423 - change waitingValidation Page and changeSejour for CLE
  app/src/scenes/account/scenes/general/index.jsx
  app/src/scenes/home/waitingValidation.jsx
Labels: CLE

#3293 feat(app): 1396 - Inscription CLE : étape récapitulatif
  admin/.gitignore
  app/src/scenes/inscription2023/components/ModalSejour.jsx
  app/src/scenes/inscription2023/steps/stepConfirm.jsx
  app/src/scenes/preinscription/Done.jsx
  app/src/scenes/preinscription/steps/stepSejour.jsx
  packages/ds/src/dsfr/layout/PaddedContainer.tsx
Labels: CLE

#3296 feat(app): 1428 - Isncription CLE : adapt header
  app/src/components/dsfr/layout/Header.jsx
  app/src/components/dsfr/nav/Menu.jsx
  app/src/scenes/inscription2023/index.jsx
  app/src/scenes/preinscription/index.jsx
  app/src/services/useAuth.js
Labels: CLE

#3302 feat(app): 1434 - Formulaire de contact : adapter le formulaire au parcours CLE
  app/src/assets/pictograms/Avatar.jsx
  app/src/assets/pictograms/School.jsx
  app/src/components/dsfr/forms/EnhancedRadioButton.jsx
  app/src/components/dsfr/ui/Alert.jsx
  app/src/components/dsfr/ui/CardLink.jsx
  app/src/scenes/contact/components/ContactForm.jsx
  app/src/scenes/contact/components/PublicContactForm.jsx
  app/src/scenes/contact/contact.service.js
  app/src/scenes/contact/index.jsx
Labels: UI/UX, CLE

#3278 fix(api): Add 11 hours to bornBefore date for eligibility check
  api/src/utils/cohort.js
Labels: bug
