Repository betagouv/service-national-universel, pull requests merged in 2023-10, with the labels that each got.

#3081 feat(app): Add link to sejour choice step to step confirm of preinscription
  app/src/scenes/preinscription/steps/stepConfirm.jsx
Labels: UI/UX

#3121 feat(app, api): address autocomplete
  api/src/__tests__/young-inscription.test.js
  api/src/controllers/young/inscription2023.js
  api/src/models/young.js
  app/src/components/dsfr/forms/AddressForm/AddressDisplay.jsx
  app/src/components/dsfr/forms/AddressForm/AddressDropdown.jsx
  app/src/components/dsfr/forms/AddressForm/AddressSearch.jsx
  app/src/components/dsfr/forms/AddressForm/index.jsx
  app/src/scenes/inscription2023/components/AdressSelect.jsx
  app/src/scenes/inscription2023/index.jsx
  app/src/scenes/inscription2023/steps/correction/stepEligibilite.jsx
  app/src/scenes/inscription2023/steps/correction/stepProfil.jsx
  app/src/scenes/inscription2023/steps/stepConfirm.jsx
  app/src/scenes/inscription2023/steps/stepConsentements.jsx
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
  app/src/scenes/inscription2023/steps/stepDocuments.jsx
  app/src/scenes/inscription2023/steps/stepDone.jsx
  app/src/scenes/inscription2023/steps/stepRepresentants.jsx
  app/src/scenes/inscription2023/steps/stepUpload.jsx
  app/src/scenes/representants-legaux/mobile/consentement.jsx
  app/src/scenes/representants-legaux/mobile/image-rights.jsx
  app/src/scenes/representants-legaux/utils.js
  app/src/services/api-adresse.js
Labels: UI/UX, inscription

#3105 feat(admin): dynamic settings phase0
  admin/src/components/ui/forms/dateForm/DatePickerInput.jsx
  admin/src/scenes/settings/index.jsx
  api/src/controllers/cohort.js
  api/src/models/cohort.js
Labels: WIP

#3141 feat(ds/admin): template & tailwind reload fix
  admin/src/scenes/develop/DesignSystemPage.jsx
  packages/ds/src/admin/layout/Container.tsx
  packages/ds/src/admin/layout/Header.tsx
  packages/ds/src/admin/layout/Page.tsx
  packages/ds/src/admin/layout/Subheader.tsx
  packages/ds/src/tailwind.config.ts
Labels: WIP

#3134 feat(app): Inscription/téléversement : ajouter une étape de prévisualisation des documents
  app/src/scenes/inscription2023/components/StepUploadDesktop.jsx
  app/src/scenes/inscription2023/components/StepUploadMobile.jsx
  app/src/scenes/inscription2023/components/VerifyDocument.jsx
  app/src/scenes/inscription2023/steps/stepUpload.jsx
Labels: UI/UX, inscription

#3149 fix(admin): [Safari] Permettre au bouton "Prendre la place" d'ouvrir un nouvel onglet
  admin/src/scenes/inbox/components/ticketInfos.jsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/inscription/panel.jsx
  admin/src/scenes/phase0/components/YoungHeader.jsx
Labels: bug, quick win
