Repository betagouv/service-national-universel, pull requests merged in 2024-07, with the labels that each got.

#4043 feat(api): add migration repository tools
  api/migrate-mongo-config.js
  api/migrations/20240627123807-sync-appel-a-projet.js
  api/migrations/20240627134721-create-changelog-lock.js
  api/package.json
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/featureFlag/featureFlagService.ts
  api/src/main.js
  api/src/migration.js
  api/src/models/featureFlag.ts
  api/src/models/featureFlagType.ts
  api/src/mongo.js
  api/src/utils/index.js
  package-lock.json
Labels: bypass title, ADMIN

#4048 feat(api/antivirus): secret api key for antivirus
  .github/workflows/cc-deploy-production.yml
  .github/workflows/cc-sync-production.yml
  .github/workflows/deploy-production-hotfix.yml
  .github/workflows/deploy-production.yml
  antivirus/config.js
  antivirus/controllers/authController.js
  antivirus/index.js
  antivirus/middlewares/authMiddleware.js
  antivirus/package.json
  api/config/ci.js
  api/config/default.js
  api/config/production.js
  api/config/staging.js
  api/src/utils/virusScanner.js
  package-lock.json
  terraform/environments/production/production.tf
Labels: Pull request title validation

#4051 disable scaleway instances
  terraform/environments/production/production.tf
Labels: Pull request title validation

#4052 fix(antivirus): update scw environment
  antivirus/Dockerfile
  terraform/environments/production/production.tf
Labels: Pull request title validation

#4054 fix(api): migration - migration is run by runAPI()
  api/src/main.js
  api/src/migration.js
Labels: bypass title

#4057 fix(api): migration - remove console and use earlier return
  api/src/migration.js
Labels: bypass title

#4062 fix(api): Disable pm2 stderr
  api/docker_start.sh
Labels: bypass title

#4041 fix(admin): 2359 - cle design
  .github/workflows/run-tests-lib.yml
  admin/package.json
  admin/src/app.jsx
  admin/src/components/Breadcrumbs.jsx
  admin/src/components/PaginationServerDriven.tsx
  admin/src/components/drawer/components/Dot.tsx
  admin/src/components/drawer/components/MultiNavItem.tsx
  admin/src/components/drawer/components/SimpleNavItem.jsx
  admin/src/components/filters-system-v2/components/SortOption.jsx
  admin/src/components/filters-system-v2/components/SortOption.tsx
  admin/src/index.css
  admin/src/scenes/classe/create.jsx
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/classe/list/ClasseRow.tsx
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/contact/list.jsx
  admin/src/scenes/dashboardV2/components/General.tsx
  admin/src/scenes/dashboardV2/head-center/subscenes/sejour/index.jsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/engagement/index.jsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/inscription/index.jsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/index.jsx
  admin/src/scenes/dashboardV2/responsible/subscenes/engagement/index.jsx
  admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
  admin/src/scenes/develop/DesignSystemPage.jsx
  admin/src/scenes/dsnj-export/index.jsx
  admin/src/scenes/etablissement/List.jsx
  admin/src/scenes/etablissement/view.tsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/missions/list.jsx
  admin/src/scenes/plan-transport/ligne-bus/List.jsx
  admin/src/scenes/signup/code.jsx
  admin/src/scenes/signup/components/Stepper.tsx
  admin/src/scenes/signup/confirmation.jsx
  admin/src/scenes/signup/email.jsx
  admin/src/scenes/signup/index.jsx
  admin/src/scenes/signup/informations/index.jsx
  admin/src/scenes/signup/role.jsx
  admin/src/scenes/structure/view/missions.jsx
  admin/src/scenes/team/list.jsx
  admin/src/scenes/utilisateur/list.jsx
  admin/src/scenes/volontaire-cle/list.jsx
  admin/src/scenes/volontaires/list.jsx
  admin/src/utils/pagination.utils.js
  admin/tailwind.config.js
  packages/ds/.prettierrc
  packages/ds/src/admin/form/Select/Select.tsx
  packages/ds/src/admin/form/Select/theme.ts
  packages/ds/src/admin/index.ts
  packages/ds/src/admin/layout/Breadcrumbs.tsx
  packages/ds/src/admin/layout/Header.tsx
  packages/ds/src/admin/ui/Badge.tsx
  packages/lib/src/dto/classeDto.ts
Labels: ADMIN

#4053 feat(admin,api): 2601 - cle reinscription auth
  admin/src/scenes/auth/signin.jsx
  api/migrations/20240703093515-remove-old-invitationToken.js
  api/src/__tests__/fixtures/referent.js
  api/src/__tests__/referent-auth.test.js
  api/src/auth.js
  packages/lib/src/roles.ts
Labels: ADMIN

#4060 feat(api): 2599-2600 - prevent duplicate entry
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/cle/appelAProjetCle/appelAProjetClasseService.ts
  api/src/cle/appelAProjetCle/appelAProjetEtablissementService.ts
  api/src/cle/appelAProjetCle/appelAProjetReferentService.ts
Labels: ADMIN

#4070 fix(api,admin): 2926 - Open right table de repartition for ref reg
  admin/src/scenes/plan-transport/table-repartition/components/RegionRow.jsx
  packages/lib/src/roles.ts
Labels: Pull request title validation

#4072 fix(admin): wording
  admin/src/scenes/plan-transport/schema-repartition/components/BoxVolontaires.tsx
Labels: Pull request title validation, bypass title

#4068 fix(admin,api): [CLE] inscription form - chef etablissement
  admin/src/scenes/etablissement/components/modale/FirstLoginAdminChef.tsx
  admin/src/scenes/etablissement/components/modale/FirstLoginAdminCoordinator.tsx
  admin/src/scenes/etablissement/components/modale/FirstLoginRefClasse.tsx
  admin/src/scenes/signup/CodeForm.tsx
  admin/src/scenes/signup/ConfirmationForm.tsx
  admin/src/scenes/signup/EmailForm.tsx
  admin/src/scenes/signup/InformationsForm.tsx
  admin/src/scenes/signup/RoleForm.tsx
  admin/src/scenes/signup/index.tsx
  admin/src/types.ts
  api/src/controllers/cle/referent-signup.js
  packages/lib/src/cohort/cohortService.spec.ts
  packages/lib/src/cohort/cohortService.ts
  packages/lib/src/dto/classeDto.ts
  packages/lib/src/dto/etablissementDto.ts
  packages/lib/src/dto/referentDto.ts
Labels: bypass title, ADMIN

#4067 feat(admin,api): fix maultiple bug for the CLE
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/cle/classe.test.js
  api/src/__tests__/young.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/classe/stateManager.ts
  packages/lib/src/constants/constants.js
  packages/lib/src/roles.ts
  packages/lib/src/translation.js
Labels: bypass title, ADMIN

#4078 fix(github): add environment to subworkflow
  .github/workflows/cc-deploy-production.yml
Labels: bypass title

#4084 fix(api,admin): désactiver la vue des nouvelles classes crée avant le 15 juillet
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/etablissement/List.jsx
  api/migrations/20240710094700-delete_doublon_etab.js
  api/migrations/20240710122436-add_feature_flag_import.js
  api/src/controllers/elasticsearch/cle/classe.js
  api/src/controllers/elasticsearch/cle/etablissement.js
  api/src/models/featureFlagType.ts
Labels: bypass title

#4090 fix(api): CLE - Ajout filtre dossier - etablissement existant
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/appelAProjetCle/appelAProjetEtablissementService.ts
  api/src/cle/appelAProjetCle/appelAProjetService.test.ts
  api/src/cle/appelAProjetCle/appelAProjetService.ts
  api/src/cle/appelAProjetCle/appelAProjetType.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.test.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.ts
Labels: bypass title, ADMIN

#4091 feat(api): 2922 - mettre a jour les statusPhase1 des classes de 2023-2034
  api/migrations/20240711094931-2023-2024_classe_statusPhase1.js
Labels: ADMIN

#4082 feat(admin,api): 2947 - ajout fonctionnalité vérifier ma classe pour les admin CLE et ref
  admin/src/scenes/classe/components/VerifClassButton.tsx
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/cle/classe.test.js
  api/src/cle/classe/classeController.ts
  api/src/emails/cle/classe.js
  packages/lib/src/constants/email.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4089 feat(api): 2888 - vérifier le branchement des mails pour les CLE
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/classe/list/ClasseRow.tsx
  api/src/cle/classe/stateManager.ts
  api/src/controllers/cle/referent-signup.js
  api/src/emails/cle/classe.js
  api/src/emails/cle/referent.js
  packages/lib/src/constants/email.ts
Labels: ADMIN

#4093 feat(admin,api): 2955 - Ajouter un export des classes qui ne soit pas un SR
  admin/src/scenes/classe/list.jsx
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/export/classeExportService.ts
  api/src/controllers/elasticsearch/cle/classe.js
  packages/lib/src/constants/constants.ts
Labels: ADMIN

#4080 feat(admin,api): 2890 - ajout fonctionnalité relancé la verif des classes pour les refs
  admin/src/scenes/classe/components/ButtonRelanceVerif.tsx
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/cle/classe.test.js
  api/src/cle/classe/classeController.ts
  api/src/emails/cle/classe.js
  packages/lib/src/constants/email.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4099 fix(api) : fix les pages volontaires et inscriptions ne fonctionnaient plus
  api/src/__tests__/cle/classe.test.js
  api/src/__tests__/helpers/es.ts
  api/src/__tests__/ligne-de-bus.test.js
  api/src/__tests__/session-phase1.test.js
  api/src/controllers/elasticsearch/cle/classe.js
  api/src/utils/es-serializer.js
Labels: bug, bypass title

#4101 fix: [CLE] invite chefetablissement param emailEtablissement
  api/src/services/cle/referent.ts
Labels: bypass title, ADMIN

#4104 fix(admin): bouton edit classe
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/utils/index.ts
Labels: bug, bypass title

#4107 fix(api): cohort patches fromUser + dto email
  api/src/models/cohort.js
  packages/lib/src/dto/userDto.ts
Labels: bug, bypass title

#4111 feat(api, app, admin): no-ticket - add 2fa env var
  api/config/default.js
  api/src/auth.js
Labels: bypass title

#4001 refactor(app): no ticket - Code split app
  app/src/Espace.jsx
  app/src/app.jsx
  app/src/components/FallBackComponent.jsx
  app/vite.config.js
Labels: bypass title

#4100 feat(admin): 2741 - préfilter les etablissement et les classes sur l'année 2024-2025
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/etablissement/List.jsx
Labels: ADMIN

#4114 refacto(admin,api) : petite refacto de la view des etablissements qui faisait des call API inutile et longs
  admin/src/scenes/etablissement/view.tsx
  api/src/__tests__/cle/etablissement.test.js
  api/src/cle/etablissement/etablissementController.ts
  packages/lib/src/dto/index.ts
Labels: CLE, bypass title, ADMIN

#4115 feat(admin,api): 2973 - notifier les ref reg lorsque l'effectif d'une classe est revue a la hausse
  api/src/__tests__/cle/classe.test.js
  api/src/cle/classe/classeController.ts
  api/src/emails/cle/classe.js
  packages/lib/src/constants/email.ts
Labels: ADMIN

#4121 fix(admin,app): Mise à jour design toaster
  admin/package.json
  admin/src/index.css
  admin/src/types.ts
  app/package.json
  package-lock.json
Labels: bypass title

#4110 chore(api): cleanup cle models
  api/.eslintrc.js
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/__tests__/cle/etablissement.test.js
  api/src/__tests__/cle/referent-signup.test.ts
  api/src/__tests__/cle/referent.test.ts
  api/src/__tests__/helpers/etablissement.ts
  api/src/cle/appelAProjetCle/appelAProjetClasseService.ts
  api/src/cle/appelAProjetCle/appelAProjetEtablissementService.ts
  api/src/cle/appelAProjetCle/appelAProjetReferentService.ts
  api/src/cle/appelAProjetCle/appelAProjetType.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/etablissement/etablissementMapper.ts
  api/src/controllers/cle/referent-signup.js
  api/src/controllers/cle/referent.ts
  api/src/models/cle/classe.js
  api/src/models/index.ts
  api/src/models/referent.js
  api/src/models/referentType.ts
  api/src/pdt/import/pdtImportService.ts
  api/src/services/cle/referent.ts
  packages/lib/.eslintrc.js
  packages/lib/src/constants/referentConstants.ts
Labels: WIP, ADMIN

#4123 chore(api): [PDT] add simple test for import and execute
  api/src/__tests__/fixtures/PlanDeTransport/importPlanTransport.ts
  api/src/__tests__/fixtures/PlanDeTransport/pointDeRassemblement.js
  api/src/__tests__/fixtures/busTeam.ts
  api/src/__tests__/fixtures/cohesionCenter.js
  api/src/__tests__/helpers/PlanDeTransport/planDeTransport.ts
  api/src/__tests__/helpers/app.js
  api/src/__tests__/helpers/db.js
  api/src/__tests__/ligne-to-point.test.js
  api/src/__tests__/plan-de-transport.test.ts
  api/src/controllers/planDeTransport/import.js
  api/src/mongo.js
  api/src/pdt/import/pdtImportUtils.ts
Labels: ADMIN

#4092 feat(api): 2649 - Supprimer les classes de 2023-2024 qui n'ont aucun éleves
  api/migrations/20240711125727-delete_empty_classe.js
Labels: ADMIN

#4129 fix(api): il manque un params dans le template d'inscription des chef d'établissement
  api/src/emails/cle/classe.js
Labels: bug, bypass title, ADMIN

#4124 fix(admin): 3034 - [cle] fix wording
  admin/src/scenes/classe/components/GeneralInfos.tsx
Labels: ADMIN

#4135 fix(app, admin): Ne pas planter si le volontaire n'a pas de fichiers PM en ligne
  admin/src/scenes/volontaires/view/phase2MilitaryPreparationV2.jsx
  app/src/components/FallBackComponent.jsx
  app/src/scenes/militaryPreparation/components/DocumentsPM.jsx
Labels: bypass title

#4134 feat(api): 3001 - cle classes batch update
  api/src/__tests__/helpers/app.js
  api/src/__tests__/referent.test.ts
  api/src/__tests__/young-edition.test.ts
  api/src/__tests__/young.test.ts
  api/src/brevo.ts
  api/src/controllers/request.ts
  api/src/controllers/young/index.js
  api/src/geo.ts
  api/src/referent/referentController.ts
  api/src/routes.ts
  api/src/utils/validator.js
  api/src/young/edition/youngEditionController.ts
  api/src/young/edition/youngEditionService.ts
  api/src/young/email/youngEmailController.ts
  api/src/young/email/youngEmailService.ts
  api/src/young/youngController.ts
  package-lock.json
Labels: ADMIN

#4140 feat(api,admin): 2925 - delete coordinateurs
  admin/src/scenes/etablissement/components/ButtonAddCoordinator.tsx
  admin/src/scenes/etablissement/components/ButtonDeleteCoordinator.tsx
  admin/src/scenes/etablissement/components/ButtonEditChefEtablissement.tsx
  admin/src/scenes/etablissement/components/Contact.tsx
  admin/src/scenes/etablissement/components/types.ts
  admin/src/scenes/etablissement/view.tsx
  admin/src/services/api.js
  api/src/__tests__/alerte-message.test.ts
  api/src/__tests__/cle/etablissement.test.js
  api/src/__tests__/cle/referent-signup.test.ts
  api/src/__tests__/cle/referent.test.ts
  api/src/__tests__/cle/young.test.ts
  api/src/__tests__/helpers/app.js
  api/src/__tests__/plan-de-transport.test.ts
  api/src/__tests__/referent.test.ts
  api/src/__tests__/young-edition.test.ts
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/etablissement/etablissementController.ts
  api/src/cle/index.ts
  api/src/cle/referent/referentController.ts
  api/src/cle/referent/referentSignupController.ts
  api/src/cle/young/youngController.ts
  api/src/controllers/cle/index.js
  api/src/routes.ts
  packages/ds/src/admin/layout/Container.tsx
  packages/lib/src/constants/email.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4136 fix(api): 3028 - delete referent etablissement zombie
  api/migrations/20240725082212-delete-referent-etablissement-zombie.js
Labels: ADMIN

#4148 fix(api,admin): 2925 - delete coordinateurs
  admin/src/scenes/etablissement/components/ButtonAddCoordinator.tsx
  api/src/__tests__/cle/referent.test.ts
  api/src/cle/referent/referentController.ts
  packages/lib/src/roles.ts
Labels: ADMIN
