Repository betagouv/service-national-universel, pull requests merged in 2024-11, with the labels that each got.

#4487 feat(api, admin, lib): 3582 - Permettre d'archiver les cohortes
  admin/src/scenes/settings/tabs/GeneralTab.tsx
  api/migrations/20241023142732-add-cohort-status.js
  api/src/__tests__/application.test.ts
  api/src/__tests__/fixtures/cohort.ts
  api/src/cohort/cohortValidator.ts
  api/src/controllers/application.js
  api/src/controllers/mission.js
  api/src/controllers/young/reinscription.js
  api/src/services/application.ts
  api/src/utils/cohort.ts
  app/src/scenes/home/index.jsx
  app/src/scenes/reinscription/index.jsx
  app/src/utils/index.js
  packages/lib/src/constants/constants.ts
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/mongoSchema/cohort.ts
  packages/lib/src/sessions.ts
Labels: VOLONTAIRES

#4505 fix(api/aadmin/lib): 3608 - normalize department name
  admin/src/scenes/centersV2/list.jsx
  api/migrations/20241104135742-normalize_department_name_session.js
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
  packages/lib/src/region-and-departments.ts
Labels: Pull request title validation

#4507 feat(github): add merge queue
  .github/workflows/run-tests-api.yml
  .github/workflows/run-tests-front.yml
  .github/workflows/run-tests-lib.yml
Labels: Pull request title validation

#4509 test merge queue
  .github/workflows/run-tests-api.yml
  .github/workflows/run-tests-front.yml
  .github/workflows/run-tests-lib.yml
  api/src/auth.js
Labels: bypass title

#4511 test
  api/src/auth.js
Labels: Pull request title validation

#4512 test
  .github/workflows/run-tests-api.yml
Labels: Pull request title validation

#4516 up
  api/src/auth.js
Labels: Pull request title validation

#4517 up
  api/src/auth.js
Labels: Pull request title validation

#4519 up
  api/src/auth.js
Labels: Pull request title validation

#4510 fix(api): 3624 - Corriger le PUT de la réinscription
  api/src/controllers/young/reinscription.js
Labels: bug, VOLONTAIRES

#3785 refactor(admin): Remove call to Api Engagement from Associations page
  admin/src/scenes/association/components/Association.jsx
  admin/src/scenes/association/list.jsx
Labels: bypass title, VOLONTAIRES

#4523 Create cohort group hook
  admin/src/scenes/settings/index.tsx
  admin/src/scenes/settings/lib/cohortGroupService.ts
  admin/src/scenes/settings/lib/useCohortGroups.ts
  admin/src/scenes/settings/lib/useCreateCohortGroup.ts
  admin/src/scenes/settings/tabs/GeneralTab.tsx
  api/src/cohortGroup/cohortGroupController.ts
Labels: bypass title, VOLONTAIRES

#4307 feat(api): 2582 - add cron monitor certificats
  api/src/crons/index.js
  api/src/crons/monitorCertificats.js
Labels: FIABILISATION

#4527 feat(api): No ticket - Ajout d'une route publique pour avoir la liste des cohortes
  api/src/cohort/cohortController.ts
Labels: bypass title

#4496 feat(api,admin): 3565 - Ajout d'une page Historique de la classe
  admin/src/components/Loader.jsx
  admin/src/components/UserCard.jsx
  admin/src/scenes/classe/components/HistoryRow.tsx
  admin/src/scenes/classe/components/NavbarClasse.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/header/ClasseHeader.tsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view/Details.tsx
  admin/src/scenes/classe/view/Historique.tsx
  admin/src/scenes/classe/view/Inscriptions.tsx
  admin/src/scenes/classe/view/index.tsx
  admin/src/utils/index.jsx
  admin/src/utils/translateFieldsModel.ts
  api/src/__tests__/application.test.ts
  api/src/__tests__/cle/classe.test.ts
  api/src/__tests__/cle/young.test.ts
  api/src/__tests__/contract.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/young/youngController.ts
  api/src/controllers/application.js
  api/src/controllers/contract.js
  api/src/controllers/mission.js
  api/src/controllers/patches.js
  api/src/controllers/structure.js
  api/src/controllers/young/index.ts
  api/src/referent/referentController.ts
  packages/ds/src/admin/form/InputText.tsx
  packages/ds/src/admin/form/Select/Select.tsx
  packages/ds/src/admin/form/Select/theme.ts
  packages/lib/src/translation.ts
Labels: CLE

#4493 feat(admin): 3539 - Filtrer sur la liste des volontaires d’un PDR d’une ligne de bus depuis le PDT
  admin/src/components/SelectAction.tsx
  admin/src/components/filters-system-v2/components/Filters.tsx
  admin/src/components/filters-system-v2/components/export/ModalExport.tsx
  admin/src/scenes/classe/list.tsx
  admin/src/scenes/edit-transport/list/index.tsx
  admin/src/scenes/etablissement/List.tsx
  admin/src/scenes/plan-transport/ligne-bus/ListPDR.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/View.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/BusTeam.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Info.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
  admin/src/scenes/plan-transport/ligne-bus/components/DatePickerList.tsx
  admin/src/scenes/plan-transport/ligne-bus/components/Field.tsx
  admin/src/scenes/plan-transport/ligne-bus/components/Select.tsx
  admin/src/scenes/plan-transport/ligne-bus/index.tsx
  admin/src/scenes/pointDeRassemblement/List.tsx
  admin/src/scenes/utilisateur/list.tsx
  api/src/controllers/planDeTransport/ligne-de-bus.js
  packages/lib/src/plandetransport/ligneService.ts
Labels: WIP, R&R

#4528 feat(app,admin,api,lib): 3525 - Affichage des particularites access du PDR
  admin/src/scenes/pointDeRassemblement/List.tsx
  admin/src/scenes/pointDeRassemblement/View.tsx
  api/src/young/youngCertificateService.ts
  app/src/redux/auth/actions.ts
  app/src/redux/auth/reducer.ts
  app/src/scenes/phase1/components/modals/InfoConvocation.tsx
  app/src/scenes/phase1/scenes/affected/components/Convocation.tsx
  packages/lib/src/plandetransport/index.ts
  packages/lib/src/plandetransport/pdrService.ts
Labels: R&R

#4531 feat(bdc/app): 3656 - add balise jva-api
  app/index.html
  knowledge-base-public/src/pages/base-de-connaissance/index.js
Labels: bypass title

#4351 feat(api): anonymise newfields not specified by default
  api/package.json
  api/src/anonymization/PlanDeTransport/ligneBus.js
  api/src/anonymization/PlanDeTransport/modificationBus.js
  api/src/anonymization/application.js
  api/src/anonymization/cohesionCenter.js
  api/src/anonymization/contract.js
  api/src/anonymization/departmentService.js
  api/src/anonymization/meetingPoint.js
  api/src/anonymization/mission.js
  api/src/anonymization/missionEquivalence.js
  api/src/anonymization/referent.js
  api/src/anonymization/sessionPhase1.js
  api/src/anonymization/structure.js
  api/src/anonymization/waitingList.js
  api/src/anonymization/young.js
  api/src/utils/anonymise-model-fields.js
  package-lock.json
Labels: Pull request title validation

#4535 fix(crons): 3615 - fix departementName
  api/src/crons/JeVeuxAiderDaily.js
Labels: bypass title

#4545 fix(api,admin): 3677 - Inscription Goal utilisation du departemet de residence
  admin/src/scenes/phase0/YoungFooterNoRequest.tsx
  admin/src/scenes/volontaires/create.tsx
  api/src/controllers/young/index.ts
  api/src/controllers/young/phase1.ts
  api/src/referent/referentController.ts
  packages/lib/src/region-and-departments.spec.ts
  packages/lib/src/region-and-departments.ts
Labels: R&R

#4525 chore(api): 3583 - Mettre à jour la convocation
  api/src/utils/pdf-renderer.ts
  api/src/young/youngCertificateService.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4536 Suppression des fichiers d'import manuel des classes pour maj vers import automatique
  api/src/__tests__/cle/classeImport.test.ts
  api/src/cle/classe/import/classeCohortImport.ts
  api/src/cle/classe/import/classeCohortMapper.ts
  api/src/cle/classe/import/classeImportController.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
  api/src/cle/index.ts
Labels: bypass title

#4529 Poc classe Import
  admin/src/scenes/classe/Import.tsx
  admin/src/scenes/classe/index.jsx
  admin/src/scenes/classe/list.tsx
  api/package.json
  api/src/__tests__/cle/classeImportAuto.test.ts
  api/src/cle/classe/importAuto/classeImportAutoController.ts
  api/src/cle/classe/importAuto/classeImportAutoMapper.ts
  api/src/cle/classe/importAuto/classeImportAutoService.test.ts
  api/src/cle/classe/importAuto/classeImportAutoService.ts
  api/src/cle/classe/importAuto/classeImportAutoType.ts
  api/src/cle/index.ts
  api/src/services/fileService.ts
  package-lock.json
  packages/lib/src/constants/email.ts
Labels: CLE, bypass title

#4500 fix(admin): 3559 - Optimiser le chargement de la liste de candidatures
  admin/src/scenes/volontaires/view/phase2MilitaryPreparationV2.jsx
  admin/src/scenes/volontaires/view/phase2bis/EquivalenceList.tsx
  admin/src/scenes/volontaires/view/phase2bis/applicationList2.tsx
  admin/src/scenes/volontaires/view/phase2bis/components/SelectStatusApplicationPhase2.jsx
  admin/src/scenes/volontaires/view/phase2bis/view.jsx
  api/src/__tests__/referent.test.ts
  api/src/controllers/young/index.ts
  api/src/models/application.ts
  api/src/referent/referentController.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4508 feat(api, admin, lib): 3594 - Créer des groupes de cohortes
  admin/src/scenes/settings/components/CohortGroupSelector.tsx
  admin/src/scenes/settings/index.tsx
  admin/src/scenes/settings/lib/cohortGroupRepository.ts
  admin/src/scenes/settings/lib/useCohortGroups.ts
  admin/src/scenes/settings/lib/useCreateCohortGroup.ts
  admin/src/scenes/settings/tabs/GeneralTab.tsx
  admin/src/services/react-query.js
  api/migrations/20241105100553-add-cohort-groups.js
  api/src/__tests__/cohort-group.test.ts
  api/src/cohort/cohortController.ts
  api/src/cohort/cohortValidator.ts
  api/src/cohortGroup/cohortGroupController.ts
  api/src/models/cohort.ts
  api/src/models/cohortGroup.ts
  api/src/models/index.ts
  api/src/routes.ts
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/mongoSchema/cohort.ts
  packages/lib/src/mongoSchema/cohortGroup.ts
  packages/lib/src/mongoSchema/index.ts
  packages/lib/src/routes/cohortGroup/index.ts
  packages/lib/src/routes/index.ts
Labels: VOLONTAIRES

#4543 feat(apiv2,snu-lib): add async tasks capabilities
  apiv2/README.md
  apiv2/package.json
  apiv2/src/App.module.ts
  apiv2/src/MainJob.module.ts
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/AdminJob.module.ts
  apiv2/src/admin/infra/iam/guard/SuperAdmin.guard.ts
  apiv2/src/admin/infra/sejours/cle/initProvider/guard.ts
  apiv2/src/admin/infra/task/AdminTask.consumer.ts
  apiv2/src/admin/infra/task/AdminTaskMongo.repository.ts
  apiv2/src/admin/infra/task/api/AdminTask.controller.ts
  apiv2/src/infra/Queue.module.ts
  apiv2/src/main.ts
  apiv2/src/mainJob.ts
  apiv2/src/notification/Notification.module.ts
  apiv2/src/notification/NotificationJob.module.ts
  apiv2/src/notification/infra/Notification.producer.ts
  apiv2/src/notification/infra/Notification.ts
  apiv2/src/notification/infra/email/Contact.consumer.ts
  apiv2/src/notification/infra/email/Contact.producer.ts
  apiv2/src/notification/infra/email/Email.consumer.ts
  apiv2/src/shared/infra/Queue.ts
  apiv2/src/task/Task.module.ts
  apiv2/src/task/core/Task.gateway.ts
  apiv2/src/task/core/Task.model.ts
  apiv2/src/task/infra/Task.mapper.ts
  apiv2/src/task/infra/TaskMongo.provider.ts
  apiv2/src/task/infra/TaskMongo.repository.ts
  apiv2/test/admin/setUpAdminTest.ts
  apiv2/test/architecture/Architecture.spec.ts
  apiv2/tsconfig.json
  packages/lib/src/constants/task.ts
  packages/lib/src/index.ts
  packages/lib/src/mongoSchema/index.ts
  packages/lib/src/mongoSchema/task.ts
Labels: bypass title

#4553 fix(api): bug cors snupport
  api/config/default.js
  api/config/production.js
  api/src/main.js
Labels: bypass title

#4524 feat(admin): 3259 - Donner les droits apres la fin de la date d'instruction aux référents
  admin/src/scenes/volontaires/view/index.tsx
  api/src/referent/referentController.ts
  api/src/young/edition/youngEditionController.ts
  packages/lib/src/roles.ts
Labels: R&R

#4560 chore(dep): mise à niveau dependances node 20
  admin/package.json
  app/package.json
  knowledge-base-public/package-lock.json
  package-lock.json
  package.json
  packages/lib/src/mongoSchema/cohortGroup.ts
  packages/lib/src/mongoSchema/referent.ts
Labels: bypass title, FIABILISATION

#4561 chore(apiv2): add admin alias
  apiv2/package.json
  apiv2/src/admin/infra/iam/Contact.gateway.ts
  apiv2/src/admin/infra/iam/api/Auth.controller.ts
  apiv2/src/admin/infra/iam/auth/AddUserToRequest.middleware.ts
  apiv2/src/admin/infra/iam/auth/Auth.provider.ts
  apiv2/src/admin/infra/iam/auth/JwtToken.service.ts
  apiv2/src/admin/infra/iam/auth/ReferentAuth.facade.ts
  apiv2/src/admin/infra/iam/auth/ReferentAuthFacade.spec.ts
  apiv2/src/admin/infra/iam/repository/mongo/Referent.mapper.ts
  apiv2/src/admin/infra/iam/repository/mongo/ReferentMongo.repository.ts
  apiv2/src/admin/infra/sejours/cle/classe/guard/ClasseAdminCle.guard.spec.ts
  apiv2/src/admin/infra/sejours/cle/classe/guard/ClasseAdminCle.guard.ts
  apiv2/src/admin/infra/sejours/cle/classe/guard/ClasseGuard.service.ts
  apiv2/src/admin/infra/sejours/cle/classe/guard/ClasseGuardService.spec.ts
  apiv2/src/admin/infra/sejours/cle/etablissement/Etablissement.mapper.ts
  apiv2/src/admin/infra/sejours/cle/etablissement/Etablissement.repository.ts
  apiv2/src/admin/infra/sejours/cle/initProvider/gateway.ts
  apiv2/src/admin/infra/sejours/cle/initProvider/guard.ts
  apiv2/src/admin/infra/sejours/cle/initProvider/useCase.ts
  apiv2/src/notification/Notification.module.ts
  apiv2/src/notification/infra/email/Contact.consumer.ts
  apiv2/src/notification/infra/email/Contact.producer.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevo.provider.ts
  apiv2/src/notification/infra/email/brevo/MockEmailBrevo.provider.ts
  apiv2/test/admin/iam/ReferentHelper.ts
  apiv2/test/admin/iam/ReferentMongo.repository.spec.ts
  apiv2/test/admin/sejour/cle/EtablissementHelper.ts
  apiv2/test/admin/sejour/cle/classe/Classe.controller.spec.ts
  apiv2/test/admin/sejour/cle/classe/ClasseHelper.ts
  apiv2/test/admin/sejour/cle/classe/ClasseMongo.repository.spec.ts
  apiv2/test/admin/setUpAdminTest.ts
  apiv2/tsconfig.json
Labels: Pull request title validation, bypass title

#4538 feat(api): 3567 - Automatiser le script de validation de la phase 1
  api/migrations/20241120144707-add-daysToValidate-cohort.js
  api/src/crons/__tester__.ts
  api/src/crons/autoValidatePhase1.ts
  api/src/crons/index.js
  api/src/sentry.js
  api/src/slack.js
  api/src/utils/index.js
  api/src/utils/old_cohorts_logic.js
  devops/analytics/src/index.js
  packages/lib/src/mongoSchema/cohort.ts
Labels: R&R

#4563 fix(analytics): supprimer le retour inutile dans le script d'index
  devops/analytics/src/index.js
Labels: Pull request title validation

#4549 refactor(app): Uniformiser le conteneur de page
  app/package.json
  app/src/components/layout/Container.tsx
  app/src/components/layout/navbar/index.jsx
  app/src/components/layout/navbar/useTickets.ts
  app/src/scenes/missions/list/index.jsx
  app/src/scenes/phase1/components/modals/InfoConvocation.tsx
  app/src/scenes/phase2/components/Header.jsx
  app/src/scenes/phase2/scenes/MesEngagements/index.jsx
  app/src/scenes/phase2/scenes/MonEquivalence/EditEquivalence.jsx
  app/src/scenes/phase2/scenes/MonEquivalence/MonEquivalence.jsx
  app/src/scenes/phase2/scenes/Program/index.jsx
  app/src/services/react-query.ts
  package-lock.json
Labels: bypass title, VOLONTAIRES

#4551 fix(app): 3681 - Améliorer la gestion d'erreur de l'étape consentement du RL1
  app/src/scenes/representants-legaux/mobile/consentement.jsx
Labels: bug, WAITING FOR QA, VOLONTAIRES

#4572 fix(misc): Fix destroy-environment script
  devops/scripts/destroy-environment.js
Labels: bypass title

#4577 feat(devops): update source list for amd and arm platform
  devops/local/Dockerfile.env-setup
Labels: bypass title

#4579 feat(apiv2): add prefix to apiv2 to prod env
  apiv2/src/admin/infra/sejours/cle/classe/api/Classe.controller.ts
  apiv2/src/admin/infra/sejours/cle/classe/api/ClassePublic.controller.ts
  apiv2/src/admin/infra/sejours/cle/classe/repository/mongo/ClasseMongo.repository.ts
  apiv2/src/main.ts
Labels: bypass title

#4576 fix(app): 3731 - Ne pas planter en cas d'échec au fetch du nombre de tickets
  app/src/components/layout/navbar/components/UserCard.jsx
  app/src/components/layout/navbar/components/UserMenu.jsx
  app/src/components/layout/navbar/index.jsx
Labels: VOLONTAIRES
