Repository betagouv/service-national-universel, pull requests merged in 2024-10, with the labels that each got.

#4392 fix(api): 3424 - les sessions de certains centres ne s’affichent pas
  api/migrations/20241001090255-denormalize-cohort-in-session.js
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
Labels: ADMIN

#4391 fix(bdc): bug plausible script
  knowledge-base-public/src/pages/_document.js
Labels: Pull request title validation

#4395 feat(api): 3426 - renommer les doublons de centre avec un préfixe
  api/migrations/20241001125505-rename-center-without-matricule.js
Labels: ADMIN

#4398 feat(api): 3425 - import classe and update youngs cohort
  api/migrations/20241002092133-feature-flag-cle-import-true.js
  api/src/__tests__/cle/classeImport.test.ts
  api/src/cle/classe/import/classeCohortImport.ts
  api/src/cle/classe/import/classeCohortMapper.ts
  api/src/cle/classe/import/classeImportController.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
Labels: ADMIN

#4403 resolution des conflits du commit c750f4eb8267f897ce7f94778cfb1266b0918723
  packages/lib/src/roles.ts
Labels: bypass title

#4401 chore(api): add pull-staging.sh script
  api/src/scripts/pull_staging.sh
Labels: FIABILISATION

#4407 fix(api): script de migrations pour renommer les department et acadenie des centres
  api/migrations/20241003102056-mapper_department.js
  api/src/cohesionCenter/import/cohesionCenterImportMapper.ts
Labels: bug, bypass title, ADMIN

#4409 fix(bdc): bug stats plausible
  knowledge-base-public/src/pages/_document.js
Labels: Pull request title validation

#4413 fix(api): fix de la derniere migratons sur le mapper des department pour les centre, qui marche en CI mais pas en prod
  api/migrations/20241003102056-mapper_department.js
Labels: bug, bypass title

#4385 fix(admin,api): 3323 - prise en compte du département de scolarisation du jeune pour le dépassement des objectifs
  admin/src/scenes/phase0/view.tsx
  admin/src/scenes/volontaires/view/index.tsx
  api/src/__tests__/fixtures/application.ts
  api/src/__tests__/fixtures/bus.ts
  api/src/__tests__/fixtures/classe.ts
  api/src/__tests__/fixtures/inscriptionGoal.ts
  api/src/__tests__/fixtures/meetingPoint.ts
  api/src/__tests__/fixtures/sessionPhase1.ts
  api/src/__tests__/fixtures/young.ts
  api/src/__tests__/inscription-goal.test.ts
  api/src/__tests__/referent.test.ts
  api/src/controllers/inscription-goal.ts
  api/src/referent/referentController.ts
  api/src/routes.ts
  api/src/services/inscription-goal.test.ts
  api/src/services/inscription-goal.ts
  packages/lib/src/constants/functionalErrors.ts
  packages/lib/src/translation.ts
Labels: R&R

#4415 fix(api): fix young admin validation
  api/src/referent/referentController.ts
Labels: bypass title

#4361 fix(app): 3024 - fix link to BDC ChangeSejour component
  app/src/components/modals/ModalForm.jsx
  app/src/scenes/phase1/changeSejour.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4364 fix(app): 3351 - Change wording in contactForm
  app/src/scenes/contact/contact.service.js
Labels: WAITING FOR QA, VOLONTAIRES

#4373 feat(app): 3282 - Prevent special letter on Input Name
  app/package.json
  app/src/scenes/inscription2023/steps/correction/stepProfil.jsx
  app/src/scenes/inscription2023/steps/stepRepresentants.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
  package-lock.json
Labels: WAITING FOR QA, VOLONTAIRES

#4411 feat(app, api, admin): 3384 - Add new Url on Programs for JVA tracking
  api/src/models/program.ts
  app/src/scenes/phase2/scenes/Program/index.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4425 chore(bdc): change wording
  knowledge-base-public/src/components/Header.jsx
Labels: Pull request title validation

#4424 chore(github): run api test only on changes
  .github/workflows/deploy-custom-env.yml
  .github/workflows/run-tests-api-pr.yml
Labels: FIABILISATION

#4382 feat(api): 3258 - Permettre de sélectionner un référent de classe comme coordinateur
  admin/src/scenes/etablissement/components/ButtonAddCoordinator.tsx
  admin/src/scenes/etablissement/components/GeneralInfos.tsx
  admin/src/scenes/etablissement/components/modale/FirstLoginAdminChef.tsx
  admin/src/scenes/etablissement/utils/index.ts
  admin/src/scenes/etablissement/view.tsx
  api/src/cle/referent/referentController.ts
  api/src/referent/referentController.ts
  api/src/services/cle/referent.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/mongoSchema/cle/etablissement.ts
Labels: CLE, ADMIN

#4388 feat(api): 3415 - import PDR
  admin/src/scenes/pointDeRassemblement/List.tsx
  admin/src/scenes/pointDeRassemblement/View.tsx
  admin/src/scenes/pointDeRassemblement/components/Field.tsx
  admin/src/scenes/pointDeRassemblement/components/ModalConfirmDelete.tsx
  admin/src/scenes/pointDeRassemblement/components/ModalCreation.jsx
  admin/src/services/api-adresse.js
  admin/src/services/api-adresse.ts
  api/src/__tests__/fixtures/PlanDeTransport/pointDeRassemblement.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/__tests__/point-de-rassemblement.test.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
  api/src/cle/classes/classesController.ts
  api/src/cohesionCenter/import/cohesionCenterImportService.ts
  api/src/controllers/elasticsearch/lignebus.js
  api/src/controllers/elasticsearch/plandetransport.js
  api/src/controllers/elasticsearch/pointderassemblement.js
  api/src/controllers/elasticsearch/populate/populateYoung.js
  api/src/controllers/mission.js
  api/src/controllers/planDeTransport/edit-transport.js
  api/src/controllers/planDeTransport/import.js
  api/src/controllers/planDeTransport/ligne-de-bus.js
  api/src/controllers/session-phase1.ts
  api/src/controllers/young/phase1.js
  api/src/controllers/young/point-de-rassemblement.js
  api/src/planDeTransport/index.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportUtils.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImport.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportController.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportMapper.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportService.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportValidator.ts
  api/src/planDeTransport/pointDeRassemblement/index.ts
  api/src/planDeTransport/pointDeRassemblement/pointDeRassemblementController.ts
  api/src/routes.ts
  api/src/scripts/pull_staging.sh
  api/src/scripts/reindex_es_all_models/index.js
  api/src/services/dashboard/todo-sejour.service.js
  api/src/services/fileService.test.ts
  api/src/services/fileService.ts
  api/src/services/gouv.fr/api-adresse.js
  api/src/services/gouv.fr/api-adresse.ts
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
  packages/ds/src/admin/ui/Button.tsx
  packages/ds/src/common/forms/AddressForm.tsx
  packages/ds/src/common/inputs/Input.tsx
  packages/lib/src/dto/userDto.ts
  packages/lib/src/mongoSchema/planDeTransport/pointDeRassemblement.ts
  packages/lib/src/roles.ts
Labels: WIP, R&R

#4431 fix(api): 3517 - suppression du filtre des PDR sur les PDT
  api/src/controllers/elasticsearch/plandetransport.js
Labels: RUN, R&R

#4434 fix(app): Do not call address API if wasBornInFranceBool is undefined
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
Labels: bypass title, VOLONTAIRES

#4422 chore(lib): bump to mongoose 7
  api/package.json
  api/src/__tests__/helpers/contract.ts
  api/src/__tests__/helpers/departmentService.ts
  api/src/__tests__/helpers/mission.ts
  api/src/__tests__/helpers/program.ts
  api/src/__tests__/helpers/referent.ts
  api/src/__tests__/helpers/structure.ts
  api/src/__tests__/helpers/young.ts
  api/src/__tests__/table-de-repartition.test.ts
  api/src/cohesionCenter/cohesionCenterController.js
  api/src/controllers/application.js
  api/src/controllers/filters.js
  api/src/controllers/mission.js
  api/src/controllers/patches.js
  api/src/controllers/planDeTransport/commons.js
  api/src/controllers/planDeTransport/demande-de-modification.js
  api/src/controllers/planDeTransport/ligne-de-bus.js
  api/src/controllers/planDeTransport/schema-de-repartition.js
  api/src/controllers/planDeTransport/table-de-repartition.js
  api/src/controllers/program.js
  api/src/controllers/session-phase1.ts
  api/src/controllers/structure.js
  api/src/controllers/young/documents.js
  api/src/crons/deleteInactiveRefs.js
  api/src/crons/patch/application.js
  api/src/crons/patch/classe.js
  api/src/crons/patch/mission.js
  api/src/crons/patch/missionEquivalence.js
  api/src/crons/patch/structure.js
  api/src/crons/patch/young.js
  api/src/models/referent.ts
  api/src/models/young.ts
  api/src/referent/referentController.ts
  package-lock.json
  package.json
  packages/lib/package.json
  patches/mongoose-patch-history+2.0.0.patch
  send-in-blue/package.json
Labels: dependencies, FIABILISATION

#4436 fix(api): 3528 - suppression du filtre sur les PDR lors de l'affectation manuel d'un jeune
  api/src/planDeTransport/pointDeRassemblement/pointDeRassemblementController.ts
Labels: RUN, R&R

#4429 fix(api, admin): 3511 - Ajouter le lien INJEP pour les admins et programmer le cron
  admin/src/components/drawer/utils.js
  api/src/crons/index.js
Labels: WAITING FOR QA, VOLONTAIRES

#4433 chore(api): speedup tests
  .github/workflows/run-tests-api-pr.yml
  .github/workflows/run-tests-api.yml
  .github/workflows/run-tests-front.yml
  .github/workflows/run-tests-lib.yml
  api/docker-compose.dev.yml
  api/jest-sequencer-alphabetical.js
  api/jest.config.js
  api/package.json
  api/src/__tests__/alerte-message.test.ts
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/__tests__/cle/classe.test.ts
  api/src/__tests__/cle/classeImport.test.ts
  api/src/__tests__/cle/classes.test.ts
  api/src/__tests__/cle/etablissement.test.ts
  api/src/__tests__/cle/referent-signup.test.ts
  api/src/__tests__/cle/referent.test.ts
  api/src/__tests__/demande-de-modification.test.ts
  api/src/__tests__/fixtures/cohesionCenter.ts
  api/src/__tests__/fixtures/inscriptionGoal.ts
  api/src/__tests__/helpers/classe.ts
  api/src/__tests__/helpers/cohesionCenter.ts
  api/src/__tests__/helpers/db.ts
  api/src/__tests__/inscription-goal.test.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/__tests__/ligne-to-point.test.ts
  api/src/__tests__/plan-de-transport.test.ts
  api/src/__tests__/point-de-rassemblement.test.ts
  api/src/__tests__/referent.test.ts
  api/src/__tests__/table-de-repartition.test.ts
  api/src/__tests__/young-edition.test.ts
  package-lock.json
  packages/lib/package.json
Labels: FIABILISATION

#4432 feat(admin): 3374 - add SanitaryContactEmail on Center search and export
  admin/src/scenes/centersV2/list.jsx
  api/src/controllers/elasticsearch/sessionphase1.js
Labels: VOLONTAIRES

#4438 fix(api): 3532 - on retire le filtre sur les pdr lors de l'affectation manuelle d'un jeune
  api/src/controllers/young/phase1.js
Labels: bug, ADMIN

#4437 fix(api): Ne plus anonymiser les données du centre dans les objet SessionPhase1
  api/src/anonymization/sessionPhase1.js
Labels: bug, bypass title, ADMIN

#4421 feat(admin, app): 3440 - Add sanitaryContactEmail on Cohort CLE
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
Labels: WAITING FOR QA, VOLONTAIRES

#4443 fix(api): fix du state Manager car le CRON ouvrent et ferment des classes sans cesse
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/stateManager.ts
Labels: bypass title

#4447 chore(dep): bump mongo 7 for tests and local
  .github/workflows/run-tests-api-pr.yml
  .github/workflows/run-tests-api.yml
  api/docker-compose.dev.yml
Labels: bypass title, FIABILISATION

#4383 feat(app): 2329 - Ajouter des informations liés à l'établissement sur le jeune (HZR)
  admin/src/hooks/useMouseOver.ts
  admin/src/scenes/phase0/components/Buttons.tsx
  admin/src/scenes/phase0/components/CorrectedRequest.tsx
  admin/src/scenes/phase0/components/CorrectionRequest.tsx
  admin/src/scenes/phase0/components/Field.tsx
  admin/src/scenes/phase0/components/FieldsGroup.jsx
  admin/src/scenes/phase0/components/PhoneField.tsx
  admin/src/scenes/phase0/components/Section.tsx
  admin/src/scenes/phase0/components/sections/SectionParents.jsx
  admin/src/scenes/phase0/components/sections/identite/SectionIdentite.tsx
  admin/src/scenes/phase0/components/sections/identite/SectionIdentiteContact.tsx
  admin/src/scenes/phase0/utils/index.ts
  admin/src/scenes/phase0/view.tsx
  admin/src/scenes/volontaires-head-center/view.jsx
  admin/src/scenes/volontaires/view/index.tsx
  packages/lib/src/dto/youngDto.ts
  packages/lib/src/translation.ts
Labels: R&R

#4317 chore(api): poc eligibility add tests
  .codeclimate.yml
  admin/src/scenes/phase0/components/ChangeCohortPen.tsx
  admin/src/scenes/plan-transport/schema-repartition/components/BoxCentres.tsx
  admin/src/scenes/volontaires/create.jsx
  admin/src/services/cohortService.ts
  api/src/__tests__/__mocks__/passport.ts
  api/src/__tests__/application.test.ts
  api/src/__tests__/cle/classe.test.ts
  api/src/__tests__/cohort-session.test.ts
  api/src/__tests__/fixtures/young.ts
  api/src/__tests__/helpers/app.ts
  api/src/__tests__/young-preinscription.test.ts
  api/src/cohort/cohortService.ts
  api/src/cohort/cohortValidator.ts
  api/src/controllers/cohort-session.js
  api/src/controllers/cohort-session.ts
  api/src/middlewares/authMiddleware.ts
  api/src/preinscription/preinscriptionController.ts
  api/src/preinscription/preinscriptionValidator.ts
  api/src/referent/referentController.ts
  api/src/routes.ts
  api/src/utils/cohort.ts
  app/src/scenes/account/scenes/general/components/ChangeAddressModal/index.jsx
  app/src/services/cohort.service.js
  app/src/services/cohort.service.ts
  app/src/utils/buildRequest.ts
  packages/lib/src/region-and-departments.ts
  packages/lib/src/routes/cohort/get.ts
  packages/lib/src/routes/cohort/getIsIncriptionOpen.ts
  packages/lib/src/routes/cohort/getIsReIncriptionOpen.ts
  packages/lib/src/routes/cohort/index.ts
  packages/lib/src/routes/cohort/postEligibility.ts
  packages/lib/src/routes/index.ts
  packages/lib/src/routes/preinscription/index.ts
  packages/lib/src/routes/preinscription/postEligibility.ts
  packages/lib/src/utils/date.ts
  packages/lib/src/utils/request.spec.ts
  packages/lib/src/utils/request.ts
Labels: WIP, R&R

#4448 chore(api): remove passport from test
  .github/workflows/run-tests-api.yml
  api/src/__tests__/cohesion-center.test.ts
  api/src/__tests__/contract.test.ts
  api/src/__tests__/department-service.test.ts
  api/src/__tests__/email.test.ts
  api/src/__tests__/fixtures/young.ts
  api/src/__tests__/helpers/app.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/__tests__/mission.test.ts
  api/src/__tests__/point-de-rassemblement.test.ts
  api/src/__tests__/program.test.ts
  api/src/__tests__/referent-auth.test.ts
  api/src/__tests__/referent.test.ts
  api/src/__tests__/session-phase1.test.ts
  api/src/__tests__/structure.test.ts
  api/src/__tests__/young-auth.test.ts
  api/src/__tests__/young-inscription.test.ts
  api/src/__tests__/young.test.ts
Labels: FIABILISATION

#4444 feat(admin,api): Ajout d'un filtre sur les classes pour les classes vides / non vides
  admin/src/components/filters-system-v2/components/Filter.ts
  admin/src/components/filters-system-v2/components/filters/FilterPopOver.tsx
  admin/src/scenes/classe/list.tsx
  api/src/controllers/elasticsearch/cle/classe.js
  api/src/controllers/elasticsearch/utils.js
Labels: CLE, bypass title

#4442 fix(lib): 3536 - vérification des objectifs pour les jeunes résidant à l'étranger
  api/src/__tests__/application.test.ts
  api/src/__tests__/cohort-session.test.ts
  api/src/__tests__/fixtures/young.ts
  packages/lib/package.json
  packages/lib/src/region-and-departments.spec.ts
  packages/lib/src/region-and-departments.ts
Labels: R&R

#4453 fix(api): 3542 - verification objectif affectation manuel
  admin/src/scenes/volontaires/components/ModalAffectation.jsx
  admin/src/scenes/volontaires/components/ModalChangePDRSameLine.jsx
  api/src/__tests__/fixtures/young.ts
  api/src/__tests__/helpers/app.ts
  api/src/__tests__/young-phase1.test.ts
  api/src/controllers/young/index.js
  api/src/controllers/young/phase1.ts
Labels: RUN, R&R

#4445 up
  admin/src/scenes/centersV2/view/CenterInformations.tsx
  api/migrations/20241011143010-softdelete-centers-without-matricule.js
  api/src/cle/classe/export/classeExportService.ts
  api/src/cohesionCenter/cohesionCenterController.js
  api/src/controllers/elasticsearch/cohesioncenter.js
  api/src/controllers/elasticsearch/young.js
  api/src/crons/dsnjExport/utils.js
  packages/lib/src/mongoSchema/cohesionCenter.ts
Labels: Pull request title validation

#4441 feat(app): 3048 - Seuls les modérateurs peuvent dispenser les volontaires
  admin/src/scenes/phase0/components/PhaseStatusSelector.jsx
  admin/src/scenes/volontaires/components/phase1/Phase1Header.jsx
  api/src/young/edition/youngEditionController.ts
  packages/lib/src/roles.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4460 refactor(api,admin): Ajout du cohortId lors de l'invitation manuel d'un jeune
  admin/src/components/ui/forms/DatePicker.jsx
  admin/src/components/ui/forms/DatePicker.tsx
  admin/src/components/ui/forms/Field.tsx
  admin/src/components/ui/forms/InputText.tsx
  admin/src/components/ui/forms/InputTextarea.tsx
  admin/src/components/ui/forms/NumberInput.tsx
  admin/src/components/ui/forms/dateForm/DatePickerInput.tsx
  admin/src/components/ui/forms/dateForm/SimpleToggle.tsx
  admin/src/components/ui/forms/dateForm/ToggleDate.tsx
  admin/src/scenes/phase0/components/ConfirmationModal.tsx
  admin/src/scenes/phase0/components/FieldSituationsParticulieres.tsx
  admin/src/scenes/phase0/components/MiniSwitch.tsx
  admin/src/scenes/phase0/components/RadioButton.tsx
  admin/src/scenes/phase0/components/SchoolEditor.tsx
  admin/src/scenes/phase0/components/VerifyAddress.tsx
  admin/src/scenes/volontaires/create.tsx
  api/src/__tests__/young.test.ts
  api/src/controllers/session-phase1.ts
  api/src/controllers/young/index.ts
  api/src/crons/index.js
  api/src/routes.ts
  api/src/utils/validator.ts
  packages/lib/src/common.ts
  packages/lib/src/sessions.spec.ts
  packages/lib/src/sessions.ts
Labels: bypass title, ADMIN

#4454 fix(api): 3542 - vérification du dépassement des objectifs de la region
  admin/src/index.jsx
  api/src/__tests__/cohort-session.test.ts
  api/src/__tests__/fixtures/PlanDeTransport/pointDeRassemblement.ts
  api/src/__tests__/fixtures/cohesionCenter.ts
  api/src/__tests__/fixtures/departmentService.ts
  api/src/__tests__/fixtures/inscriptionGoal.ts
  api/src/__tests__/fixtures/mission.ts
  api/src/__tests__/fixtures/program.ts
  api/src/__tests__/fixtures/referent.ts
  api/src/__tests__/fixtures/structure.ts
  api/src/__tests__/fixtures/young.ts
  api/src/__tests__/inscription-goal.test.ts
  api/src/__tests__/referent.test.ts
  api/src/__tests__/young-phase1.test.ts
  api/src/controllers/inscription-goal.ts
  api/src/controllers/young/account.ts
  api/src/controllers/young/index.ts
  api/src/controllers/young/phase1.ts
  api/src/models/young.ts
  api/src/referent/referentController.ts
  api/src/services/inscription-goal.test.ts
  api/src/services/inscription-goal.ts
  app/src/index.jsx
  packages/lib/src/constants/functionalErrors.ts
  packages/lib/src/translation.ts
Labels: R&R

#4464 feat(api): modifier l'import des classes pour prendre en compte les nouvelles regles
  api/src/__tests__/cle/classeImport.test.ts
  api/src/cle/classe/import/classeCohortImport.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
Labels: bypass title

#4466 Fix softdelete anonymize email
  api/src/services/cle/referent.ts
Labels: Pull request title validation

#4435 fix(api): 3480 - fix inscription and ReinscriptionStep when changeCoh…
  api/migrations/20241010123909-updateinscriptionStepForYoungCleBug.js
  api/src/referent/referentController.ts
Labels: VOLONTAIRES

#4469 feat(api, lib): 3564 - Ajouter le nouveau modèle d'attestation et mettre à jour le wording
  api/src/templates/certificate/phase1.ts
  api/src/templates/certificate/phase2.js
  packages/lib/src/constants/constants.ts
Labels: VOLONTAIRES

#4471 feat(admin): 3333 - MAJ le filtre cohorte du TDB pour que les cohortes 2025
  admin/src/scenes/dashboardV2/components/inscription/General.tsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/engagement/index.tsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/general/components/Objective.tsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/inscription/index.tsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/index.tsx
  admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.jsx
  admin/src/scenes/dashboardV2/visitor/subscenes/inscription/index.tsx
  admin/src/services/cohort.service.ts
  packages/ds/src/admin/ui/DropdownButton.tsx
Labels: R&R

#4462 feat(admin): 3371 - Validation directement vers liste complémentaire
  admin/src/scenes/phase0/YoungConfirmationModal.tsx
  admin/src/scenes/phase0/YoungFooterNoRequest.tsx
  admin/src/scenes/phase0/YoungFooterPending.tsx
  admin/src/scenes/phase0/YoungFooterSent.tsx
  admin/src/scenes/phase0/commons.ts
  admin/src/scenes/phase0/components/ConfirmModalContent.tsx
  admin/src/scenes/phase0/view.tsx
  admin/src/services/inscriptionGoalService.ts
  api/src/controllers/inscription-goal.ts
  packages/lib/src/dto/youngDto.ts
  packages/lib/src/routes/index.ts
  packages/lib/src/routes/inscriptiongoal/getTauxRemplissage.ts
  packages/lib/src/routes/inscriptiongoal/index.ts
Labels: R&R

#4430 feat(infra): 3513 - Clean stack script
  .github/workflows/destroy-environment-wip.yml
  devops/scripts/clean-ci.js
  devops/scripts/destroy-environment.js
  devops/scripts/get-environment-name.js
  devops/scripts/lib/github-client.js
  devops/scripts/lib/scaleway-client.js
  devops/scripts/lib/user-input.js
  devops/scripts/lib/utils.js
Labels: bypass title

#4477 fix(admin): fix du breadcrumb utilisateur et suppression onglet Dev dans l'env production
  admin/src/components/drawer/SideBar.tsx
  admin/src/scenes/develop/DesignSystemPage.jsx
  admin/src/scenes/utilisateur/list.jsx
Labels: bypass title

#4482 fix(api): bug deletedat export
  api/src/crons/dsnjExport/utils.js
Labels: Pull request title validation

#4483 fix(api) - supression du model des mails dans la liste usefull du script reindex
  api/src/scripts/reindex_es_all_models/index.js
Labels: bypass title

#4491 fix(api): bug script anonymize
  api/src/scripts/anonymization/docker/start_anonymize_db.sh
Labels: Pull request title validation

#4484 feat(api): 3198 - Candidater à une mission - évolution de la règle d'âge minimum
  api/src/services/application.js
Labels: WAITING FOR QA, VOLONTAIRES

#4478 fix(app): 3518 - fix situation when schooled change
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4479 feat(app): 3441 - Inciter les élèves à poursuivre leur inscription
  admin/src/scenes/classe/header/ButtonLinkInvite.tsx
  app/src/assets/pictograms/pen.svg
  app/src/scenes/cle/OnBoarding.tsx
  app/src/scenes/cle/useClass.ts
  app/src/scenes/contact/components/PublicContactForm.jsx
  app/src/scenes/preinscription/components/AlreadyHaveAnAccountModal.tsx
  app/src/scenes/preinscription/components/Modals.ts
  app/src/scenes/preinscription/steps/stepProfil.jsx
  app/src/services/classe.service.js
  packages/ds/src/dsfr/layout/Container.tsx
Labels: WAITING FOR QA, VOLONTAIRES

#4426 feat(app): 3243 - Formulaire de contact : donner aux utilisateurs CLE accès aux questions sur la phase 2
  app/src/components/dsfr/forms/EnhancedRadioButton.jsx
  app/src/scenes/contact/components/Article.jsx
  app/src/scenes/contact/components/PublicContactForm.jsx
  app/src/scenes/contact/components/Solutions.jsx
  app/src/scenes/contact/contact.service.js
  app/src/scenes/contact/index.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4489 chore(api): 3585 - Mettre à jour l'ID de la liste de diffusion "Inscription"
  api/src/brevo.ts
  api/src/preinscription/preinscriptionController.ts
Labels: VOLONTAIRES

#4485 fix(app): 2970 - remove psc1Info specific Case for Toussaint
  api/src/__tests__/young-inscription.test.ts
  api/src/controllers/young/inscription2023.js
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4494 fix(api,admin): 3603 - Bloquer les inscriptions aux objectifs départementaux et non régionaux
  admin/src/scenes/phase0/YoungFooterNoRequest.tsx
  api/src/__tests__/inscription-goal.test.ts
  api/src/services/inscription-goal.test.ts
  api/src/services/inscription-goal.ts
Labels: RUN

#4404 feat(api, admin): 3283 - Add manual inscription rights according to dynamic CLE settings
  admin/src/scenes/classe/header/index.tsx
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/settings/index.jsx
  admin/src/scenes/settings/phase0/ManualInscriptionSettings.tsx
  admin/src/scenes/settings/phase0/getManualInscriptionTogglesByCohortType.tsx
  admin/src/scenes/volontaires/create.tsx
  api/migrations/20241002075633-add-inscription-controls-to-cohort.js
  api/src/__tests__/young.test.ts
  api/src/cohort/cohortValidator.ts
  api/src/controllers/young/index.ts
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/mongoSchema/cohort.ts
  packages/lib/src/roles.ts
Labels: R&R

#4499 chore-3592-test-github-queue
  api/src/main.js
Labels: Pull request title validation

#4501 chore(api): cron coherence cohortId - ne pas check les young deleted
  api/src/crons/checkCoherence.ts
  api/src/crons/index.js
Labels: FIABILISATION

#4498 fix(app): 3378 - Prevent error 400 when not_scolarise young create Brevo con…
  app/src/scenes/preinscription/components/CreateContactForm.tsx
Labels: WAITING FOR QA, VOLONTAIRES

#4502 fix(api): 3611 - fix updatePhase2hoursAndStatus
  api/src/utils/index.js
Labels: VOLONTAIRES

#4492 feat(api): 3576 - Bloquer l’impersonate pour le sous rôle god
  admin/src/app.jsx
  admin/src/components/drawer/SideBar.tsx
  admin/src/scenes/contact/list.jsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/engagement/index.tsx
  admin/src/scenes/utilisateur/composants/UserHeader.jsx
  admin/src/scenes/utilisateur/list.tsx
  admin/src/utils/signinAs.ts
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/__tests__/cle/classe.test.ts
  api/src/__tests__/cle/classeImport.test.ts
  api/src/__tests__/cle/classes.test.ts
  api/src/__tests__/cle/referent.test.ts
  api/src/__tests__/cohort.test.ts
  api/src/__tests__/referent.test.ts
  api/src/cle/classe/classeService.test.ts
  api/src/referent/referentController.ts
  api/src/utils/validator.ts
  packages/lib/src/cohort/cohortService.spec.ts
  packages/lib/src/cohort/cohortService.ts
  packages/lib/src/dto/referentDto.ts
  packages/lib/src/dto/userDto.ts
  packages/lib/src/mongoSchema/referent.ts
  packages/lib/src/roles.spec.ts
  packages/lib/src/roles.ts
Labels: R&R

#4290 feat(api,admin,app): 3229 - POC Régionalisation de l’éligibilité front
  admin/src/components/ui/buttons/ButtonPrimary.tsx
  admin/src/components/ui/forms/dateForm/DatePickerInput.tsx
  admin/src/scenes/settings/components/CleSettings.tsx
  admin/src/scenes/settings/components/InformationsConvoyage.tsx
  admin/src/scenes/settings/index.jsx
  admin/src/scenes/settings/index.tsx
  admin/src/scenes/settings/tabs/EligibilityTab.tsx
  admin/src/scenes/settings/tabs/GeneralTab.tsx
  admin/src/scenes/settings/utils.js
  api/src/__tests__/cohort.test.ts
  api/src/auth.js
  api/src/cohort/cohortController.ts
  packages/ds/src/admin/index.ts
  packages/ds/src/admin/layout/NavbarControlled.tsx
  packages/lib/src/dto/cohortDto.ts
Labels: WIP, R&R
