Repository betagouv/service-national-universel, pull requests merged in 2024-06, with the labels that each got.

#3954 fix(github): Fix check_docker_image_tag action
  .github/actions/check_docker_image_tag/action.yml
Labels: bypass title

#3953 fix(terraform): Remove incorrect checks
  .github/workflows/deploy-production-hotfix.yml
  .github/workflows/deploy-production.yml
Labels: bypass title

#3955 fix(github): Sleep before healthchecks
  .github/workflows/deploy-ci.yml
  .github/workflows/deploy-custom-env.yml
  .github/workflows/deploy-production-hotfix.yml
  .github/workflows/deploy-production.yml
Labels: bypass title

#3958 fix(api): sentry - Capture errors for sync
  api/src/crons/syncReferentSupport.js
Labels: Pull request title validation

#3934 feat(admin,api): 1740 - permettre aux modérateurs de supprimer une classe
  admin/src/redux/cohorts/reducer.ts
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
  admin/src/scenes/classe/components/DeleteButton.tsx
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/ReferentInfos.tsx
  admin/src/scenes/classe/components/SejourInfos.tsx
  admin/src/scenes/classe/components/StatsInfos.tsx
  admin/src/scenes/classe/components/modale/ModaleInvite.tsx
  admin/src/scenes/classe/components/modale/ModaleWithdraw.tsx
  admin/src/scenes/classe/components/modale/modaleCohort.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/classe/utils/index.js
  admin/src/scenes/classe/view.jsx
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/plan-transport/schema-repartition/components/DetailTable.tsx
  admin/src/types.ts
  api/src/__tests__/classe.test.js
  api/src/__tests__/helpers/app.js
  api/src/__tests__/helpers/classe.js
  api/src/classe/classe.service.test.ts
  api/src/classe/classe.service.ts
  api/src/controllers/cle/classe.js
  packages/ds/src/admin/form/InputText.tsx
  packages/ds/src/admin/layout/Header.tsx
  packages/ds/src/admin/ui/Button.tsx
  packages/ds/src/admin/ui/DropdownButton.tsx
  packages/lib/src/dto/classeDto.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#3949 fix(api): sentry - download convoc without lineId
  api/src/templates/convocation/cohesion.js
Labels: bypass title, RUN

#3963 feat(admin,api): 1740 - permettre aux admins de supprimer une classe
  admin/src/redux/cohorts/reducer.ts
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
  admin/src/scenes/classe/components/DeleteButton.tsx
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/ReferentInfos.tsx
  admin/src/scenes/classe/components/SejourInfos.tsx
  admin/src/scenes/classe/components/StatsInfos.tsx
  admin/src/scenes/classe/components/modale/ModaleInvite.tsx
  admin/src/scenes/classe/components/modale/ModaleWithdraw.tsx
  admin/src/scenes/classe/components/modale/modaleCohort.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/classe/utils/index.js
  admin/src/scenes/classe/view.jsx
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/plan-transport/schema-repartition/components/DetailTable.tsx
  admin/src/types.ts
  api/src/__tests__/application.test.js
  api/src/__tests__/classe.test.js
  api/src/__tests__/helpers/app.js
  api/src/__tests__/helpers/classe.js
  api/src/classe/classe.service.test.ts
  api/src/classe/classe.service.ts
  api/src/controllers/cle/classe.js
  packages/ds/src/admin/form/InputText.tsx
  packages/ds/src/admin/layout/Header.tsx
  packages/ds/src/admin/ui/Button.tsx
  packages/ds/src/admin/ui/DropdownButton.tsx
  packages/lib/src/dto/classeDto.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#3964 feat(admin): 2440 - Rendre la modale de CNI dépassé moins violente
  admin/src/scenes/phase0/components/CniField.jsx
  admin/src/scenes/phase0/components/ConfirmModalContent.jsx
Labels: ADMIN

#3975 fix(admin): modal affectation - two bus line with the same meetingPoint
  admin/src/scenes/volontaires/components/ModalAffectation.jsx
Labels: Pull request title validation, bypass title

#3977 chore(admin): 786 - Changement de wording pour la 2FA sur le singin
  admin/src/scenes/auth/signin2FA.jsx
Labels: ADMIN

#3974 fix(api): 2396 - faire fonctionner le crons parentConsentementReminder pour toutes les cohorts
  api/src/crons/parentConsentementReminder.js
Labels: ADMIN

#3962 feat(admin,api): 2244 - supprimer les infos d'affectation de la classe et es eleves lors du changement de cohort de la classe
  admin/src/scenes/classe/components/ButtonInvite.tsx
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/modale/ModaleInvite.tsx
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/classe.test.js
  api/src/__tests__/fixtures/classe.js
  api/src/__tests__/helpers/classe.js
  api/src/classe/classe.service.test.ts
  api/src/classe/classe.service.ts
  api/src/controllers/cle/classe.js
Labels: ADMIN

#3979 feat(terraform): Create GetSecret policy
  terraform/environments/ci/main.tf
  terraform/environments/production/main.tf
Labels: bypass title

#3982 feat(admin,api): 2732 - [HTS] - Juillet 2024 - Schéma de répartition - impossible de créer un groupe
  admin/src/scenes/plan-transport/schema-repartition/SchemaDepartmentDetail.jsx
  admin/src/scenes/plan-transport/schema-repartition/SchemaEditor.jsx
  admin/src/scenes/plan-transport/schema-repartition/SchemaRepartition.jsx
Labels: ADMIN

#3956 feat(admin,api): 2382 - identification lignes fusionnees pdt
  admin/src/scenes/plan-transport/ligne-bus/View/LigneDeBusMapper.ts
  admin/src/scenes/plan-transport/ligne-bus/View/View.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/BusTeam.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Info.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/partials/AddMergedBusModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/partials/DeleteMergedBusButton.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/partials/MergedBus.tsx
  api/src/__tests__/helpers/app.js
  api/src/controllers/planDeTransport/import.js
  api/src/main.js
  api/src/models/PlanDeTransport/ligneBus.type.ts
  api/src/planDeTransport/import/pdtImportService.ts
  api/src/planDeTransport/import/pdtImportUtils.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusMapper.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusValidator.ts
  api/src/planDeTransport/ligneDeBus/ligneFusionneeController.test.ts
  api/src/planDeTransport/ligneDeBus/ligneFusionneeController.ts
  api/src/planDeTransport/planDeTransportController.test.ts
  api/src/planDeTransport/planDeTransportController.ts
  packages/lib/src/dto/busDto.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/dto/ligneDeBus.ts
  packages/lib/src/plandetransport/ligneService.spec.ts
  packages/lib/src/plandetransport/ligneService.ts
Labels: ADMIN

#3987 fix(api/admin): buses duplication
  api/src/controllers/planDeTransport/import.js
  api/src/pdt/import/pdtImportService.ts
  packages/lib/src/constants/plan-de-transport.js
Labels: Pull request title validation, bypass title

#3930 feat(admin,api): 2513 - param dynamique cle affectation transport
  admin/src/scenes/classe/utils/index.js
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view.jsx
  admin/src/scenes/settings/CleSettings.tsx
  admin/src/scenes/settings/index.jsx
  api/src/cohort/cohortValidator.ts
  api/src/models/cohort.js
  packages/lib/index.js
  packages/lib/src/cohort/cohortService.spec.ts
  packages/lib/src/cohort/cohortService.ts
  packages/lib/src/cohort/index.ts
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/dto/referentDto.ts
  packages/lib/src/utils/date.js
  packages/lib/src/utils/date.spec.js
  packages/lib/tsconfig.json
Labels: ADMIN

#3993 feat(api): add ENABLE_ANTIVIRUS configuration
  api/config/default.js
  api/config/development.js
  api/src/utils/virusScanner.js
Labels: bypass title

#3994 feat(api): 2598 - brancher et exporter ds et annuaire etablissement
  api/build.tsconfig.json
  api/config/default.js
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/appelAProjetCle/appelAProjetService.ts
  api/src/cle/appelAProjetCle/appelAProjetType.ts
  api/src/cle/etablissement/etablissementService.ts
  api/src/main.js
  api/src/models/cle/classeType.ts
  api/src/models/cle/etablissementType.ts
  api/src/models/referentType.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeQueryBuilder.test.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeQueryBuilder.ts
  api/src/services/gouv.fr/api-education.js
  api/src/services/gouv.fr/etablissementType.ts
Labels: ADMIN

#3966 feat(admin,api): 2425 - action de suppresion d'une session
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
  admin/src/scenes/centersV2/view/CenterInformations.tsx
  admin/src/scenes/centersV2/view/index.jsx
  api/src/__tests__/fixtures/PlanDeTransport/ligneBus.js
  api/src/__tests__/session-phase1.test.js
  api/src/__tests__/sessionPhase1/getPlanDeTransport.test.ts
  api/src/controllers/session-phase1.js
  api/src/sessionPhase1/sessionPhase1Controller.ts
Labels: ADMIN

#4000 fix(app): no ticket - Prevent spam download of convocation
  app/src/scenes/phase1/scenes/affected/components/modals/ConvocationModal.jsx
  app/src/scenes/phase1/scenes/affected/components/step/stepConvocation.jsx
Labels: bypass title

#4002 refactor(api): cle domain
  admin/src/scenes/classe/list.jsx
  admin/src/services/convocation.service.js
  api/src/classe/classe.controller.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/classe/export/classeExportService.ts
  api/src/cle/etablissement/etablissementController.ts
  api/src/cle/index.ts
  api/src/controllers/cle/index.js
  api/src/routes.ts
Labels: bypass title, ADMIN

#3996 feat(admin,api): 2706 - ajouter les champ et filtre pour "Etat", "Academie" et "Années scolaire" pour les etablissement
  admin/src/scenes/etablissement/List.jsx
  admin/src/scenes/etablissement/view.jsx
  api/src/__tests__/etablissement.test.js
  api/src/__tests__/fixtures/etablissement.js
  api/src/__tests__/helpers/etablissement.ts
  api/src/cle/etablissement/etablissementController.ts
  api/src/controllers/elasticsearch/cle/etablissement.js
  api/src/models/cle/etablissement.js
  api/src/models/cle/etablissementType.ts
  packages/ds/src/common/index.ts
  packages/lib/src/translation.js
Labels: ADMIN

#4012 feat(api): 2781 - mapping DS form
  api/src/cle/appelAProjetCle/appelAProjetType.ts
  api/src/providers/demarcheSimplifiee/appelAProjetDemarcheSimplifieeDto.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.test.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeQueryBuilder.test.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeQueryBuilder.ts
Labels: ADMIN

#4015 feat(api): no_ticket - Ajout d'un service d'export de CSV
  api/package.json
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/appelAProjetCle/appelAProjetService.ts
  api/src/services/fileService.ts
  package-lock.json
Labels: bypass title

#4013 fix(antivirus): 2768 - limit antivirus ram usage & use unix socket
  antivirus/Dockerfile
  antivirus/config.js
  antivirus/docker_start.sh
  api/src/utils/virusScanner.js
Labels: bypass title

#3998 feat(admin,api): 2730 - mettre a jour le modele des classes
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/StatsInfos.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view.jsx
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/classe.test.js
  api/src/__tests__/etablissement.test.js
  api/src/__tests__/fixtures/classe.js
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/etablissement/etablissementController.ts
  api/src/controllers/elasticsearch/cle/classe.js
  api/src/models/cle/classe.js
  api/src/models/cle/classeType.ts
  api/src/models/cle/etablissement.js
  packages/lib/src/constants/constants.js
  packages/lib/src/dto/classeDto.ts
  packages/lib/src/translation.js
Labels: ADMIN

#4023 feat(api) - no ticket : Add csv export
  api/package.json
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/appelAProjetCle/appelAProjetService.ts
  api/src/services/fileService.ts
  package-lock.json
Labels: bypass title, ADMIN

#4009 feat(admin,api): 2677 - affichage des liens dans les bandeaux d’alertes
  admin/package.json
  admin/src/components/forms/Field.jsx
  admin/src/scenes/alerte/AlerteMessageForm.tsx
  admin/src/scenes/alerte/index.tsx
  admin/src/scenes/dashboardV2/components/BandeauInfo.jsx
  admin/src/scenes/dashboardV2/components/BandeauInfo.tsx
  admin/src/scenes/dashboardV2/components/DashboardContainer.jsx
  admin/src/scenes/dashboardV2/components/General.tsx
  admin/src/scenes/dashboardV2/components/ui/InfoMessage.tsx
  api/docker-compose.dev.yml
  api/src/__tests__/alerte-message.test.ts
  api/src/__tests__/fixtures/alerteMessage.js
  api/src/controllers/dashboard/alerte-message.js
  api/src/models/alerteMessage.js
  package-lock.json
  packages/ds/package.json
  packages/lib/src/dto/alerteMessageDto.ts
  packages/lib/src/dto/index.ts
Labels: ADMIN

#4025 refacto(admin): PR de refacto du front des etablissement, passage en TS suite a la PR 3996
  admin/src/scenes/etablissement/components/ButtonAddCoordinator.tsx
  admin/src/scenes/etablissement/components/ButtonModalContact.tsx
  admin/src/scenes/etablissement/components/Contact.tsx
  admin/src/scenes/etablissement/components/GeneralInfos.tsx
  admin/src/scenes/etablissement/components/modale/FirstLoginAdminChef.tsx
  admin/src/scenes/etablissement/components/modale/FirstLoginAdminCoordinator.tsx
  admin/src/scenes/etablissement/components/modale/FirstLoginRefClasse.tsx
  admin/src/scenes/etablissement/components/types.ts
  admin/src/scenes/etablissement/view.jsx
  admin/src/scenes/etablissement/view.tsx
  admin/src/types.ts
  packages/lib/src/dto/etablissementDto.ts
Labels: bypass title, ADMIN

#4030 fix(api): 2859 - upload cni cohort avenir
  api/src/__tests__/young-inscription.test.js
  api/src/__tests__/young.test.ts
  api/src/controllers/young/documents.js
  api/src/controllers/young/inscription2023.js
  packages/lib/index.js
  packages/lib/src/constants/cohort.ts
Labels: ADMIN

#4034 fix(api): 2841 - optimize "/mission/:id/application"
  api/src/controllers/mission.js
  api/src/models/application.js
Labels: ADMIN

#4031 fix(admin/api): fix du modele de classe pour conserver la plateforme jeune
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/fixtures/classe.js
  api/src/auth.js
  api/src/cle/classe/classeController.ts
  api/src/controllers/elasticsearch/cle/classe.js
  api/src/controllers/referent.js
  api/src/models/cle/classe.js
  api/src/models/cle/classeType.ts
  packages/lib/src/constants/constants.js
  packages/lib/src/dto/classeDto.ts
Labels: bypass title, ADMIN

#4024 feat(api): 2599-2600 - create classe, etablissement and referent
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/__tests__/fixtures/cle/appelAProjet.ts
  api/src/__tests__/fixtures/providers/annuaireEtablissement.ts
  api/src/cle/appelAProjetCle/appelAProjetClasseService.ts
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/appelAProjetCle/appelAProjetEtablissementService.ts
  api/src/cle/appelAProjetCle/appelAProjetReferentService.ts
  api/src/cle/appelAProjetCle/appelAProjetService.ts
  api/src/cle/appelAProjetCle/appelAProjetType.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/etablissement/etablissementMapper.ts
  api/src/models/cle/classe.js
  api/src/models/cle/classeType.ts
  api/src/models/referent.js
  api/src/models/referentType.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.test.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.ts
  api/src/services/fileService.ts
  api/src/services/gouv.fr/api-education.ts
  api/src/services/regionService.ts
  packages/lib/index.js
  packages/lib/src/constants/cle/classeConstants.ts
  packages/lib/src/constants/constants.js
  packages/lib/src/constants/referentConstants.ts
  packages/lib/src/dto/classeDto.ts
Labels: ADMIN
