Repository betagouv/service-national-universel, pull requests merged in 2024-05, with the labels that each got.

#3826 fix(admin): 2446 - info message default value and empty filter
  admin/src/components/filters-system-v2/components/filters/FilterPopOver.jsx
  admin/src/scenes/dashboardV2/components/ui/InfoMessage.tsx
  admin/src/scenes/missions/view/details.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/View.jsx
  admin/src/scenes/volontaires/view/phase1.jsx
Labels: ADMIN

#3836 fix(admin): sentry - centers young undefined
  admin/src/scenes/centersV2/youngs/index.jsx
Labels: bypass title

#3823 fix(admin): 2272 - Correction de la scrollbar sur le menu
  admin/globals.d.ts
  admin/src/components/cohorts/SelectCohort.tsx
  admin/src/components/drawer/SideBar.tsx
  admin/src/components/drawer/components/Header.tsx
  admin/src/hooks/useEnvironment.js
  admin/src/hooks/useEnvironment.ts
  admin/src/index.css
  admin/src/redux/auth/actions.ts
  admin/src/redux/auth/reducer.ts
  admin/src/redux/cohorts/actions.ts
  admin/src/redux/cohorts/reducer.ts
  admin/src/redux/reducers.ts
  admin/src/redux/tickets/actions.ts
  admin/src/redux/tickets/reducer.ts
  admin/src/scenes/centersV2/components/ModalRattacherCentre.tsx
  admin/src/scenes/edit-transport/list/index.tsx
  app/globals.d.ts
Labels: ADMIN

#3832 fix(admin): Corrections de l'affichage des données de session
  admin/src/components/ui/forms/dateForm/ToggleDate.jsx
  admin/src/scenes/centersV2/components/sessions/OccupationCard.jsx
  admin/src/scenes/centersV2/components/sessions/SessionList.jsx
Labels: bypass title

#3825 fix(api): sentry - Gestion des MimeType inconnu
  api/src/controllers/SNUpport.js
  api/src/controllers/application.js
  api/src/controllers/planDeTransport/import.js
  api/src/controllers/referent.js
  api/src/controllers/session-phase1.js
  api/src/controllers/young/documents.js
  api/src/controllers/young/index.js
  api/src/utils/file.ts
Labels: bypass title

#3795 feat(admin,api): 2194- Refonte export DSNJ
  admin/src/scenes/dsnj-export/components/DatePicker.jsx
  admin/src/scenes/dsnj-export/components/ExportBox.jsx
  admin/src/scenes/dsnj-export/components/ExportBox.tsx
  admin/src/scenes/dsnj-export/index.jsx
  api/src/controllers/cohort/cohort.controller.js
Labels: ADMIN

#3839 fix(api): bug crons dsnjExport cohesionCenterId undefined
  api/src/crons/dsnjExport/utils.js
Labels: Pull request title validation

#3841 chore(mix): add eslint import extensions rule
  admin/.eslintrc.js
  api/.eslintrc.js
  app/.eslintrc.js
  package-lock.json
  package.json
  packages/lib/.eslintrc.js
Labels: bypass title

#3840 fix(api): sentry 45336 - Fixed meetingHour null case.
  api/src/templates/convocation/cohesion.js
Labels: bypass title

#3829 chore(app/admin): ajout des tests check-types
  .github/workflows/deploy-ci.yml
  .github/workflows/deploy-custom-env.yml
  .github/workflows/deploy-production-hotfix.yml
  .github/workflows/run-tests-api.yml
  .github/workflows/run-tests-front.yml
  admin/.eslintrc.js
  admin/package.json
  admin/src/build-only-on-clevercloud.js
  admin/src/scenes/centersV2/components/ModalRattacherCentre.tsx
  admin/src/scenes/inbox/components/header.jsx
  admin/src/scenes/signup/code.jsx
  admin/src/utils/generate-assets-presentation-page.js
  admin/tsconfig.ci.json
  analytics/src/index.js
  antivirus/index.js
  api/.eslintrc.js
  api/src/controllers/SNUpport.js
  api/src/controllers/mission.js
  api/src/crons/patch/application.js
  api/src/crons/patch/classe.js
  api/src/crons/patch/mission.js
  api/src/crons/patch/missionEquivalence.js
  api/src/crons/patch/refresh-materialized-views.js
  api/src/crons/patch/structure.js
  api/src/crons/patch/young.js
  api/src/index.js
  api/src/mongo.js
  api/src/services/stats.service/engagement.js
  api/src/services/stats.service/inscription.js
  api/src/services/support.js
  app/.eslintrc.js
  app/package.json
  app/src/build-only-on-clevercloud.js
  app/src/scenes/representants-legaux/mobile/consentement.jsx
  app/src/utils/generate-assets-presentation-page.js
  app/tsconfig.ci.json
  front.tsconfig.json
  packages/ds/src/common/forms/AddressForm.tsx
  packages/ds/tsconfig.json
  packages/lib/.eslintrc.js
  pdf/index.js
  send-in-blue/index.js
  send-in-blue/mongo.js
Labels: bypass title

#3842 fix(admin): sentry - Fix PDT bus validation
  admin/src/scenes/plan-transport/ligne-bus/View/components/BusTeam.jsx
Labels: bypass title, ADMIN

#3843 fix(admin): sentry - handle dashboard todo empty
  admin/src/scenes/dashboardV2/components/Todos.jsx
Labels: bypass title, ADMIN

#3835 fix(admin): sentry - head center session undefined
  admin/src/scenes/dashboardV2/head-center/subscenes/sejour/index.jsx
Labels: bypass title

#3846 refactor(admin): Simpler logic in session list
  admin/src/scenes/centersV2/components/PedagoProject.jsx
  admin/src/scenes/centersV2/components/TimeSchedule.jsx
  admin/src/scenes/centersV2/components/modals/ModalPedagoProject.jsx
  admin/src/scenes/centersV2/components/modals/ModalTimeSchedule.jsx
  admin/src/scenes/centersV2/components/sessions/OccupationCard.jsx
  admin/src/scenes/centersV2/components/sessions/SessionList.jsx
  admin/src/scenes/centersV2/view/index.jsx
Labels: bypass title

#3851 Revert "fix(api): bug dsnjexport alerting youngCohort != sessionCohort"
  api/src/crons/dsnjExport/utils.js
Labels: Pull request title validation

#3838 feat(api): 2158 - use common young data to generate convocation
  api/src/classe/classe.service.test.ts
  api/src/classe/classe.service.ts
  api/src/templates/convocation/cohesion.js
  packages/lib/functionalErrors.js
Labels: ADMIN

#3858 fix(admin): sentry - status table undefined
  admin/src/components/cohorts/SelectCohort.tsx
  admin/src/components/drawer/components/Header.tsx
  admin/src/components/filters-system-v2/components/ResultTable.jsx
  admin/src/redux/auth/reducer.ts
  admin/src/scenes/centersV2/components/ModalRattacherCentre.tsx
  admin/src/scenes/centersV2/view/CenterInformations.tsx
  admin/src/scenes/dashboardV2/components/ui/StatusTable.tsx
  admin/src/scenes/dsnj-export/components/ExportBox.tsx
  admin/src/scenes/edit-transport/list/index.tsx
  admin/src/scenes/goal/index.tsx
  admin/src/types.ts
  front.tsconfig.json
Labels: bypass title, ADMIN

#3868 fix(api, admin): Unable manual affectation for CLE
  admin/src/scenes/volontaires/view/phase1.jsx
  api/src/controllers/cle/classe.js
Labels: bypass title

#3867 refactor(github): Drop scw_reset_endpoint GHAction
  .github/workflows/scw-reset-endpoint.yml
Labels: bypass title

#3833 fix(api): 2186 - Récupération centre notif fermeture de sejour
  api/build.tsconfig.json
  api/jest.config.js
  api/package.json
  api/src/__tests__/application.test.js
  api/src/__tests__/bus.test.js
  api/src/__tests__/cohesion-center.test.js
  api/src/__tests__/contract.test.js
  api/src/__tests__/department-service.test.js
  api/src/__tests__/diagoriente.test.ts
  api/src/__tests__/email.test.js
  api/src/__tests__/helpers/db.js
  api/src/__tests__/inscription-goal.test.js
  api/src/__tests__/ligne-de-bus.test.js
  api/src/__tests__/ligne-to-point.test.js
  api/src/__tests__/mission.test.js
  api/src/__tests__/point-de-rassemblement.test.js
  api/src/__tests__/program.test.js
  api/src/__tests__/referent-auth.test.js
  api/src/__tests__/referent.test.js
  api/src/__tests__/session-phase1.test.js
  api/src/__tests__/structure.test.js
  api/src/__tests__/table-de-repartition.test.js
  api/src/__tests__/waiting-list.test.js
  api/src/__tests__/young-auth.test.js
  api/src/__tests__/young-documents.test.js
  api/src/__tests__/young-inscription.test.js
  api/src/__tests__/young-meeting-point.test.js
  api/src/__tests__/young.test.ts
  api/src/controllers/young/phase1.js
  api/src/models/cohesionCenter.type.ts
  api/src/models/departementService.type.ts
  api/src/utils/index.js
Labels: ADMIN

#3860 fix(admin) sentry - academyToDepartments array
  admin/src/scenes/dashboardV2/components/common.js
  packages/lib/src/constants/academy.js
Labels: bypass title, ADMIN

#3859 fix(admin) sentry - export session undefined
  admin/src/scenes/centersV2/youngs/index.jsx
Labels: bypass title, ADMIN

#3857 feat(api, admin): 2227 - Ajout de l'email académique lors de la création de la session
  admin/src/components/ui/forms/dateForm/ToggleDate.jsx
  admin/src/scenes/centersV2/components/ModalRattacherCentre.tsx
  admin/src/scenes/centersV2/components/sessions/OccupationCard.jsx
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
  admin/src/scenes/centersV2/view/CenterInformations.tsx
  admin/src/scenes/centersV2/view/index.jsx
  admin/src/types.ts
  api/src/controllers/cohesion-center.js
  packages/ds/src/common/index.ts
Labels: ADMIN

#3881 fix(admin) sentry - undefined pdr / pointage
  admin/src/scenes/centersV2/components/modals/ModalMultiPointageDepart.jsx
  admin/src/scenes/plan-transport/ligne-bus/List.jsx
Labels: bypass title, ADMIN

#3878 chore(lib,api): add typescript to snu-lib
  api/src/cohort/cohortValidatorTemp.ts
  package-lock.json
  packages/lib/.babelrc.json
  packages/lib/.eslintrc.js
  packages/lib/.gitignore
  packages/lib/jest.config.js
  packages/lib/package.json
  packages/lib/rollup.config.js
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/roles.ts
  packages/lib/tsconfig.json
Labels: bypass title

#3865 feat(admin): 2252 - maj design cohorte revoir les filtres
  admin/.eslintrc.js
  admin/src/components/filters-system-v2/components/Filter.ts
  admin/src/components/filters-system-v2/components/Filters.jsx
  admin/src/components/filters-system-v2/components/filters/FilterPopOver.tsx
  admin/src/components/filters-system-v2/components/filters/IntermediateFilter.tsx
  admin/src/scenes/centersV2/list.jsx
  admin/src/scenes/classe/list.jsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/pointDeRassemblement/List.jsx
  admin/src/scenes/utilisateur/list.jsx
  admin/src/scenes/volontaires/list.jsx
  admin/src/services/cohort.service.jsx
  admin/src/services/cohort.service.ts
Labels: ADMIN

#3871 feat(app): 2226, 2229, 2534 - Ecran affecté/étape 4 : ajout email académique
  app/src/components/ui/buttons/ButtonLinkLight.jsx
  app/src/components/ui/modals/Modal.jsx
  app/src/scenes/phase1/components/EnumeratedList.jsx
  app/src/scenes/phase1/components/MedicalFileModal.jsx
  app/src/scenes/phase1/scenes/affected/components/StepsAffected.jsx
  app/src/scenes/phase1/scenes/affected/components/step/stepMedicalFile.jsx
Labels: bypass title

#3890 chore(api): fix CPU is 200% by not fetching the whole young item from ES
  api/src/services/stats.service/engagement.js
Labels: bypass title, ADMIN

#3896 fix(admin): 2286 - export classes mongo
  admin/src/scenes/classe/list.jsx
  api/src/classe/classe.controller.ts
  api/src/classe/export/classeExportService.ts
  api/src/models/index.ts
Labels: RUN

#3876 feat(admin,api): 2177 - parametrage dynamique hts infos convoyage
  admin/src/scenes/plan-transport/ligne-bus/View/components/BusTeam.jsx
  admin/src/scenes/settings/InformationsConvoyage.tsx
  admin/src/scenes/settings/index.jsx
  api/src/cohort/cohortController.ts
  api/src/cohort/cohortService.ts
  api/src/cohort/cohortValidator.ts
  api/src/cohort/cohortValidatorTemp.ts
  api/src/controllers/cohort-session.js
  api/src/controllers/planDeTransport/ligne-de-bus.js
  api/src/index.js
  api/src/models/cohort.js
  packages/lib/index.js
  packages/lib/jest.config.js
  packages/lib/src/plandetransport/index.ts
  packages/lib/src/plandetransport/ligneService.spec.ts
  packages/lib/src/plandetransport/ligneService.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#3848 feat(admin,api): 2381 - [PDT] identification des lignes fusionnees
  admin/src/components/cohorts/SelectCohort.tsx
  admin/src/redux/cohorts/reducer.ts
  admin/src/scenes/plan-transport/components/Buttons.jsx
  admin/src/scenes/plan-transport/ligne-bus/List.jsx
  admin/src/scenes/plan-transport/ligne-bus/import/components/Download.tsx
  admin/src/scenes/plan-transport/ligne-bus/import/components/Import.tsx
  admin/src/scenes/plan-transport/ligne-bus/import/components/NavBar.tsx
  admin/src/scenes/plan-transport/ligne-bus/import/components/Resum.tsx
  admin/src/scenes/plan-transport/ligne-bus/import/index.tsx
  admin/src/scenes/plan-transport/ligne-bus/import/type.ts
  api/src/controllers/planDeTransport/import.js
  api/src/models/PlanDeTransport/ligneBus.js
  api/src/models/index.ts
  api/src/pdt/import/pdtImportService.ts
  api/src/pdt/import/pdtImportUtils.ts
  packages/lib/src/constants/plan-de-transport.js
Labels: ADMIN

#3901 chore(admin): sentry - cannot read properties of undefined(reading 'm…
  admin/src/scenes/classe/view.jsx
Labels: ADMIN

#3904 fix(admin): 2286 - export classes mongo v2
  admin/src/scenes/classe/list.jsx
  api/src/classe/classe.controller.ts
  api/src/classe/export/classeExportService.ts
  api/src/models/index.ts
Labels: RUN

#3895 fix(admin): 2247 - attestation sur l'honneur disparue
  admin/src/scenes/phase0/components/sections/identite/SectionIdentiteCni.jsx
  admin/src/scenes/phase0/utils/index.js
Labels: ADMIN

#3888 chore(admin): 2550 - Dette Design Export DSNJ
  admin/src/scenes/dsnj-export/components/DatePicker.jsx
  admin/src/scenes/dsnj-export/components/ExportBox.tsx
Labels: ADMIN

#3885 feat(admin): 2221 - mis a jour des infos scolaire du jeune lors du changement HTS -> CLE
  admin/src/scenes/phase0/components/sections/SectionParents.jsx
  api/src/controllers/referent.js
Labels: ADMIN

#3915 fix(admin): Autoriser les centres sans capacité renseignée
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
  admin/src/scenes/centersV2/view/CenterInformations.tsx
  admin/src/types.ts
Labels: bypass title

#3912 chore(admin): sentry - cannot read properties of undefined
  admin/src/components/filters-system-v2/components/filters/IntermediateFilter.tsx
Labels: ADMIN

#3917 fix(api): 2286 - add young classeId index
  api/src/models/young.js
Labels: RUN

#3927 fix(api): CLE convocation v2
  api/src/templates/convocation/cohesion.js
Labels: Pull request title validation, bypass title

#3924 fix(admin): settings invalid body
  api/src/cohort/cohortValidator.ts
  packages/lib/src/dto/cohortDto.ts
Labels: bypass title, ADMIN

#3877 chore(lib): update dependency next / xlsx
  admin/package.json
  api/package.json
  knowledge-base-public/package.json
  package-lock.json
  package.json
Labels: dependencies

#3928 Revert "fix(admin): Reopen boite reception temporairement"
  admin/src/app.jsx
  admin/src/components/drawer/components/SNUpportBox.jsx
  admin/src/scenes/inbox/components/ticketInfos.jsx
  admin/src/scenes/inbox/components/ticketMessage.jsx
  admin/src/scenes/inbox/components/ticketTabs.jsx
  admin/src/scenes/inbox/index.jsx
Labels: Pull request title validation

#3921 fix(api): Error Sentry Export DSNJ
  api/src/cohort/cohortController.ts
Labels: Pull request title validation

#3935 fix(admin): 2622 - correction onglet sejour chef de centre
  admin/src/scenes/dashboardV2/head-center/subscenes/sejour/index.jsx
Labels: RUN

#3938 fix(admin): sentry - Automatic refresh after restore signin
  admin/src/components/RestorePreviousSignin/index.jsx
Labels: Pull request title validation

#3941 feat(admin): Ajouter le modele lors de l'ajout de ligne sur le pdt
  admin/src/scenes/plan-transport/ligne-bus/import/components/Download.tsx
Labels: Pull request title validation, bypass title, ADMIN

#3882 fix(admin): sentry - Redirect to not found if id not good for establishment
  admin/src/scenes/classe/index.jsx
  admin/src/scenes/etablissement/index.jsx
Labels: bypass title

#3946 fix(api): Impossible to change cohort if one of youngs has finished
  api/src/controllers/cle/classe.js
Labels: Pull request title validation

#3950 fix(admin): open manual affectation for CLE
  admin/src/scenes/volontaires/view/phase1.jsx
Labels: Pull request title validation, bypass title

#3951 fix(api): notickets - fix access to secrets managers
  api/config/staging.js
Labels: bypass title
