Repository betagouv/service-national-universel, pull requests merged in 2024-12, with the labels that each got.

#4583 fix(api): bug crons certificats
  api/src/crons/monitorCertificats.js
Labels: Pull request title validation

#4592 fest(api): 3740 - rattrapage des classes et des jeunes désistés par erreur
  api/migrations/20241203141830-Rattrapage_classe_desistees.js
Labels: Pull request title validation

#4033 refactor(app): 2633 - Refacto HomePage App
  app/src/Espace.jsx
  app/src/scenes/home/AvenirCohort.jsx
  app/src/scenes/home/Excluded.jsx
  app/src/scenes/home/InscriptionClosedCLE.jsx
  app/src/scenes/home/Phase1NotDone.jsx
  app/src/scenes/home/WaitingReinscription.jsx
  app/src/scenes/home/index.jsx
  app/src/scenes/home/index.tsx
  app/src/scenes/home/waitingAffectation.jsx
  app/src/scenes/home/waitingCorrection.jsx
  app/src/scenes/inscription2023/InscriptionClosed.jsx
  app/src/scenes/phase2/index.jsx
  app/src/scenes/reinscription/index.jsx
  app/src/services/reinscription.service.js
  app/src/utils/index.js
Labels: WAITING FOR QA, VOLONTAIRES

#4586 chore(apiv2): add health check
  apiv2/src/App.module.ts
  apiv2/src/infra/HealthCheck.controller.ts
  apiv2/src/main.ts
Labels: bypass title

#4588 chore(github): update pr title checker
  .github/pr-title-checker-config.json
Labels: bypass title

#4581 refactor(api): Mieux distinguer les logiques d'éligibilité entre inscription/réinscription/changement de séjour
  api/src/__tests__/cohort-group.test.ts
  api/src/__tests__/cohort-session.test.ts
  api/src/__tests__/helpers/db.ts
  api/src/cohort/cohortQueryBuilder.ts
  api/src/cohort/cohortService.ts
  api/src/cohortGroup/cohortGroupController.ts
  api/src/controllers/cohort-session.ts
  api/src/controllers/young/account.ts
  api/src/controllers/young/index.ts
  api/src/controllers/young/inscription2023.js
  api/src/controllers/young/reinscription.js
  api/src/preinscription/preinscriptionController.ts
  app/src/scenes/changeSejour/lib/useChangeSejour.ts
  app/src/scenes/changeSejour/lib/useCohortGroups.ts
  app/src/scenes/changeSejour/lib/useSejours.ts
  app/src/scenes/changeSejour/scenes/ChangeSejourMenu.tsx
  app/src/scenes/home/index.tsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/reinscription/index.jsx
  app/src/services/cohort.service.ts
  app/src/services/reinscription.service.js
  app/src/services/reinscription.service.ts
  app/src/services/young.service.ts
  packages/lib/src/routes/cohortGroup/index.ts
  packages/lib/src/sessions.ts
Labels: bypass title, VOLONTAIRES

#4556 fix(api): 3692 - fix acceptRI
  api/src/controllers/representants-legaux.js
  api/src/controllers/young/index.ts
  api/src/crons/parentRevalidateRI.js
Labels: VOLONTAIRES

#4590 feat(admin,api): 3682 - import referentiel routes (SDR)
  admin/src/scenes/plan-transport/ligne-bus/ImportSDRButton.tsx
  admin/src/scenes/plan-transport/ligne-bus/List.jsx
  admin/src/scenes/settings/operations/actions/AffectationSimulationMetropole/AffectationSimulationMetropole.tsx
  admin/src/scenes/settings/operations/actions/AffectationSimulationMetropole/AffectationSimulationMetropoleModal.tsx
  admin/src/services/ReferentielService.ts
  admin/src/services/apiv2.ts
  admin/src/services/file.service.ts
  admin/src/utils/buildRequest.ts
  api/src/controllers/planDeTransport/schema-de-repartition.ts
  apiv2/package.json
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/AdminJob.module.ts
  apiv2/src/admin/core/referentiel/routes/ReferentielImportTask.model.ts
  apiv2/src/admin/core/referentiel/routes/ReferentielRoutes.service.spec.ts
  apiv2/src/admin/core/referentiel/routes/ReferentielRoutes.service.ts
  apiv2/src/admin/core/referentiel/routes/useCase/ImporterRoutes.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.ts
  apiv2/src/admin/infra/referentiel/api/ImportReferentiel.controller.ts
  apiv2/src/admin/infra/referentiel/initProvider/useCase.ts
  apiv2/src/admin/infra/task/AdminTask.consumer.ts
  apiv2/src/shared/core/File.gateway.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/src/shared/infra/AllExceptions.filter.ts
  apiv2/src/shared/infra/File.provider.ts
  apiv2/src/task/core/Task.gateway.ts
  apiv2/src/task/infra/TaskMongo.repository.ts
  apiv2/test/admin/setUpAdminTest.ts
  apiv2/test/architecture/Architecture.spec.ts
  package-lock.json
  packages/ds/src/admin/form/InputFile.tsx
  packages/ds/src/admin/index.ts
  packages/lib/src/constants/constants.ts
  packages/lib/src/constants/referentiel.ts
  packages/lib/src/constants/task.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/dto/referentiel/ReferentielTaskDto.ts
  packages/lib/src/index.ts
  packages/lib/src/routes/index.ts
  packages/lib/src/routes/referentiel/getImportsReferentiel.ts
  packages/lib/src/routes/referentiel/index.ts
  packages/lib/src/routes/referentiel/postImportReferentiel.ts
  packages/lib/src/translation.ts
Labels: R&R

#4605 fix(api): 3692 - fixAcceptRI
  api/migrations/20241211102407-add-parent1ValidationDate.js
Labels: VOLONTAIRES

#4596 feat(app): 3600 - New Withdraw Access
  app/src/scenes/account/components/ActionButton.jsx
  app/src/scenes/account/components/ConfirmationModalContent.jsx
  app/src/scenes/account/components/WithdrawFormModalContent.jsx
  app/src/scenes/account/components/WithdrawOrChangeDateModalContent.jsx
  app/src/scenes/account/components/WithdrawalModal.jsx
  app/src/scenes/account/scenes/withdrawn/components/Withdrawal.jsx
  app/src/scenes/account/utils.js
  app/src/scenes/changeSejour/scenes/ChangeSejourMenu.tsx
  app/src/scenes/changeSejour/scenes/WithdrawSejour.tsx
  app/src/scenes/phase1/scenes/affected/components/StepsAffected.jsx
  app/src/scenes/phase1/waitingAffectation.jsx
Labels: VOLONTAIRES

#4585 fix(api): 3691 - Eviter les doublons lors de la synchro des missions JVA
  api/src/crons/JeVeuxAiderDaily.js
  api/src/crons/index.js
  api/src/crons/missionsJVA/JVARepository.ts
  api/src/crons/missionsJVA/JVAService.ts
  api/src/crons/missionsJVA/JVAUtils.ts
  api/src/crons/missionsJVA/JeVeuxAiderDaily.ts
Labels: VOLONTAIRES

#4612 fix(api): random failing test
  api/src/__tests__/young-documents.test.ts
Labels: bypass title

#4616 chore(github): allow pr without number
  .github/pr-title-checker-config.json
Labels: bypass title

#4604 feat(app): 3607 - Home unique pour les volontaires hors parcours
  api/src/__tests__/cohort-group.test.ts
  api/src/cohort/cohortQueryBuilder.ts
  api/src/cohort/cohortService.ts
  api/src/cohortGroup/cohortGroupController.ts
  api/src/cohortGroup/cohortGroupService.ts
  api/src/controllers/young/index.ts
  api/src/controllers/young/reinscription.js
  app/src/assets/hero/home-not-done.png
  app/src/components/layout/HomeContainer.tsx
  app/src/components/layout/HomeHeader.tsx
  app/src/components/modals/ResponsiveModal.tsx
  app/src/components/ui/alerts/ErrorNotice.tsx
  app/src/components/ui/alerts/Notice.jsx
  app/src/components/ui/alerts/Notice.tsx
  app/src/hooks/usePermissions.ts
  app/src/index.css
  app/src/scenes/all-engagements/index.jsx
  app/src/scenes/changeSejour/components/CurrentSejourNotice.tsx
  app/src/scenes/changeSejour/components/NoSejourSection.tsx
  app/src/scenes/changeSejour/scenes/ChangeSejourMenu.tsx
  app/src/scenes/changeSejour/scenes/NewChoiceSejour.tsx
  app/src/scenes/home/HomePhase1.tsx
  app/src/scenes/home/Phase1NotDone.jsx
  app/src/scenes/home/Phase1NotDone.tsx
  app/src/scenes/home/components/Engagement.jsx
  app/src/scenes/home/components/Engagement.tsx
  app/src/scenes/home/index.tsx
  app/src/scenes/phase2/engagement.repository.ts
  app/src/scenes/phase2/scenes/Home/components/Programs.jsx
  app/src/scenes/phase2/scenes/usePrograms.ts
  app/src/scenes/preinscription/components/EngagementPrograms.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepSejour.jsx
  app/src/scenes/reinscription/index.tsx
  app/src/utils/index.js
  packages/lib/src/common.ts
  packages/lib/src/region-and-departments.ts
  packages/lib/src/sessions.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4619 fix(api): Fix d'un test qui ne passait plus pour la release
  api/src/__tests__/young.test.ts
Labels: bypass title

#4620 fix(api): Fix de la migration de rattrappage des jeunes supprimés
  api/migrations/20241211105617-rattrappage_young_deleted.js
Labels: bypass title

#4621 fix(api): 3794 - Fix reinscription eligibility
  api/src/cohort/cohortService.ts
  api/src/cohortGroup/cohortGroupController.ts
  api/src/cohortGroup/cohortGroupService.ts
  api/src/controllers/cohort-session.ts
Labels: VOLONTAIRES

#4613 feat(app): 3601 - Evolution des homes "En attente" et "Liste complémentaire"
  app/src/assets/hero/home.png
  app/src/components/layout/HomeHeader.tsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/home/EnAttente.tsx
  app/src/scenes/home/HomePhase1.tsx
  app/src/scenes/home/Phase1NotDone.tsx
  app/src/scenes/home/components/CorrectionRequests.tsx
  app/src/scenes/home/components/SejourNotice.tsx
  app/src/scenes/home/components/StatusNotice.tsx
  app/src/scenes/home/waitingCorrection.jsx
  app/src/scenes/home/waitingList.jsx
  app/src/scenes/home/waitingValidation.jsx
  app/src/services/useAuth.js
  packages/lib/src/mongoSchema/young.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4614 feat(app): 3604 - Donner accès au changement de séjour depuis la page "Inscriptions clôturées"
  app/src/Espace.jsx
  app/src/components/layout/navbar/components/NavigationMenu.jsx
  app/src/components/layout/navbar/components/UserCard.jsx
  app/src/components/layout/navbar/components/UserMenu.jsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/home/components/SejourNotice.tsx
  app/src/scenes/inscription2023/InscriptionClosed.jsx
  app/src/utils/navigation.js
  packages/lib/src/sessions.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4622 chore(api): apiv2 transactions
  apiv2/package.json
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/AdminJob.module.ts
  apiv2/src/admin/core/sejours/phase1/affectation/ValiderAffectationHTS.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/ValiderAffectationHTS.ts
  apiv2/src/admin/infra/iam/repository/mongo/ReferentMongo.repository.ts
  apiv2/src/admin/infra/sejours/cle/classe/repository/mongo/ClasseMongo.repository.ts
  apiv2/src/admin/infra/sejours/jeune/repository/mongo/JeuneMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/centre/repository/mongo/CentreMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/mongo/LigneDeBusMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/planDeTransport/repository/mongo/PlanDeTransportMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/pointDeRassemblement/repository/mongo/PointDeRassemblementMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/sejour/repository/mongo/SejourMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/session/repository/mongo/SessionMongo.repository.ts
  apiv2/src/infra/Database.provider.ts
  apiv2/src/infra/TransactionalAdatpterMongoose.ts
  apiv2/src/shared/Shared.module.ts
  apiv2/src/shared/core/DbSession.gateway.ts
  apiv2/src/shared/infra/MongoDbSession.ts
  apiv2/test/admin/setUpAdminTest.ts
  apiv2/test/architecture/Architecture.spec.ts
  apiv2/test/architecture/MatchingPattern.ts
  package-lock.json
Labels: FIABILISATION

#4472 feat(api): 3556 - MAJ de l'import de PDR (uniquement par matricule)
  api/src/__tests__/fixtures/PlanDeTransport/pointDeRassemblement.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImport.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportMapper.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportService.ts
  packages/lib/src/mongoSchema/planDeTransport/pointDeRassemblement.ts
Labels: R&R

#4610 feat(apiv2): add patches to apiv2
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/core/history/History.gateway.ts
  apiv2/src/admin/core/history/History.ts
  apiv2/src/admin/infra/history/api/History.controller.ts
  apiv2/src/admin/infra/history/historyProvider.ts
  apiv2/src/admin/infra/history/repository/mongo/HistoryMongo.provider.ts
  apiv2/src/admin/infra/history/repository/mongo/HistoryMongo.repository.ts
  packages/lib/src/mongoSchema/index.ts
  packages/lib/src/mongoSchema/patch.ts
Labels: bypass title

#4626 fix(api, admin): 3796 - Corriger les imports de mission JVA
  admin/src/scenes/missions/view/details.jsx
  api/src/crons/__tester__.ts
  api/src/crons/missionsJVA/JVAService.ts
Labels: VOLONTAIRES
