Repository betagouv/service-national-universel, pull requests merged in 2024-08, with the labels that each got.

#4108 fix(admin): cle appelAProjet - add checks for consistency
  api/src/__tests__/cle/appelAProjet.test.ts
  api/src/cle/appelAProjetCle/appelAProjetReferentService.ts
  api/src/cle/appelAProjetCle/appelAProjetService.ts
  api/src/cle/classe/classeController.ts
  api/src/services/cle/referent.ts
Labels: bypass title, ADMIN

#4133 feat(admin): 2866 - design des nouvelles liste eleves pour les admin CLE
  admin/src/components/filters-system-v2/components/Filters.jsx
  admin/src/components/filters-system-v2/components/ResultTable.jsx
  admin/src/components/filters-system-v2/components/Save.jsx
  admin/src/components/filters-system-v2/components/SelectedFilters.jsx
  admin/src/components/filters-system-v2/components/SortOption.tsx
  admin/src/components/filters-system-v2/components/export/ExportComponent.jsx
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/StatsInfos.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/edit-transport/list/index.tsx
  admin/src/scenes/volontaire-cle/List.tsx
  admin/src/scenes/volontaire-cle/components/NavbarList.tsx
  admin/src/scenes/volontaire-cle/components/YoungListHeader.tsx
  admin/src/scenes/volontaire-cle/components/YoungRowGeneral.tsx
  admin/src/scenes/volontaire-cle/consent/ButtonActionGroupConsent.tsx
  admin/src/scenes/volontaire-cle/consent/YoungListHeaderConsent.tsx
  admin/src/scenes/volontaire-cle/consent/YoungRowConsent.tsx
  admin/src/scenes/volontaire-cle/imageRight/ButtonActionGroupImageRight.tsx
  admin/src/scenes/volontaire-cle/imageRight/YoungListHeaderImageRight.tsx
  admin/src/scenes/volontaire-cle/imageRight/YoungRowImageRight.tsx
  admin/src/scenes/volontaire-cle/index.jsx
  admin/src/scenes/volontaire-cle/list.jsx
  admin/src/scenes/volontaire-cle/utils/list.ts
  admin/src/scenes/volontaire-cle/validation/ButtonActionGroupValidation.tsx
  admin/src/scenes/volontaire-cle/validation/YoungListHeaderValidation.tsx
  admin/src/scenes/volontaire-cle/validation/YoungRowValidation.tsx
  admin/src/types.ts
  api/src/controllers/elasticsearch/cle/young.js
  api/src/referent/referentController.ts
  packages/ds/src/admin/layout/Navbar.tsx
  packages/ds/src/admin/ui/Button.tsx
  packages/ds/src/admin/ui/DropdownButton.tsx
Labels: ADMIN

#4147 feat(admin,api): 2921 - [cle] Modificaton création d'une classe
  .vscode/tasks.json
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/create.jsx
  admin/src/scenes/classe/create.tsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/etablissement/view.tsx
  admin/src/types.ts
  api/migrations/20240731094314-cle-cohort-ff.js
  api/src/__tests__/cle/classe.test.ts
  api/src/__tests__/cle/etablissement.test.ts
  api/src/auth.js
  api/src/cle/appelAProjetCle/appelAProjetController.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/etablissement/etablissementController.ts
  api/src/cle/referent/referentController.ts
  api/src/controllers/elasticsearch/cle/classe.js
  api/src/controllers/elasticsearch/cle/etablissement.js
  api/src/emails/cle/classe.ts
  api/src/emails/index.js
  api/src/featureFlag/featureFlagService.test.ts
  api/src/featureFlag/featureFlagService.ts
  api/src/models/featureFlag.ts
  api/src/services/cle/referent.ts
  packages/ds/src/admin/form/Label.tsx
  packages/lib/index.js
  packages/lib/src/constants/email.ts
  packages/lib/src/constants/featureFlags.ts
  packages/lib/src/index.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4168 fix(admin, api): noticket - fix force consent for young CLE
  admin/src/scenes/volontaire-cle/List.tsx
  admin/src/scenes/volontaire-cle/utils/list.ts
  api/src/controllers/elasticsearch/cle/young.js
Labels: bypass title

#4154 chore(api): mail transport smtp (mailcatcher)
  api/config/ci.js
  api/config/custom.js
  api/config/default.js
  api/config/local-development.example.js
  api/config/production.js
  api/config/staging.js
  api/src/brevo.ts
  api/src/mailcatcher.ts
  mailcatcher/Dockerfile
  mailcatcher/docker_nginx.conf
  mailcatcher/docker_start.sh
Labels: WIP, DANGER NE PAS MERGE

#4169 Fix/remove 2fa on test
  api/config/custom-environment-variables.js
  api/config/default.js
  api/config/production.js
  api/src/auth.js
Labels: bypass title

#4156 feat(crons): 2803 - mongo connection monitoring
  api/src/crons/index.js
  api/src/crons/mongoMonitoring.js
Labels: Pull request title validation

#4175 feat(api, app): no tickets - close Inscription for Region Occitanie
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
Labels: bypass title

#4171 feat(api): 3049 - migrate - add cohorts and add cohortId to collections
  api/migrations/20240806105049-create-non-existing-cohort.js
  api/migrations/20240806125049-add-cohortId-into-collections.js
  api/package.json
  api/src/__tests__/fixtures/application.ts
  api/src/__tests__/fixtures/bus.ts
  api/src/__tests__/fixtures/classe.ts
  api/src/__tests__/fixtures/inscriptionGoal.ts
  api/src/__tests__/fixtures/meetingPoint.ts
  api/src/__tests__/fixtures/sessionPhase1.ts
  api/src/__tests__/fixtures/young.ts
  api/src/models/PlanDeTransport/importPlanTransport.ts
  api/src/models/PlanDeTransport/ligneBus.ts
  api/src/models/PlanDeTransport/modificationBus.ts
  api/src/models/PlanDeTransport/planTransport.ts
  api/src/models/PlanDeTransport/pointDeRassemblement.ts
  api/src/models/PlanDeTransport/schemaDeRepartition.ts
  api/src/models/PlanDeTransport/tableDeRepartition.ts
  api/src/models/application.ts
  api/src/models/bus.ts
  api/src/models/cle/classe.ts
  api/src/models/departmentService.ts
  api/src/models/inscriptionGoal.ts
  api/src/models/legacy/stats-young-center.js
  api/src/models/meetingPoint.ts
  api/src/models/sessionPhase1.ts
  api/src/models/young.ts
Labels: ADMIN

#4177 update rsyslog index
  api/docker_rsyslog.conf
Labels: bypass title

#4183 fix(api): revert ES datastream
  api/docker_rsyslog.conf
Labels: bypass title

#4179 feat(api): 3110 - replace cohort findByName by findById
  api/src/__tests__/cohort.test.ts
  api/src/__tests__/referent.test.ts
  api/src/__tests__/session-phase1.test.ts
  api/src/auth.js
  api/src/cle/classe/classeController.ts
  api/src/cohort/cohortController.ts
  api/src/controllers/cohesion-center.js
  api/src/controllers/planDeTransport/point-de-rassemblement.js
  api/src/controllers/session-phase1.js
  api/src/crons/dsnjExport/utils.js
  api/src/referent/referentController.ts
  api/src/sessionPhase1/sessionPhase1Controller.ts
Labels: ADMIN

#4187 feat(api): monitor certificats crons
  api/src/crons/index.js
  api/src/crons/monitorCertificats.js
Labels: Pull request title validation

#4160 feat(api): 2854 - Inscriptions des référents de classe
  api/migrations/20240809135541-add-feature-flag-invite-referent-classe.js
  api/migrations/20240809154147-add-feature-flag-invite-referent-classe-when-classe-verified.js
  api/src/__tests__/cle/referent.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/referent/referentController.ts
  api/src/cle/referent/referentRepository.ts
  api/src/emails/cle/classe.ts
  api/src/models/referent.ts
  api/src/services/cle/referent.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/constants/featureFlags.ts
Labels: ADMIN

#4186 feat(admin,lib): 2735 - saint barthelemy displays twice
  admin/src/scenes/team/components/filter/FilterDepartment.tsx
  packages/lib/src/region-and-departments.ts
Labels: ADMIN

#4191 fix(admin): fix center page error
  admin/src/scenes/centersV2/list.jsx
Labels: Pull request title validation, bypass title

#4192 fix(api): fix deleteOldReferentClasse test by improving order consist…
  api/src/__tests__/cle/referent.test.ts
Labels: bypass title

#4190 fix(api): 2907 - reset affectation informations when a young is switched to LC
  api/src/referent/referentController.ts
  api/src/young/youngService.test.ts
  api/src/young/youngService.ts
Labels: ADMIN

#4189 fix(api): export dsnj in local
  api/src/crons/dsnjExport/local.js
Labels: bypass title, ADMIN

#4188 feat(admin): 2856 - do not display attestation button for responsible…
  admin/src/scenes/phase0/components/YoungHeader.jsx
Labels: ADMIN

#4199 fix(app): No ticket - import erroné
  app/src/app.jsx
Labels: bypass title

#4206 fix(api): no ticket: Correction de la récupération du nom de la cohorte courante dans le tdb des refs reg et dep
  api/src/services/stats.service/inscription.js
Labels: bypass title

#4202 fix(admin): error on page pdr session
  admin/src/scenes/pointDeRassemblement/List.jsx
Labels: bypass title, ADMIN

#4219 feat(admin): add lazy loading on routes
  admin/src/app.jsx
Labels: Pull request title validation

#4217 fix(api): 2514 - remove some dynamic settings for CLE
  admin/src/scenes/settings/index.jsx
Labels: ADMIN, WAITING FOR QA

#4220 fix(api): 3147 - remove on of "juin 2022" cohort
  api/migrations/20240822095220-remove-juin-2022-cohort.js
Labels: ADMIN

#4221 feat(api): 3146 - migration of cohortIds for several collections
  api/migrations/20240822101008-add-cohortIds-into-collection.js
  api/src/cohort/cohortService.ts
  api/src/controllers/cohesion-center.js
  api/src/controllers/planDeTransport/point-de-rassemblement.js
  api/src/models/PlanDeTransport/pointDeRassemblement.ts
  api/src/models/cohesionCenter.ts
  api/src/models/referent.ts
  api/src/referent/referentController.ts
  api/src/utils/index.js
Labels: ADMIN

#4198 feat(api): 3119 - endpoint to import classe and cohort
  api/migrations/20240819142501-add-feature-flag-import-classe-cohort.js
  api/package.json
  api/src/__tests__/cle/classeImport.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/classe/import/classeCohortImport.ts
  api/src/cle/classe/import/classeCohortMapper.ts
  api/src/cle/classe/import/classeImportController.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
  api/src/cle/index.ts
  api/src/cohort/cohortService.test.ts
  api/src/cohort/cohortService.ts
  api/src/featureFlag/featureFlagService.ts
  api/src/services/fileService.test.ts
  api/src/services/fileService.ts
  package-lock.json
  packages/lib/src/constants/errors.ts
  packages/lib/src/constants/featureFlags.ts
Labels: ADMIN

#4223 fix(admin): ajout d'une sécurité sur la formulaire de création d'une classe sur le champ estimatedSeats
  admin/src/scenes/classe/create.tsx
  api/src/cle/classe/classeController.ts
  packages/ds/src/admin/form/InputNumber.tsx
Labels: bug, bypass title, ADMIN

#4227 feat(api): add info to changeloglock source
  api/src/migration.js
Labels: bypass title

#4228 feat(api): add doMigration flag to prevent running from local
  api/config/default.js
  api/config/development.js
  api/config/local-development.example.js
  api/src/migration.js
Labels: bypass title

#4231 feat(api,admin): 3156 - edit referent classe in classe
  admin/src/scenes/classe/components/ReferentInfos.tsx
  admin/src/scenes/classe/components/types.ts
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view.tsx
  api/src/__tests__/cle/classe.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.ts
  packages/lib/src/constants/functionalErrors.ts
  packages/lib/src/constants/referentConstants.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4230 feat(api): 3119 - some improvement after testing
  api/src/__tests__/cle/classeImport.test.ts
  api/src/cle/classe/import/classeCohortImport.ts
  api/src/cle/classe/import/classeImportController.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
  api/src/services/fileService.test.ts
  api/src/services/fileService.ts
  packages/lib/src/constants/functionalErrors.ts
Labels: ADMIN

#4240 fix(api): 3156 - add isFirstInvitationPending when create a new referent
  api/migrations/20240828123437-add-isFirstInvitationPending-when-create-referent-classe.js
  api/package.json
  api/src/__tests__/cle/classe.test.ts
  api/src/cle/classe/classeService.ts
Labels: ADMIN

#4242 fix(api): 3174 - referent deprtment cannot verify classe
  api/src/__tests__/cle/classe.test.ts
  api/src/cle/classe/classeController.ts
  packages/lib/src/dto/userDto.ts
Labels: ADMIN

#4161 feat(app, api, admin): 2969 et 2902 et 2968 - New young scolarity
  admin/src/scenes/phase0/components/sections/SectionParents.jsx
  admin/src/services/api.js
  api/src/__tests__/cle/classe.test.ts
  api/src/auth.js
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.ts
  api/src/controllers/young/inscription2023.js
  api/src/controllers/young/reinscription.js
  api/src/models/cle/classe.ts
  api/src/models/cohort.ts
  app/src/scenes/account/index.jsx
  app/src/scenes/account/scenes/school-situation/index.jsx
  app/src/scenes/cle/MyClass.jsx
  app/src/scenes/inscription2023/steps/correction/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
  app/src/services/classe.service.js
  packages/lib/src/constants/constants.ts
  packages/lib/src/translation.ts
Labels: bypass title

#4250 fix(api): 3071 - fix search page result size
  api/src/controllers/elasticsearch/mission.js
Labels: ADMIN
