Repository betagouv/service-national-universel, pull requests merged in 2024-09, with the labels that each got.

#4185 feat(api): 2451 - referent classe cannot manage MIG
  admin/src/scenes/phase0/components/YoungHeader.jsx
  packages/ds/src/admin/layout/Navbar.tsx
  packages/lib/src/roles.ts
Labels: ADMIN

#4256 fix(app): No ticket - Fix cohort service
  app/src/scenes/cle/MyClass.jsx
  app/src/utils/cohorts.js
Labels: bypass title

#4254 fix(api): 3200 - CLE correction des params d'email d'invitation des referents de classe
  api/src/__tests__/cle/referent.test.ts
  api/src/services/cle/referent.ts
Labels: ADMIN

#4253 feat(api): 3120 - change column name and add estimatedSeats update
  api/src/__tests__/cle/classeImport.test.ts
  api/src/cle/classe/import/classeCohortImport.ts
  api/src/cle/classe/import/classeCohortMapper.ts
  api/src/cle/classe/import/classeImportService.test.ts
  api/src/cle/classe/import/classeImportService.ts
Labels: ADMIN

#4257 fix(app): No ticket - Pas de redirection si 401 sur call cohortes
  app/src/services/api.js
  app/src/utils/cohorts.js
Labels: bypass title

#4260 fix(app): No ticket - Add missing calls to /cohort
  app/src/scenes/auth/desktop/signin2FA.jsx
  app/src/scenes/auth/mobile/signin2FA.jsx
  app/src/scenes/preinscription/EmailValidation.jsx
  app/src/scenes/preinscription/steps/stepConfirm.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
  app/src/utils/cohorts.js
Labels: bypass title

#4266 fix(api): 3181 - referent hide deletedat
  api/src/controllers/elasticsearch/referent.js
Labels: ADMIN

#4270 fix(app): No ticket - Afficher un loader sur l'espace volontaire pendant le chargement des données
  app/src/Espace.jsx
Labels: bypass title

#4271 feat(app): 399 - Add Notice Info For 1erGT inscription
  app/src/scenes/preinscription/steps/stepSejour.jsx
  packages/ds/src/dsfr/index.ts
  packages/ds/src/dsfr/ui/Notice.tsx
Labels: WAITING FOR QA

#4273 fix(api): 3223 - [CLE] Mettre à jour le statut des classes lors de la modification des dates d’ouverture et de fermeture
  api/src/cle/classe/stateManager.ts
Labels: Pull request title validation

#4248 feat(api): update referent for every classe status by super admin
  api/package.json
  api/src/__tests__/cle/classe.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  package-lock.json
Labels: bypass title, ADMIN, WAITING FOR QA

#4278 feat(admin): 3232 - donner aux modérateurs la possibilité d'ajouter une cohorte a une classe
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/volontaire-cle/List.tsx
Labels: ADMIN

#4275 fix(api): 3224 - [CLE] Dates des ouvertures, fermetures des inscriptions non programmables depuis les paramètres dynamiques (pas d’automatisation)
  api/src/cle/classe/stateManager.ts
  api/src/cohort/cohortService.ts
  api/src/crons/__tester__.ts
  api/src/crons/classesStatusUpdate.ts
  api/src/crons/index.js
Labels: WIP

#4268 fix(app, admin): No ticket - Reload app on import failure
  admin/src/index.jsx
  app/src/index.jsx
Labels: bypass title

#4251 feat(admin,api): 3002 - Ajouter les nouveau export dans la fiche des classes
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/components/StatsInfos.tsx
  admin/src/scenes/classe/components/WithdrawButton.tsx
  admin/src/scenes/classe/components/modale/ModaleWithdraw.tsx
  admin/src/scenes/classe/components/modaleCohort.tsx
  admin/src/scenes/classe/header/ButtonCertificateDownload.tsx
  admin/src/scenes/classe/header/ButtonDownloadEmptyFile.tsx
  admin/src/scenes/classe/header/ButtonHandleInscription.tsx
  admin/src/scenes/classe/header/ButtonLinkInvite.tsx
  admin/src/scenes/classe/header/ButtonManualInvite.tsx
  admin/src/scenes/classe/header/ButtonRelanceVerif.tsx
  admin/src/scenes/classe/header/DeleteButton.tsx
  admin/src/scenes/classe/header/VerifClassButton.tsx
  admin/src/scenes/classe/header/index.tsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/classe/view.tsx
  admin/src/services/convocation.service.js
  api/src/__tests__/cle/classe.test.ts
  api/src/cle/classe/classeController.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/young/youngController.ts
  api/src/templates/consent/consent.ts
  api/src/templates/convocation/cohesion.ts
  api/src/templates/droitImage/droitImage.ts
  api/src/templates/templateService.ts
  api/src/utils/pdf-renderer.ts
  api/src/young/youngCertificateService.ts
  api/src/young/youngDocument.ts
  api/src/young/youngService.test.ts
  api/src/young/youngService.ts
  packages/ds/src/admin/ui/DropdownButton.tsx
  packages/lib/src/constants/cle/classeConstants.ts
Labels: ADMIN, WAITING FOR QA

#4286 fix(admin): 3241 - fix cohort 2025
  admin/src/services/cohort.service.ts
Labels: ADMIN

#4308 fix(api): migration-young-inscription
  api/migrations/20240910084532-fix-young-inscriptionStep2023.js
Labels: Pull request title validation, bypass title, ADMIN

#4291 feat(api,admin,app): 3229 - POC Régionalisation de l’éligibilité back
  api/src/utils/cohort.js
  packages/lib/src/region-and-departments.ts
Labels: WIP, R&R

#4321 fix(api): Fix local logs
  api/src/logger.ts
Labels: bypass title

#4297 fix(admin): types forms component
  admin/src/components/ui/buttons/ButtonPrimary.tsx
  admin/src/components/ui/forms/DatePicker.jsx
  admin/src/components/ui/forms/DatePicker.tsx
  admin/src/components/ui/forms/InputText.tsx
  admin/src/components/ui/forms/InputTextarea.tsx
  admin/src/components/ui/forms/NumberInput.tsx
  admin/src/components/ui/forms/dateForm/DatePickerInput.tsx
  admin/src/components/ui/forms/dateForm/SimpleToggle.tsx
  admin/src/scenes/settings/tabs/GeneralTab.tsx
Labels: bypass title, R&R

#4325 fix(lib): Merge error in translation
  packages/lib/src/translation.ts
Labels: bypass title

#4311 feat(api): update referents by csv
  api/src/__tests__/cle/classes.test.ts
  api/src/cle/classes/classesController.ts
  api/src/cle/classes/classesService.test.ts
  api/src/cle/classes/classesService.ts
  api/src/cle/classes/classesValidator.ts
Labels: bypass title, ADMIN

#4332 fix(app): Mettre à jour correctement la date de naissance dans le contexte de la préinscription
  app/src/scenes/inscription2023/steps/correction/stepProfil.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
Labels: bypass title

#4313 chore(lib): Ajout des champs vrituels sur ClasseType
  api/src/__tests__/fixtures/PlanDeTransport/pointDeRassemblement.ts
  api/src/__tests__/fixtures/classe.ts
  api/src/__tests__/fixtures/cohesionCenter.ts
  api/src/__tests__/fixtures/etablissement.ts
  api/src/brevo.ts
  api/src/cle/appelAProjetCle/appelAProjetClasseService.ts
  api/src/cle/appelAProjetCle/appelAProjetEtablissementService.ts
  api/src/cle/appelAProjetCle/appelAProjetReferentService.ts
  api/src/cle/appelAProjetCle/appelAProjetType.ts
  api/src/cle/classe/classeService.test.ts
  api/src/cle/classe/classeService.ts
  api/src/cle/etablissement/etablissementController.ts
  api/src/cle/etablissement/etablissementMapper.ts
  api/src/emails/cle/classe.ts
  api/src/models/PlanDeTransport/pointDeRassemblement.ts
  api/src/models/cohesionCenter.ts
  api/src/models/index.ts
  api/src/models/types.ts
  api/src/providers/demarcheSimplifiee/demarcheSimplifieeProvider.ts
  api/src/services/cle/referent.ts
  api/src/young/youngCertificateService.ts
  packages/lib/src/mongoSchema/cle/classe.ts
  packages/lib/src/mongoSchema/cohesionCenter.ts
  packages/lib/src/mongoSchema/index.ts
  packages/lib/src/mongoSchema/pointDeRassemblement.ts
Labels: ADMIN

#4329 feat(api,admin): 3126 - ajout de plusieurs champs dans l'export des classes et etablissements
  admin/src/components/filters-system-v2/components/Filters.jsx
  admin/src/scenes/classe/components/GeneralInfos.tsx
  admin/src/scenes/classe/list.tsx
  admin/src/scenes/classe/list/ClasseRow.tsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/etablissement/List.tsx
  admin/src/scenes/etablissement/utils/index.ts
  api/src/cle/classe/classeController.ts
  api/src/controllers/elasticsearch/cle/etablissement.js
  api/src/controllers/elasticsearch/populate/populateEtablissement.js
  packages/lib/src/mongoSchema/cle/classe.ts
Labels: ADMIN

#4337 chore(api,lib): fix ObjectId Type in lib and model
  api/src/models/young.ts
  packages/lib/src/mongoSchema/young.ts
Labels: ADMIN

#4282 feat(api): authentication and access control middleware
  api/src/__tests__/cle/classe.test.ts
  api/src/__tests__/infra/accessControl.test.ts
  api/src/__tests__/infra/fakeEndpoint.ts
  api/src/cle/classe/classeController.ts
  api/src/controllers/request.ts
  api/src/middlewares/accessControlMiddleware.test.ts
  api/src/middlewares/accessControlMiddleware.ts
  api/src/middlewares/authMiddleware.test.ts
  api/src/middlewares/authMiddleware.ts
  api/src/middlewares/requestValidatorMiddleware.test.ts
  api/src/middlewares/requestValidatorMiddleware.ts
  api/src/utils/index.js
Labels: bypass title, ADMIN

#4339 fix(admin): - on supprime le champ virtuel fullName ca fou le dawa dans les exports
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/etablissement/utils/index.ts
Labels: bypass title

#4281 fix(app): 3209 - Fix Retour Inscription CLE
  app/src/components/dsfr/layout/Header.jsx
  app/src/index.css
  app/src/scenes/cle/MyClass.jsx
  app/src/scenes/cle/OnBoarding.jsx
  app/src/scenes/inscription2023/steps/stepConsentements.jsx
  app/src/scenes/phase1/waitingAffectation.jsx
  app/src/scenes/phase2/scenes/MesEngagements/components/Preferences/index.jsx
  app/src/scenes/preinscription/components/ProgressBar.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
  app/src/scenes/representants-legaux/commons.js
  app/src/scenes/representants-legaux/mobile/consentement.jsx
  app/src/scenes/representants-legaux/mobile/image-rights.jsx
  app/src/scenes/representants-legaux/mobile/presentation.jsx
  app/src/scenes/representants-legaux/mobile/verification.jsx
  packages/ds/src/dsfr/SignupButtons.tsx
Labels: WAITING FOR QA, VOLONTAIRES

#4341 fix(app, admin): Filtrer les fichiers modifiés avant de provoquer un rechargement des apps
  admin/vite.config.js
  app/vite.config.js
Labels: bug, bypass title

#4258 feat(api): 3171 - normalizeName for preventing Double Account
  api/src/auth.js
  api/src/utils/index.js
Labels: enhancement, VOLONTAIRES

#4335 fix(app, api): 3291 - Modifier le numéro de téléphone sur le profil du jeune
  api/src/controllers/young/account.js
  app/src/scenes/account/scenes/general/index.jsx
Labels: VOLONTAIRES

#4340 chore(lib): fix circular deps
  api/package.json
  package-lock.json
  packages/lib/package.json
  packages/lib/rollup.config.mjs
  packages/lib/src/mongoSchema/cle/classe.ts
  packages/lib/src/mongoSchema/cle/etablissement.ts
  packages/lib/src/mongoSchema/cohort.ts
  packages/lib/src/mongoSchema/referent.ts
  packages/lib/src/mongoSchema/young.ts
Labels: FIABILISATION

#4326 feat(api): 3240 - migrate - create CLE 2025 cohort and add verified classes
  admin/src/scenes/classe/components/GeneralInfos.tsx
  api/migrations/20240913131927-create-cohorte-cle-2025-globale.js
  api/src/referent/referentController.ts
  app/src/scenes/representants-legaux/mobile/presentation.jsx
  app/src/scenes/representants-legaux/mobile/verification.jsx
  packages/lib/src/constants/cohort.ts
  packages/lib/src/index.ts
  packages/lib/src/sessions.ts
  packages/lib/src/utils/cohortUtils.ts
Labels: ADMIN

#4347 chore(api,lib,app): update date-fns dep
  admin/package.json
  api/package.json
  app/package.json
  package-lock.json
  packages/lib/package.json
Labels: dependencies

#4343 chore(terraform): add reindexing job
  api/src/scripts/reindex_es_all_models/docker/start_reindex_es.sh
  api/src/scripts/reindex_es_all_models/index.js
  terraform/environments/ci/jobs.tf
  terraform/environments/production/jobs.tf
Labels: FIABILISATION

#4289 chore(api,app,admin): code climate coverage
  .codeclimate.yml
  api/src/cle/classe/import/classeImportService.ts
Labels: bypass title, ADMIN

#4336 fix(app): 3297 - Améliorer la gestion d'erreur du formulaire de liste de diffusion
  app/src/components/dsfr/layout/DSFRContainer.jsx
  app/src/scenes/preinscription/components/CreateContactForm.tsx
  app/src/scenes/preinscription/steps/stepNoSejour.jsx
  app/src/scenes/preinscription/steps/stepNoSejour.tsx
  packages/ds/src/dsfr/SignupButtons.tsx
Labels: VOLONTAIRES

#4348 fix(api): 3322 - les refs de classe et admin_cle ne pouvaient plus valider un jeune dans une classe depuis l'onglet "volontaire"
  admin/src/scenes/phase0/view.tsx
  packages/lib/src/roles.ts
Labels: bug

#4352 fix(app): 3329 - Corriger la redirection après la connexion 2FA
  app/src/scenes/auth/desktop/signin2FA.jsx
Labels: bug, VOLONTAIRES

#4350 fix(api): cle-manual-inscription-status
  api/migrations/20240919125411-young-add-missing-inprogress-status.js
  api/src/controllers/young/index.js
  api/src/referent/referentController.ts
  api/src/young/youngService.test.ts
  api/src/young/youngService.ts
Labels: bypass title, ADMIN

#4354 fix(api): Remove readMode from error logs
  api/docker_rsyslog.conf
Labels: bypass title

#4355 fix(api): no tickets - fix inscriptionStepStatus
  api/src/referent/referentController.ts
Labels: bypass title

#4358 fix(api): remove old countDocument for Signup CLE
  api/src/auth.js
Labels: bypass title

#4295 fix(admin, app): 3237 - Fix bug equivalence MIG phase 2
  api/src/controllers/application.js
  api/src/controllers/contract.js
  api/src/controllers/young/phase2.js
  api/src/utils/index.js
  app/src/scenes/phase2/scenes/MonEquivalence/EditEquivalence.jsx
Labels: bug, WAITING FOR QA, VOLONTAIRES

#4357 refactor(admin): ChangeCohortPen to TS
  admin/src/scenes/phase0/components/ChangeCohortPen.tsx
  admin/src/scenes/phase0/components/modal/ChangeCohortModal.tsx
  admin/src/scenes/phase0/utils/index.ts
  admin/src/scenes/phase0/utils/service.ts
  admin/src/utils/download-pdf.ts
Labels: bypass title, ADMIN, R&R

#4367 fix(misc): Update turbo.json with additional global environment variables
  admin/src/index.jsx
  api/src/index.js
  app/src/index.jsx
  turbo.json
Labels: Pull request title validation

#4369 fix(github): Update branch name in mirroring.yml
  .github/workflows/mirroring.yml
Labels: Pull request title validation

#4366 feat(admin,api): 3125 - Ajouter les infos CLE dans l'export des volontaires
  admin/src/scenes/volontaires/utils/index.js
  api/src/controllers/elasticsearch/young.js
  packages/lib/src/excelExports.ts
Labels: ADMIN

#4356 fix(api,admin): 3354 - fix de plusieurs bug CLE
  admin/src/scenes/classe/components/ReferentInfos.tsx
  admin/src/scenes/classe/components/SejourInfos.tsx
  admin/src/scenes/classe/components/StatsInfos.tsx
  admin/src/scenes/classe/view.tsx
  admin/src/scenes/volontaire-cle/List.tsx
  api/src/__tests__/young-edition.test.ts
  api/src/cle/classe/classeService.test.ts
  api/src/young/edition/youngEditionService.test.ts
  api/src/young/edition/youngEditionService.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4334 fix(app): 3233 - fix before refacto of the DatePicker
  app/src/scenes/inscription2023/components/StepUploadDesktop.jsx
  app/src/scenes/inscription2023/components/StepUploadMobile.jsx
  app/src/scenes/inscription2023/steps/stepUpload.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4323 fix(app): 3233 - Inscriptions HTS 2025 - 2/2 Retours P2 non Bloquant
  api/src/controllers/young/account.js
  app/src/components/forms/inputs/Checkbox.jsx
  app/src/components/modals/ModalRI.jsx
  app/src/context/RepresentantsLegauxContextProvider.jsx
  app/src/scenes/account/scenes/representants/index.jsx
  app/src/scenes/account/scenes/special-situations/index.jsx
  app/src/scenes/inscription2023/steps/correction/stepEligibilite.jsx
  app/src/scenes/inscription2023/steps/stepConsentements.jsx
  app/src/scenes/inscription2023/steps/stepCoordonnees.jsx
  app/src/scenes/phase1/scenes/affected/components/Convocation.jsx
  app/src/scenes/phase1/scenes/affected/components/FaqAffected.jsx
  app/src/scenes/preinscription/Done.jsx
  app/src/scenes/preinscription/steps/stepConfirm.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/src/scenes/preinscription/steps/stepNoSejour.tsx
  app/src/scenes/preinscription/steps/stepSejour.jsx
  app/src/scenes/representants-legaux/mobile/RiConsentement.jsx
  app/src/scenes/representants-legaux/mobile/consentement.jsx
  app/src/scenes/representants-legaux/mobile/verification.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4374 fix(api): cohesion center fix ES sync
  api/src/models/cohesionCenter.ts
Labels: Pull request title validation, bypass title, R&R

#4375 fix(api): Ajouter l'authentification pour la création de documents
  api/src/controllers/young/documents.js
Labels: Pull request title validation

#4359 feat(app): 3072 - Amélioration du tracking pour l'API Engagement
  api/src/models/mission.ts
  app/index.html
  app/src/scenes/missions/components/ApiEngagementTracker.jsx
  app/src/scenes/missions/components/ApplyButton.tsx
  app/src/scenes/preinscription/steps/stepConfirm.jsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  packages/lib/src/features.ts
  packages/lib/src/mongoSchema/engagement/mission.ts
  packages/lib/src/mongoSchema/index.ts
Labels: WAITING FOR QA, VOLONTAIRES

#4370 fix(api): reduction du temps de reponse de l'export des classes
  admin/src/scenes/classe/utils/index.ts
  api/src/controllers/elasticsearch/cle/classe.js
Labels: bypass title

#4372 fix(api): set QPV on young inscription
  api/src/controllers/young/inscription2023.js
Labels: Pull request title validation, bypass title

#4376 feat(admin): 3279 - preparation du front pour l'import des centres
  admin/src/scenes/centersV2/components/Field.tsx
  admin/src/scenes/centersV2/components/ModalRattacherCentre.tsx
  admin/src/scenes/centersV2/components/Toggle.tsx
  admin/src/scenes/centersV2/view/CenterInformations.tsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/MoreInfo.jsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/components/TabSession.jsx
  admin/src/scenes/dashboardV2/moderator-ref/subscenes/sejour/index.jsx
  admin/src/types.ts
Labels: ADMIN

#4338 feat(api): 3281 - import center and session
  api/src/__tests__/fixtures/cohesionCenter.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/cohesionCenter/cohesionCenterController.js
  api/src/cohesionCenter/import/cohesionCenterImport.ts
  api/src/cohesionCenter/import/cohesionCenterImportController.ts
  api/src/cohesionCenter/import/cohesionCenterImportMapper.ts
  api/src/cohesionCenter/import/cohesionCenterImportService.test.ts
  api/src/cohesionCenter/import/cohesionCenterImportService.ts
  api/src/cohesionCenter/import/cohesionCenterImportValidator.ts
  api/src/cohesionCenter/index.ts
  api/src/controllers/session-phase1.ts
  api/src/middlewares/accessControlMiddleware.test.ts
  api/src/middlewares/requestValidatorMiddleware.ts
  api/src/routes.ts
  api/src/sessionPhase1/import/sessionPhase1Import.ts
  api/src/sessionPhase1/import/sessionPhase1ImportController.ts
  api/src/sessionPhase1/import/sessionPhase1ImportMapper.ts
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
  api/src/sessionPhase1/import/sessionPhase1ImportValidator.ts
  packages/lib/src/constants/cohesionCenter.ts
  packages/lib/src/index.ts
  packages/lib/src/mongoSchema/cohesionCenter.ts
  packages/lib/src/mongoSchema/sessionPhase1.ts
Labels: ADMIN

#4380 fix(api,admin): 3376 - fix de l'inscription manuelle CLE
  admin/src/scenes/volontaires/create.jsx
  api/migrations/20240927142016-rattrapageYoung_Manual_Inscription_In_PROGRESS.js
  api/src/controllers/young/index.js
  api/src/utils/validator.ts
  api/src/young/youngService.ts
Labels: bug, ADMIN

#4284 fix(app): 3296 - React-query : recharger l'app en cas de 401
  app/package.json
  app/src/app.jsx
  app/src/index.jsx
  app/src/scenes/auth/desktop/signin.jsx
  app/src/scenes/auth/desktop/signin2FA.jsx
  app/src/scenes/auth/desktop/signupInvite.jsx
  app/src/scenes/auth/mobile/signin.jsx
  app/src/scenes/auth/mobile/signin2FA.jsx
  app/src/scenes/auth/mobile/signupInvite.jsx
  app/src/scenes/phase2/engagement.repository.js
  app/src/scenes/preinscription/EmailValidation.jsx
  app/src/scenes/preinscription/steps/stepConfirm.jsx
  app/src/scenes/preinscription/steps/stepProfil.jsx
  app/src/services/api.js
  app/src/services/react-query.js
  app/src/services/react-query.ts
  app/src/services/useAuth.js
  package-lock.json
Labels: bug, VOLONTAIRES

#4362 feat(app, api): 3238 - Change wording in convocation
  api/src/templates/convocation/cohesion.ts
  app/src/scenes/phase1/scenes/affected/components/Convocation.jsx
  app/src/scenes/phase1/scenes/affected/components/TodoBackpack.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4378 fix(app): 3406 - Set dayjs locale to fr globally
  app/src/app.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4387 feat(app): noTickets - change convocation wording
  app/src/scenes/phase1/scenes/affected/components/TodoBackpack.jsx
Labels: bypass title, VOLONTAIRES

#4371 feat(api, lib): 3242 - generate INJEP Export
  api/src/cohort/cohortController.ts
  api/src/crons/injepExport/index.js
  api/src/crons/injepExport/local.js
  api/src/crons/injepExport/utils.js
  api/src/models/cohort.ts
  packages/lib/src/mongoSchema/cohort.ts
Labels: VOLONTAIRES
