Repository betagouv/service-national-universel, pull requests merged in 2025-04, with the labels that each got.

#4876 feat(api, admin, lib): 379 - Mettre à jour les droits d'édition des lignes de transport
  admin/src/scenes/plan-transport/ligne-bus/View/View.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/authorization.ts
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/SessionSelector.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/index.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/ConfirmChangesModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
  api/src/__tests__/email-preview.test.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/controllers/emailPreview.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  packages/lib/src/actions/index.ts
  packages/lib/src/index.ts
  packages/lib/src/rolesConfig/index.ts
Labels: ADMIN

#4871 fix(api): 493 - lors de l'import des centres de sessions, ne plus se baser sur l'excel pour le nombres de places
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
Labels: deploy

#4907 feat(app): 517 - Question fréquente : stage de seconde
  app/src/scenes/phase1/scenes/affected/components/FaqAffected.jsx
Labels: deploy

#4889 feat(apiv2,admin): 152- Pouvoir supprimer une ligne de bus
  admin/src/components/views/HistoricServerDriven.tsx
  admin/src/scenes/plan-transport/ligne-bus/DeletePDTButton.tsx
  admin/src/scenes/plan-transport/ligne-bus/Historic.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/View.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Partials/DeleteLigneButton.tsx
  admin/src/services/phase1Service.ts
  api/src/controllers/planDeTransport/import.ts
  api/src/models/index.ts
  api/src/models/patch.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  apiv2/src/admin/core/history/History.gateway.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.gateway.ts
  apiv2/src/admin/core/sejours/phase1/PlanDeTransport/PlanDeTransport.model.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SupprimerLigneDeBus.ts
  apiv2/src/admin/core/sejours/phase1/demandeModificationLigneDeBus/DemandeModificationLigneDeBus.gateway.ts
  apiv2/src/admin/core/sejours/phase1/ligneDeBus/LigneDeBus.gateway.ts
  apiv2/src/admin/core/sejours/phase1/ligneDeBus/LigneDeBus.model.ts
  apiv2/src/admin/infra/history/repository/HistoryMapper.ts
  apiv2/src/admin/infra/history/repository/mongo/HistoryMongo.repository.ts
  apiv2/src/admin/infra/iam/auth/AddUserToRequest.middleware.ts
  apiv2/src/admin/infra/sejours/jeune/repository/mongo/JeuneMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/api/Phase1.controller.ts
  apiv2/src/admin/infra/sejours/phase1/api/Phase1.validation.ts
  apiv2/src/admin/infra/sejours/phase1/demandeModificationLigneDeBus/repository/mongo/DemandeModificationLigneDeBusMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/initProvider/useCase.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/LigneDeBus.mapper.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/mongo/LigneDeBusMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/planDeTransport/repository/PlanDeTransport.mapper.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/src/shared/infra/AllExceptions.filter.ts
  apiv2/test/admin/sejour/phase1/helper/PlanDeTransportHelper.ts
  packages/lib/src/dto/ligneDeBus.ts
  packages/lib/src/mongoSchema/patch.ts
  packages/lib/src/routes/phase1/deleteLigneBus.ts
  packages/lib/src/routes/phase1/index.ts
  packages/lib/src/translation.ts
Labels: deploy, QA OK

#4904 fix(admin): Phase 2/Contrat : ne pas tenter d'afficher l'historique si non autorisé
  admin/src/components/Contract.jsx
Labels: bug, bypass title, Phase 2, deploy

#4905 fix(api): 600 - Modifications de lignes fusionnées
  api/migrations/20250407144538-fusion-defusion.js
Labels: RUN

#4901 feat(apiv2): 458 - Désaffecter les jeunes et les classes à l'import SI-SNU
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.ts
Labels: deploy

#4909 fix(api): Corriger la migration de fusion de lignes
  api/migrations/20250407144538-fusion-defusion.js
Labels: bug, bypass title

#4897 feat(apiv2): 576 - 389 pmr programmation modele back calcul date
  apiv2/src/plan-marketing/core/Campagne.model.ts
  apiv2/src/plan-marketing/core/Programmation.model.ts
  apiv2/src/plan-marketing/core/gateway/Campagne.gateway.ts
  apiv2/src/plan-marketing/core/service/Programmation.service.spec.ts
  apiv2/src/plan-marketing/core/service/Programmation.service.ts
  apiv2/src/plan-marketing/core/useCase/MettreAJourCampagne.spec.ts
  apiv2/src/plan-marketing/core/useCase/MettreAJourCampagne.ts
  apiv2/src/plan-marketing/infra/Campagne.mapper.spec.ts
  apiv2/src/plan-marketing/infra/Campagne.mapper.ts
  apiv2/src/plan-marketing/infra/CampagneMongo.repository.ts
  apiv2/src/plan-marketing/infra/api/Campagne.validation.ts
  apiv2/src/plan-marketing/plan-marketing.module.ts
  apiv2/src/shared/core/Clock.gateway.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/src/shared/infra/Clock.provider.spec.ts
  apiv2/src/shared/infra/Clock.provider.ts
  apiv2/test/plan-marketing/CampagneMongo.repository.spec.ts
  packages/lib/src/mongoSchema/campagne.ts
Labels: WIP, ADMIN

#4918 chore(api): 608 - Loguer le comportement du cron de validation de la phase 1
  api/src/crons/autoValidatePhase1.ts
  api/src/utils/index.ts
Labels: bug, Phase 1

#4899 fix(api): 370 - Corriger le statut des candidatures aux PM quand le dossier PM est validé
  api/migrations/20250404135201-sync-pm-application-status.js
Labels: bug, Phase 2

#4900 fix(api): 489 - Corriger les statuts des missions et candidatures JVA annulées par le bug du 19/04
  api/migrations/20250404145622-fix-statut-missions-candidatures-jva.js
Labels: bug, Phase 2

#4916 feat(api): Crons pour detecter les incoherence entre les cohort des jeunes et celle de leur classe
  api/src/crons/__tester__.ts
  api/src/crons/checkClasseCoherence.ts
  api/src/crons/index.js
Labels: bypass title

#4906 feat(admin): 528 - Aligner l'export par département ou région sur celui des inscriptions
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/volontaires/list.jsx
  admin/src/scenes/volontaires/utils/index.js
Labels: ADMIN

#4910 fix(admin): 523 - Affichage des jeunes sur un centre alors qu’ils sont encore en attente d’affectation
  admin/src/scenes/centersV2/components/sessions/SessionVolontairesButton.tsx
  admin/src/scenes/centersV2/youngs/general.tsx
  packages/lib/src/dto/youngDto.ts
Labels: QA OK

#4930 feat(app): 592 - Mon compte/Phase 1 statut Affecté : Ajouter le contact de convocation
  app/src/scenes/phase1/scenes/affected/components/ContactsConvocation.tsx
  app/src/scenes/phase1/scenes/affected/components/Convocation.tsx
  app/src/scenes/phase1/scenes/affected/index.tsx
  app/src/scenes/phase1/scenes/affected/utils/useContactsConvocation.ts
  packages/lib/src/mongoSchema/departmentService.ts
Labels: VOLONTAIRES, Phase 1

#4936 fix(admin): 646 - CTA exporter les contacts
  admin/src/scenes/settings/operations/actions/Inscription/ExportContactSimulation/ExportContactConvocation.tsx
Labels: RUN, deploy

#4938 fix(admin): 650 - permission edit email fiche sanitaire
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
Labels: RUN

#4934 refactor(api): Simplifier davantage le cron de validation phase 1
  api/src/crons/autoValidatePhase1/index.ts
  api/src/crons/autoValidatePhase1/repository.ts
  api/src/crons/autoValidatePhase1/service.ts
  api/src/crons/autoValidatePhase1/utils.ts
  api/src/sessionPhase1/validation/sessionPhase1ValidationService.ts
Labels: bypass title

#4931 feat(apiv2): 392 - cron de gestion des envois programmés
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/AnnulerClasseDesistee.spec.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/modifierReferentClasse/ModifierReferentClasse.spec.ts
  apiv2/src/admin/infra/iam/api/Referent.validation.ts
  apiv2/src/admin/infra/sejours/phase1/session/repository/Session.mapper.ts
  apiv2/src/cron/jobs.config.ts
  apiv2/src/plan-marketing/core/Campagne.model.ts
  apiv2/src/plan-marketing/core/Programmation.model.ts
  apiv2/src/plan-marketing/core/gateway/Campagne.gateway.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.spec.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/core/service/CampagneProcessor.service.ts
  apiv2/src/plan-marketing/core/service/Programmation.service.spec.ts
  apiv2/src/plan-marketing/core/service/Programmation.service.ts
  apiv2/src/plan-marketing/core/useCase/BasculerArchivageCampagne.spec.ts
  apiv2/src/plan-marketing/core/useCase/cron/EnvoyerCampagneProgrammee.spec.ts
  apiv2/src/plan-marketing/core/useCase/cron/EnvoyerCampagneProgrammee.ts
  apiv2/src/plan-marketing/infra/Campagne.mapper.spec.ts
  apiv2/src/plan-marketing/infra/Campagne.mapper.ts
  apiv2/src/plan-marketing/infra/CampagneMongo.repository.ts
  apiv2/src/plan-marketing/infra/api/Campagne.validation.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/test/plan-marketing/CampagneHelper.ts
  apiv2/test/plan-marketing/CampagneMongo.repository.spec.ts
  apiv2/test/plan-marketing/EnvoyerCampagneProgrammee.spec.ts
  apiv2/test/plan-marketing/setUpPlanMarketingTest.ts
  packages/lib/src/mongoSchema/campagne.ts
Labels: ADMIN

#4941 fix(admin): 280 - Corriger le comportement du formulaire d'édition de classe
  admin/src/scenes/classe/view/Details.tsx
Labels: bug, ADMIN, deploy

#4942 fix(admin): 624 - afficher l'heure du traitement dans la modale de selection des désistements de masse
  admin/src/scenes/settings/operations/actions/Desistement/SimulationDesistementModal.tsx
Labels: deploy

#4917 fix(api): 526 - Notifications aux chef de structure parametre manquant
  api/src/application/applicationController.ts
  api/src/application/applicationNotificationService.ts
Labels: deploy

#4947 feat(admin): 386 - Ajout de la gestion des programmations dans le for…
  admin/src/scenes/planMarketing/campagne/CampagneSpecifique.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifiqueForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifiqueHook.ts
  admin/src/scenes/planMarketing/campagne/ProgrammationForm.tsx
  admin/src/scenes/planMarketing/campagne/ProgrammationList.tsx
  admin/src/scenes/planMarketing/campagne/mapper/CampagneSpecifiqueMapper.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.spec.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/core/useCase/BasculerArchivageCampagne.spec.ts
  apiv2/src/plan-marketing/core/useCase/BasculerArchivageCampagne.ts
  apiv2/src/plan-marketing/core/useCase/cron/EnvoyerCampagneProgrammee.spec.ts
  apiv2/src/plan-marketing/core/useCase/cron/EnvoyerCampagneProgrammee.ts
  apiv2/src/plan-marketing/infra/api/Campagne.controller.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/test/plan-marketing/CampagneMongo.repository.spec.ts
  apiv2/test/plan-marketing/EnvoyerCampagneProgrammee.spec.ts
  packages/lib/src/constants/colors.ts
  packages/lib/src/utils/date.ts
Labels: ADMIN

#4951 feat(apiv2): 385 - Import des programmations depuis une camapgne géné…
  .cursor/rules/typescript-best-practices.mdc
  apiv2/src/plan-marketing/core/service/Programmation.service.spec.ts
  apiv2/src/plan-marketing/core/service/Programmation.service.ts
Labels: ADMIN

#4915 fix(api, app): 581 - Mon Compte/Home : Corriger les états "Phase 2 réalisée" et "Cohorte archivée"
  api/src/cohort/cohortController.ts
  app/src/scenes/home/index.tsx
Labels: bug, VOLONTAIRES, Phase 2

#4926 fix(lib, api, app): 590 - Aligner et corriger les permissions d'accès et de candidature à la phase 2
  api/migrations/20250416121813-fix-youngStatusPhase2OpenAt.js
  api/src/application/applicationController.ts
  api/src/application/applicationService.ts
  api/src/controllers/young/index.ts
  api/src/controllers/young/phase1.ts
  api/src/crons/autoValidatePhase1/repository.ts
  api/src/equivalence/equivalenceController.ts
  api/src/sessionPhase1/notification/sessionPhase1NotificationService.ts
  api/src/sessionPhase1/validation/sessionPhase1ValidationService.ts
  api/src/young/edition/youngEditionController.ts
  app/src/Espace.jsx
  app/src/components/layout/navbar/components/NavigationMenu.jsx
  app/src/components/layout/navbar/components/UserCard.jsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/militaryPreparation/HomeDesktop.jsx
  app/src/scenes/militaryPreparation/HomeMobile.jsx
  app/src/scenes/missions/index.jsx
  app/src/utils/index.js
  packages/lib/src/sessions.ts
Labels: bug, VOLONTAIRES, Phase 2, deploy

#4954 fix(app): 595 - Phase 1/statut Affecté : Valider l'étape de convocation après chaque action disponible
  app/src/scenes/phase1/scenes/affected/components/modals/ConvocationModal.jsx
  app/src/scenes/phase1/scenes/affected/components/step/stepConvocation.tsx
  app/src/scenes/phase1/scenes/affected/utils/affectationRepository.ts
  app/src/scenes/phase1/scenes/affected/utils/convocationMutations.ts
Labels: bug, VOLONTAIRES, Phase 1

#4961 fix(api): fix du crons checkClasseCoherence
  api/src/crons/checkClasseCoherence.ts
Labels: bypass title

#4964 fix(app): Ecran Phase 1/statut Affecté : Ne pas afficher "0" si aucun contact renseigné
  app/src/components/modals/ModalConfirm.jsx
  app/src/components/ui/buttons/ButtonLight.jsx
  app/src/components/ui/modals/Modal.jsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/phase1/components/MedicalFileModal.tsx
  app/src/scenes/phase1/index.tsx
  app/src/scenes/phase1/scenes/affected/components/ModalConvocation.jsx
  app/src/scenes/phase1/scenes/affected/components/ModalConvocation.tsx
  app/src/scenes/phase1/scenes/affected/components/TodoBackpack.tsx
  app/src/scenes/phase1/scenes/affected/components/TravelInfo.tsx
  app/src/scenes/phase1/scenes/affected/index.tsx
  app/src/scenes/phase1/scenes/affected/utils/convocationMutations.ts
  app/src/scenes/phase1/waitingAffectation.tsx
Labels: bug, bypass title, Phase 1, Jeune, deploy

#4963 fix(admin): sentry - handle case "match" return null in function getInitials
  admin/src/components/drawer/components/Profil.jsx
Labels: bypass title

#4959 feat(admin, apiv2): 382 - modification des campagnes génériques et im…
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneFormHook.ts
  admin/src/services/planMarketingService.ts
  apiv2/src/plan-marketing/core/Campagne.model.ts
  apiv2/src/plan-marketing/core/gateway/Campagne.gateway.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/core/useCase/EnvoyerCampagne.spec.ts
  apiv2/src/plan-marketing/core/useCase/EnvoyerCampagne.ts
  apiv2/src/plan-marketing/infra/CampagneMongo.repository.ts
  apiv2/src/plan-marketing/infra/api/Campagne.controller.ts
  packages/lib/src/routes/planMarketing/index.ts
Labels: ADMIN

#4972 feat(admin): 682 - ajout de la fonctionnalité d'inscription en masse …
  .cursor/rules/admin-react-design-system.mdc
  admin/src/scenes/classe/header/ButtonInscriptionEnMasse.tsx
  admin/src/scenes/classe/header/index.tsx
  admin/src/scenes/classe/index.tsx
  admin/src/scenes/classe/inscriptionEnMasse/FileUploadPanel.tsx
  admin/src/scenes/classe/inscriptionEnMasse/InscriptionEnMassePage.tsx
  admin/src/scenes/classe/inscriptionEnMasse/MappingModal.tsx
  admin/src/scenes/classe/inscriptionEnMasse/SelectMapping.tsx
  admin/src/scenes/classe/inscriptionEnMasse/SuccessModal.tsx
  admin/src/scenes/classe/inscriptionEnMasse/ValidationFile.tsx
  admin/src/scenes/classe/inscriptionEnMasse/useFileUploadHandler.ts
  packages/lib/src/roles.ts
Labels: ADMIN

#4974 fix(app): 567 - Home Phase 1 : Correction du bouton "Trouver un engagement" pour les cohortes non archivées
  app/src/scenes/phase2/scenes/Home/index.jsx
Labels: bug, Phase 1, Jeune, deploy

#4977 fix(api): Cron de validation de phase 1 : Corriger le comportement en cas d'absence de date de départ
  api/src/crons/autoValidatePhase1/repository.ts
  api/src/sessionPhase1/validation/sessionPhase1ValidationService.ts
Labels: bug, bypass title

#4982 fix(admin,api) - Fix sentry errors
  admin/src/scenes/volontaires-responsible/listV2.jsx
  api/src/controllers/elasticsearch/plandetransport.js
  api/src/referent/referentController.ts
Labels: bypass title
