Repository betagouv/service-national-universel, pull requests merged in 2025-01, with the labels that each got.

#4618 feat(api, app): 3593 - Evolution du parcours volontaires "à venir"
  app/src/Espace.jsx
  app/src/app.jsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/home/AvenirCohort.jsx
  app/src/scenes/home/WaitingReinscription.jsx
  app/src/scenes/home/components/StatusNotice.tsx
  app/src/scenes/home/index.tsx
  app/src/scenes/home/refusedV2.jsx
  app/src/scenes/inscription2023/index.jsx
  app/src/scenes/preinscription/components/EngagementPrograms.jsx
  app/src/scenes/reinscription/ReinscriptionClosed.tsx
  app/src/scenes/reinscription/index.tsx
  app/src/utils/navigation.js
  packages/lib/src/sessions.ts
Labels: VOLONTAIRES

#4638 fix(app): 3520 - Empêcher la propagation des clics dans le composant SearchableSelect
  admin/package.json
  app/package.json
  app/src/components/dsfr/forms/SearchableSelect.jsx
  app/src/scenes/auth/mobile/signin.jsx
  app/src/scenes/auth/mobile/signin2FA.jsx
  package-lock.json
Labels: VOLONTAIRES

#4634 feat(app): 3549 - change equivalence logic
  api/src/controllers/young/phase2.js
  app/src/scenes/phase2/scenes/MonEquivalence/EditEquivalence.jsx
  app/src/scenes/phase2/scenes/MonEquivalence/MonEquivalence.jsx
Labels: VOLONTAIRES

#4644 feat(admin): fix de quelques bug CLE mineurs
  admin/src/scenes/classe/view/Details.tsx
  admin/src/scenes/classe/view/Historique.tsx
  admin/src/scenes/classe/view/Inscriptions.tsx
  admin/src/scenes/phase0/components/modal/ChangeCohortModal.tsx
Labels: bypass title

#4654 fix(api): 3849 - young add missing inprogress status
  api/migrations/20250110110711-young-add-missing-inprogress-status.js
Labels: RUN

#4642 feat(api,admin): 3830 - FF fermeture bascule manuelle sur LP pour les référents regionaux
  admin/src/scenes/phase0/components/YoungHeader.jsx
  admin/src/scenes/settings/general/GeneralTab.tsx
  admin/src/scenes/volontaires/view/index.tsx
  api/src/cohort/cohortValidator.ts
  api/src/referent/referentController.ts
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/mongoSchema/cohort.ts
  packages/lib/src/roles.ts
Labels: RUN

#4653 fix(app): N'afficher l'écran "En attente de réinscription" qu'aux volontaires sur la cohorte "à venir"
  app/src/scenes/home/index.tsx
Labels: bypass title, VOLONTAIRES

#4660 fix(api): 3864 - Algo affectation HTS places sejour negatif
  .vscode/tasks.json
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.ts
Labels: RUN, R&R

#4659 fix(admin): validation titre message d'alerte
  admin/src/scenes/alerte/AlerteMessageForm.tsx
Labels: RUN

#4665 fix(api): 3639 - Corriger le CTA des templates liés au changement de cohorte
  api/src/emails/young/changeCohortEmail.js
Labels: VOLONTAIRES

#4666 fix(api): 3840 - les référents ne peuvent plus modifier le dossier des volontaires après l'instruction
  api/src/referent/referentController.ts
  api/src/young/edition/youngEditionController.ts
Labels: RUN

#4641 feat(app, api): 3057 - add the possibility to remove an equivalence
  api/src/__tests__/equivalence.test.ts
  api/src/__tests__/fixtures/equivalence.ts
  api/src/__tests__/helpers/equivalence.ts
  api/src/controllers/young/phase2.js
  app/src/components/modals/ResponsiveModal.tsx
  app/src/scenes/phase2/engagement.repository.ts
  app/src/scenes/phase2/scenes/MonEquivalence/MonEquivalence.jsx
Labels: VOLONTAIRES

#4645 feat(app): 2963 - change wording for fiche sanitaire
  app/src/scenes/phase1/Files.jsx
  app/src/scenes/phase1/components/MedicalFileModal.jsx
  app/src/scenes/phase1/scenes/affected/components/step/stepMedicalFile.jsx
Labels: WAITING FOR QA, VOLONTAIRES

#4658 fix(api,admin): 3651 - button import pdr
  .vscode/tasks.json
  admin/src/scenes/classe/Import.tsx
  admin/src/scenes/pointDeRassemblement/List.tsx
  admin/src/scenes/pointDeRassemblement/components/ImportPDRButton.tsx
  admin/src/services/ReferentielService.ts
  admin/src/services/api.js
  api/src/brevo.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImport.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportController.ts
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportService.ts
  api/src/services/fileService.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.spec.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/utils/file.ts
Labels: R&R

#4476 Release 3395 front back
  admin/src/scenes/centersV2/list.jsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/plan-transport/ligne-bus/List.jsx
  admin/src/scenes/plan-transport/util.jsx
  admin/src/scenes/pointDeRassemblement/List.tsx
  admin/src/scenes/volontaires/utils/index.js
  api/src/__tests__/fixtures/PlanDeTransport/importPlanTransport.ts
  api/src/__tests__/helpers/PlanDeTransport/planDeTransport.ts
  api/src/__tests__/plan-de-transport.test.ts
  api/src/cohesionCenter/cohesionCenterController.js
  api/src/controllers/elasticsearch/cohesioncenter.js
  api/src/controllers/elasticsearch/pointderassemblement.js
  api/src/controllers/elasticsearch/sessionphase1.js
  api/src/controllers/planDeTransport/import.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  packages/lib/src/constants/functionalErrors.ts
  packages/lib/src/constants/plan-de-transport.ts
Labels: bypass title, ADMIN, WAITING FOR QA

#4673 refactor(app): 3235 - Passage à React-Query pour les informations d'affectation
  app/src/scenes/home/Affected.jsx
  app/src/scenes/phase1/components/ChangeStayLink.jsx
  app/src/scenes/phase1/components/MedicalFileModal.jsx
  app/src/scenes/phase1/scenes/affected/assets/SnuBackPack.jsx
  app/src/scenes/phase1/scenes/affected/components/CenterInfo.jsx
  app/src/scenes/phase1/scenes/affected/components/Convocation.tsx
  app/src/scenes/phase1/scenes/affected/components/StepCard.jsx
  app/src/scenes/phase1/scenes/affected/components/StepsAffected.tsx
  app/src/scenes/phase1/scenes/affected/components/TodoBackpack.jsx
  app/src/scenes/phase1/scenes/affected/components/TravelInfo.jsx
  app/src/scenes/phase1/scenes/affected/components/modals/AgreementModal.jsx
  app/src/scenes/phase1/scenes/affected/components/modals/ConvocationModal.jsx
  app/src/scenes/phase1/scenes/affected/components/modals/PDRModal.jsx
  app/src/scenes/phase1/scenes/affected/components/step/StepPDR.tsx
  app/src/scenes/phase1/scenes/affected/components/step/stepAgreement.tsx
  app/src/scenes/phase1/scenes/affected/components/step/stepConvocation.tsx
  app/src/scenes/phase1/scenes/affected/components/step/stepMedicalFile.tsx
  app/src/scenes/phase1/scenes/affected/index.jsx
  app/src/scenes/phase1/scenes/affected/index.tsx
  app/src/scenes/phase1/scenes/affected/utils/affectationRepository.ts
  app/src/scenes/phase1/scenes/affected/utils/steps.utils.js
  app/src/scenes/phase1/scenes/affected/utils/steps.utils.ts
  app/src/scenes/phase1/scenes/affected/utils/useAffectationInfo.ts
  app/src/scenes/phase1/scenes/affected/utils/useAvailableMeetingPoints.ts
  app/src/scenes/phase1/scenes/affected/utils/useUpdateMeetingPoint.ts
Labels: VOLONTAIRES

#4655 feat(apiv2): 3817 - importer et annuler classes desistees
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/AdminJob.module.ts
  apiv2/src/admin/core/history/History.gateway.ts
  apiv2/src/admin/core/referentiel/Referentiel.service.spec.ts
  apiv2/src/admin/core/referentiel/Referentiel.service.ts
  apiv2/src/admin/core/referentiel/Referentiel.ts
  apiv2/src/admin/core/referentiel/classe/ReferentielClasse.mapper.ts
  apiv2/src/admin/core/referentiel/classe/ReferentielClasse.model.ts
  apiv2/src/admin/core/referentiel/classe/ReferentielClasse.service.spec.ts
  apiv2/src/admin/core/referentiel/classe/ReferentielClasse.service.ts
  apiv2/src/admin/core/referentiel/classe/useCase/DesisterClasses.spec.ts
  apiv2/src/admin/core/referentiel/classe/useCase/DesisterClasses.ts
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.spec.ts
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.ts
  apiv2/src/admin/core/referentiel/routes/ReferentielImportTask.model.ts
  apiv2/src/admin/core/sejours/cle/classe/Classe.gateway.ts
  apiv2/src/admin/core/sejours/cle/classe/Classe.model.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/AnnulerClasseDesistee.spec.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/AnnulerClasseDesistee.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.gateway.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.model.ts
  apiv2/src/admin/core/sejours/phase1/centre/Centre.gateway.ts
  apiv2/src/admin/core/sejours/phase1/sejour/Sejour.gateway.ts
  apiv2/src/admin/core/sejours/phase1/session/Session.gateway.ts
  apiv2/src/admin/infra/history/repository/mongo/HistoryMongo.repository.ts
  apiv2/src/admin/infra/referentiel/api/ImportReferentiel.controller.ts
  apiv2/src/admin/infra/referentiel/initProvider/service.ts
  apiv2/src/admin/infra/referentiel/initProvider/useCase.ts
  apiv2/src/admin/infra/sejours/cle/classe/repository/mongo/ClasseMongo.repository.ts
  apiv2/src/admin/infra/sejours/jeune/repository/Jeune.mapper.ts
  apiv2/src/admin/infra/sejours/jeune/repository/mongo/JeuneMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/centre/repository/mongo/CentreMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/sejour/repository/mongo/SejourMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/session/repository/mongo/SessionMongo.repository.ts
  apiv2/src/admin/infra/task/AdminTask.consumer.ts
  apiv2/src/admin/infra/task/AdminTaskImportReferentielSelector.service.ts
  apiv2/src/notification/NotificationJob.module.ts
  apiv2/src/notification/core/Notification.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevo.mapper.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevo.provider.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevoCatcher.provider.ts
  apiv2/src/notification/infra/email/brevo/EmailContact.factory.ts
  apiv2/src/shared/core/Clock.gateway.ts
  apiv2/src/shared/infra/Clock.provider.ts
  packages/lib/src/constants/referentiel.ts
  packages/lib/src/constants/task.ts
Labels: ADMIN

#4682 fix(admin): 129 - remove department and region default value on filte…
  admin/src/scenes/plan-transport/ligne-bus/List.jsx
Labels: bug, ADMIN

#4685 feat(api): 150 - Amélioration de l’algo d’affectation HTS (ajout code route)
  admin/src/scenes/plan-transport/ligne-bus/View/components/Info.tsx
  api/src/__tests__/fixtures/PlanDeTransport/importPlanTransport.ts
  api/src/__tests__/helpers/PlanDeTransport/planDeTransport.ts
  api/src/__tests__/helpers/db.ts
  api/src/controllers/planDeTransport/import.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.ts
  apiv2/src/admin/core/sejours/phase1/ligneDeBus/LigneDeBus.model.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/LigneDeBus.mapper.ts
  packages/lib/src/mongoSchema/planDeTransport/ligneBus.ts
  packages/lib/src/mongoSchema/planDeTransport/planTransport.ts
Labels: RUN, Phase 1

#4692 feat(api,lib): 75 - maj jeunes avec motif de depart NOT_DONE status phase1 j-8
  api/src/crons/autoValidatePhase1.ts
  packages/lib/src/domains/sejours/phase1/contants.ts
Labels: R&R, Phase 1

#4691 fix(app): 148 - block RL validation when cohort inscrution is passed
  app/src/scenes/representants-legaux/mobile/presentation.jsx
Labels: bug, RUN

#4694 fix(api): 158 - bulkwrite unset undefined
  apiv2/src/admin/infra/sejours/jeune/repository/mongo/JeuneMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/mongo/LigneDeBusMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/planDeTransport/repository/mongo/PlanDeTransportMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/sejour/repository/mongo/SejourMongo.repository.ts
  apiv2/src/shared/infra/RepositoryHelper.spec.ts
  apiv2/src/shared/infra/RepositoryHelper.ts
  apiv2/test/admin/sejour/phase1/Phase1.controller.spec.ts
  apiv2/test/admin/sejour/phase1/helper/JeuneHelper.ts
Labels: RUN, Phase 1

#4672 Refactor(app): 3234 - Refacto Auth to typescript and DSFR
  app/src/components/dsfr/forms/input.jsx
  app/src/components/error.tsx
  app/src/index.css
  app/src/scenes/auth/desktop/forgot.jsx
  app/src/scenes/auth/desktop/reset.jsx
  app/src/scenes/auth/desktop/signin.jsx
  app/src/scenes/auth/desktop/signupInvite.jsx
  app/src/scenes/auth/forgot.tsx
  app/src/scenes/auth/index.jsx
  app/src/scenes/auth/index.tsx
  app/src/scenes/auth/mobile/forgot.jsx
  app/src/scenes/auth/mobile/reset.jsx
  app/src/scenes/auth/mobile/signin.jsx
  app/src/scenes/auth/mobile/signin2FA.jsx
  app/src/scenes/auth/mobile/signupInvite.jsx
  app/src/scenes/auth/reset.tsx
  app/src/scenes/auth/signin.tsx
  app/src/scenes/auth/signin2FA.tsx
  app/src/scenes/auth/signupInvite.tsx
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
Labels: VOLONTAIRES

#4647 feat(api): 3751 - import PDT: type transport autocar
  api/src/controllers/planDeTransport/import.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportUtils.ts
Labels: R&R

#4667 chore(misc): Use only one docker image for CI
  .github/workflows/test-deploy-ci.yml
  admin/package.json
  api/package.json
  apiv2/src/main.ts
  app/package.json
  devops/ci/Dockerfile
  devops/ci/build-application-docker.js
  devops/ci/nginx.conf
  devops/ci/supervisord.ini
Labels: bypass title

#4698 feat(api): 181 - ajout colonnes hzr sur la simulation hts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.ts
Labels: Phase 1

#4705 fix(tests): add directConnection parameter to test database connection
  api/src/__tests__/helpers/db.ts
Labels: bypass title

#4635 feat(api,admin): 3704 - PDT Lignes fusinonnees et miroirs
  admin/src/scenes/plan-transport/ligne-bus/List.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/View.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/BusTeam.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Info.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Itineraire.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Modification.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Partials/MergedBus.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Partials/MirrorBus.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
  admin/src/scenes/plan-transport/ligne-bus/import/components/Import.tsx
  api/migrations/20250106144313-update-mergedbus.js
  api/src/__tests__/fixtures/PlanDeTransport/importPlanTransport.ts
  api/src/__tests__/plan-de-transport.test.ts
  api/src/controllers/planDeTransport/import.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusMapper.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportUtils.test.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportUtils.ts
  api/src/routes.ts
  apiv2/src/admin/core/sejours/phase1/PlanDeTransport/PlanDeTransport.model.ts
  apiv2/src/admin/core/sejours/phase1/ligneDeBus/LigneDeBus.model.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/LigneDeBus.mapper.ts
  apiv2/src/admin/infra/sejours/phase1/planDeTransport/repository/PlanDeTransport.mapper.ts
  apiv2/test/admin/sejour/phase1/helper/PlanDeTransportHelper.ts
  packages/lib/src/constants/plan-de-transport.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/dto/ligneDeBus.ts
  packages/lib/src/mongoSchema/planDeTransport/ligneBus.ts
  packages/lib/src/mongoSchema/planDeTransport/planTransport.ts
  packages/lib/src/plandetransport/ligneService.spec.ts
  packages/lib/src/plandetransport/ligneService.ts
Labels: R&R
