Repository betagouv/service-national-universel, pull requests merged in 2025-02, with the labels that each got.

#4706 chore(analytics): remove env-manager
  devops/analytics/package.json
  devops/analytics/scripts/anonymize_DB.js
  devops/analytics/src/config.js
  devops/analytics/src/env-manager.js
  devops/analytics/src/index.js
  package-lock.json
  package.json
Labels: bypass title

#4701 feat(api,admin): 145 - revert dafd331 and keep matricule in front filter a…
  admin/src/components/filters-system-v2/components/filters/utils.js
  admin/src/scenes/centersV2/list.jsx
  admin/src/scenes/classe/utils/index.ts
  admin/src/scenes/plan-transport/ligne-bus/List.tsx
  admin/src/scenes/plan-transport/util.jsx
  admin/src/scenes/pointDeRassemblement/List.tsx
  admin/src/scenes/volontaires/utils/index.js
  api/src/__tests__/fixtures/PlanDeTransport/importPlanTransport.ts
  api/src/__tests__/helpers/PlanDeTransport/planDeTransport.ts
  api/src/__tests__/helpers/db.ts
  api/src/__tests__/plan-de-transport.test.ts
  api/src/controllers/elasticsearch/sessionphase1.js
  api/src/controllers/planDeTransport/import.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  api/src/planDeTransport/planDeTransport/import/pdtImportUtils.ts
  packages/lib/src/constants/functionalErrors.ts
  packages/lib/src/constants/plan-de-transport.ts
Labels: RUN, WAITING FOR QA, Phase 1

#4687 fix(api): 101 - Reset les infos CLE lors du parcours ReInscription
  api/src/controllers/young/reinscription.js
  api/src/referent/referentController.ts
Labels: deploy

#4677 feat(api,admin,lib): 43 - changement pdr sur une ligne de bus
  admin/src/app.jsx
  admin/src/assets/icons/CheckCircleFull.jsx
  admin/src/assets/icons/XCircleFull.jsx
  admin/src/scenes/email-preview/index.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/ConfirmChangesModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblementLabel.tsx
  api/src/__tests__/email-preview.test.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/brevo.ts
  api/src/controllers/emailPreview.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  api/src/routes.ts
  api/src/services/LigneDeBusService.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/utils/date.ts
Labels: R&R, deploy

#4709 refactor(api, admin): 211 - Listes de volontaires - optimiser la récupération des labels de filtres
  admin/src/scenes/classe/utils/useClass.ts
  admin/src/scenes/classe/view/index.tsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/volontaire-cle/List.tsx
  admin/src/scenes/volontaire-cle/utils/list.ts
  admin/src/scenes/volontaires/list.jsx
  admin/src/scenes/volontaires/useFilterLabels.ts
  admin/src/scenes/volontaires/utils/index.js
  api/src/filterLabel/filterLabelController.ts
  api/src/filterLabel/filterLabelRepository.ts
  api/src/filterLabel/filterLabelService.ts
  api/src/routes.ts
  packages/lib/src/dto/filterLabelDto.ts
  packages/lib/src/dto/index.ts
  packages/lib/src/routes/filterLabel/index.ts
  packages/lib/src/routes/index.ts
Labels: deploy

#4684 fix(api): 127 - add SchoolDepartment for CLE export
  api/migrations/20250122095753-fixSchoolDepartmentForCle.js
  api/src/controllers/elasticsearch/young.js
  api/src/controllers/young/index.ts
Labels: bug, ADMIN

#4680 feat(admin): front pour import des référentiels
  admin/src/app.jsx
  admin/src/components/drawer/components/Profil.jsx
  admin/src/scenes/importSiSnu/ImportFileTypeCell.tsx
  admin/src/scenes/importSiSnu/ImportRapportCell.tsx
  admin/src/scenes/importSiSnu/ImportSelectModal.tsx
  admin/src/scenes/importSiSnu/index.tsx
  admin/src/scenes/settings/operations/actions/AffectationSimulation/AffectationHTSSimulationMetropoleModal.tsx
  admin/src/services/ReferentielService.ts
  apiv2/src/admin/core/referentiel/classe/ReferentielClasse.mapper.ts
  apiv2/src/admin/infra/referentiel/api/ImportReferentiel.controller.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/test/admin/referentiel/ImportReferentielController.spec.ts
  package-lock.json
  package.json
  packages/ds/src/admin/form/Select/Select.tsx
  packages/ds/src/admin/index.ts
  packages/lib/src/routes/referentiel/getImportsReferentiel.ts
  packages/lib/src/translation.ts
Labels: bypass title, WAITING FOR QA, Referentiel, deploy

#4713 feat(apiv2): 208 - creer une liste de diffusion
  apiv2/src/App.module.ts
  apiv2/src/admin/Admin.module.ts
  apiv2/src/config/configuration.ts
  apiv2/src/plan-marketing/core/PlanMarketing.model.ts
  apiv2/src/plan-marketing/core/PlanMarketingActionSelector.service.ts
  apiv2/src/plan-marketing/core/gateway/PlanMarketing.gateway.ts
  apiv2/src/plan-marketing/core/useCase/AssocierListeDiffusionToCampagne.spec.ts
  apiv2/src/plan-marketing/core/useCase/AssocierListeDiffusionToCampagne.ts
  apiv2/src/plan-marketing/core/useCase/ImporterEtCreerListeDiffusion.spec.ts
  apiv2/src/plan-marketing/core/useCase/ImporterEtCreerListeDiffusion.ts
  apiv2/src/plan-marketing/infra/api/PlanMarketing.controller.ts
  apiv2/src/plan-marketing/infra/guard/BrevoIpGuard.spec.ts
  apiv2/src/plan-marketing/infra/guard/BrevoIpGuard.ts
  apiv2/src/plan-marketing/infra/provider/PlanMarketing.factory.ts
  apiv2/src/plan-marketing/infra/provider/PlanMarketingBrevo.provider.ts
  apiv2/src/plan-marketing/infra/provider/PlanMarketingMock.provider.ts
  apiv2/src/plan-marketing/plan-marketing.module.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/src/shared/infra/AllExceptions.filter.ts
  apiv2/src/shared/infra/TechnicalException.ts
  apiv2/src/task/core/Task.gateway.ts
  apiv2/src/task/infra/Task.mapper.ts
  apiv2/src/task/infra/TaskMongo.repository.ts
  apiv2/tsconfig.json
  packages/lib/src/constants/task.ts
Labels: ADMIN, deploy

#4722 fix(api): 222 - correction des statusPhase 1 des jeunes CLE > CLE06
  api/migrations/20250207162201-fix-status-youngs-affected.js
Labels: RUN

#4715 fix(app, api): 3300, 130 - Rétablir le bouton de correction des dossiers PM et les notifications associées
  admin/src/scenes/volontaires/view/phase2MilitaryPreparationV2.jsx
  admin/src/scenes/volontaires/view/phase2bis/EquivalenceList.tsx
  admin/src/scenes/volontaires/view/phase2bis/applicationList2.tsx
  admin/src/scenes/volontaires/view/phase2bis/lib/useApplications.ts
  admin/src/scenes/volontaires/view/phase2bis/view.jsx
  api/src/__tests__/application.test.ts
  api/src/__tests__/equivalence.test.ts
  api/src/application/applicationController.ts
  api/src/application/applicationNotificationService.ts
  api/src/application/applicationService.ts
  api/src/controllers/mission.js
  api/src/controllers/young/index.ts
  api/src/controllers/young/phase2.js
  api/src/controllers/young/phase2.ts
  api/src/crons/missionsJVA/JVAService.ts
  api/src/equivalence/equivalenceController.ts
  api/src/equivalence/equivalenceValidator.ts
  api/src/routes.ts
  app/src/components/layout/navbar/useTickets.ts
  app/src/scenes/militaryPreparation/components/DocumentsPM.jsx
  app/src/scenes/militaryPreparation/lib/useUpdateMPStatus.tsx
  app/src/scenes/missions/components/AcceptButton.tsx
  app/src/scenes/missions/components/ApplyButton.tsx
  app/src/scenes/missions/components/ApplyModal.jsx
  app/src/scenes/missions/components/DeclineButton.tsx
  app/src/scenes/missions/viewDesktop.jsx
  app/src/scenes/missions/viewMobile.jsx
  app/src/scenes/phase2/engagement.repository.ts
  package-lock.json
  packages/lib/src/constants/constants.ts
Labels: WAITING FOR QA, Phase 2, Jeune, deploy

#4730 feat(app): 258 - new message for inscription
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
Labels: deploy

#4733 fix(api): 262 - correction envoie email sans modification PDR
  api/src/services/LigneDeBusService.ts
Labels: deploy

#4744 fix(apiv2): 279 - affectation cle classe sans sejour défini
  apiv2/src/admin/core/sejours/phase1/sejour/Sejour.gateway.ts
  apiv2/src/admin/infra/sejours/phase1/sejour/repository/mongo/SejourMongo.repository.ts
Labels: deploy

#4726 fix(api): 212 - import centre des sessions - ajout champ sejourSnuIds
  api/migrations/20250212084123-sp1-sejourSnuIds.js
  api/src/cle/classe/importAuto/classeImportAutoService.ts
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
  apiv2/src/admin/core/sejours/phase1/sejour/Sejour.model.ts
  apiv2/src/admin/infra/sejours/phase1/sejour/repository/Sejour.mapper.ts
  apiv2/src/admin/infra/sejours/phase1/sejour/repository/mongo/SejourMongo.repository.ts
  apiv2/test/admin/sejour/phase1/helper/SejourHelper.ts
  packages/lib/src/mongoSchema/sessionPhase1.ts
Labels: deploy

#4750 chore(misc): fix custom env build
  devops/scripts/build-application-docker.js
Labels: deploy

#4725 fix(apiv2): 247 - récupération du dernier SDR pour la simulation HTS
  apiv2/src/admin/infra/referentiel/api/ImportReferentiel.controller.ts
Labels: deploy

#4766 feat(app): 318 - MonCompte : Ajout d'un bandeau sur la confirmation de participation
  app/src/scenes/home/components/ConfirmationNotice.tsx
  app/src/scenes/home/waitingAffectation.jsx
  app/src/scenes/phase1/waitingAffectation.jsx
Labels: deploy

#4769 fix(app): MonCompte/Phase 1 : Empêcher la page de planter dans certains cas
  app/src/scenes/phase1/Files.jsx
Labels: bug, bypass title

#4760 fix(api): 312 - migration nettoyage sessionphase1 (sejourSnuId) pour l'import des centres en sessions
  api/migrations/20250219100910-sp1-sejourSnuIds-clean.js
Labels: QA OK

#4749 feat(apiv2): 295 - Afficher les HZR dans l’onglet Intradep
  admin/src/scenes/settings/operations/rapport-pdf/RapportPdfPage.tsx
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.ts
  apiv2/src/admin/core/sejours/phase1/affectation/__tests__/youngs.json
Labels: QA OK

#4761 fix(apiv2): 303 - Le taux de remplissage des lignes de bus n’est pas correctement calculé après les affectations
  apiv2/src/admin/core/sejours/phase1/PlanDeTransport/PlanDeTransport.model.ts
  apiv2/src/admin/core/sejours/phase1/affectation/Affectation.service.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/Affectation.service.ts
  apiv2/src/admin/core/sejours/phase1/affectation/ValiderAffectationCLE.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/ValiderAffectationCLEDromCom.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/ValiderAffectationHTS.spec.ts
  apiv2/src/admin/core/sejours/phase1/inscription/ValiderBasculeJeunesNonValides.spec.ts
  apiv2/src/admin/core/sejours/phase1/inscription/ValiderBasculeJeunesValides.spec.ts
  apiv2/src/admin/core/sejours/phase1/ligneDeBus/LigneDeBus.gateway.ts
  apiv2/src/admin/infra/sejours/phase1/ligneDeBus/repository/mongo/LigneDeBusMongo.repository.ts
  apiv2/src/admin/infra/sejours/phase1/planDeTransport/repository/PlanDeTransport.mapper.ts
  apiv2/test/admin/sejour/phase1/LigneDeBusMongo.repository.spec.ts
Labels: QA OK

#4770 feat(admin): 325 - Affectation manuelle : ajouter tooltips
  admin/src/scenes/volontaires/components/phase1/Details.tsx
Labels: UI/UX, Phase 1

#4732 feat(admin): 188 - Notifier automatiquement les volontaires lorsqu’ils sont désistés après les affectations
  admin/src/scenes/phase0/components/YoungHeader.jsx
  admin/src/scenes/phase0/utils/service.ts
  api/src/controllers/young/index.ts
  api/src/referent/referentController.ts
  api/src/young/youngService.ts
  app/src/scenes/changeSejour/components/ReasonForm.tsx
  packages/lib/src/constants/constants.ts
  packages/lib/src/constants/email.ts
Labels: Phase 1

#4743 feat(apiv2, admin): 234 - Désistement post affectation
  admin/src/scenes/settings/operations/actions/ActionsSubTab.tsx
  admin/src/scenes/settings/operations/actions/Desistement/Desistement.tsx
  admin/src/scenes/settings/operations/actions/Desistement/DesistementButton.tsx
  admin/src/scenes/settings/operations/actions/Desistement/DesistementModal.tsx
  admin/src/scenes/settings/operations/actions/DesistementSection.tsx
  admin/src/scenes/settings/operations/shared/useTraitements.ts
  admin/src/scenes/settings/operations/traitements/TraitementsSubTab.tsx
  admin/src/scenes/settings/operations/traitements/desistement/DesistementResultCell.tsx
  admin/src/services/desistementService.ts
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/AdminJob.module.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.model.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.service.ts
  apiv2/src/admin/core/sejours/jeune/JeuneService.spec.ts
  apiv2/src/admin/core/sejours/phase1/desistement/Desistement.service.spec.ts
  apiv2/src/admin/core/sejours/phase1/desistement/Desistement.service.ts
  apiv2/src/admin/core/sejours/phase1/desistement/DesisterPostAffectation.ts
  apiv2/src/admin/core/sejours/phase1/desistement/DesisterPostAffectationTask.model.ts
  apiv2/src/admin/infra/sejours/jeune/repository/Jeune.mapper.ts
  apiv2/src/admin/infra/sejours/phase1/api/Phase1.controller.ts
  apiv2/src/admin/infra/sejours/phase1/desistement/api/Desistement.controller.ts
  apiv2/src/admin/infra/task/AdminTask.consumer.ts
  apiv2/src/admin/infra/task/AdminTaskAffectationSelector.service.ts
  apiv2/src/notification/core/Notification.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevo.mapper.ts
  packages/ds/src/admin/form/Select/Select.tsx
  packages/ds/src/admin/ui/Button.tsx
  packages/lib/src/constants/task.ts
  packages/lib/src/dto/phase1/desistement/DesistementTaskDto.ts
  packages/lib/src/dto/phase1/desistement/index.ts
  packages/lib/src/dto/phase1/index.ts
  packages/lib/src/routes/index.ts
  packages/lib/src/routes/phase1/desistement/index.ts
  packages/lib/src/routes/phase1/index.ts
  packages/lib/src/translation.ts
Labels: Phase 1

#4767 feat(api): 313 - Notification automatique au volontaire+RL a la confirmation de participation
  api/src/controllers/young/index.ts
  api/src/controllers/young/phase1.ts
  packages/lib/src/constants/email.ts
Labels: deploy

#4776 fix(apiv2): exclude healthcheck from AddUserToRequestMiddleware to pr…
  apiv2/src/admin/Admin.module.ts
Labels: devOps

#4754 feat(apiv2): 285 - gestion des campagnes generiques
  admin/src/app.jsx
  admin/src/components/drawer/components/Profil.jsx
  admin/src/scenes/phase0/components/RadioButton.tsx
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneFormHook.ts
  admin/src/scenes/planMarketing/campagne/CampagneHookError.ts
  admin/src/scenes/planMarketing/campagne/CampagnesGeneriques.tsx
  admin/src/scenes/planMarketing/campagne/index.tsx
  admin/src/services/planMarketingService.ts
  apiv2/src/config/configuration.ts
  apiv2/src/plan-marketing/core/Campagne.model.ts
  apiv2/src/plan-marketing/core/gateway/Campagne.gateway.ts
  apiv2/src/plan-marketing/core/gateway/PlanMarketing.gateway.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.spec.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/infra/Campagne.mapper.ts
  apiv2/src/plan-marketing/infra/CampagneMongo.provider.ts
  apiv2/src/plan-marketing/infra/CampagneMongo.repository.ts
  apiv2/src/plan-marketing/infra/api/Campagne.controller.ts
  apiv2/src/plan-marketing/infra/api/Campagne.validation.ts
  apiv2/src/plan-marketing/infra/api/PlanMarketing.controller.ts
  apiv2/src/plan-marketing/infra/provider/PlanMarketingBrevo.provider.ts
  apiv2/src/plan-marketing/infra/provider/PlanMarketingMock.provider.ts
  apiv2/src/plan-marketing/plan-marketing.module.ts
  apiv2/src/shared/core/FunctionalException.ts
  packages/ds/src/admin/ui/Collapsable.tsx
  packages/lib/src/domains/index.ts
  packages/lib/src/domains/planMarketing/constants.ts
  packages/lib/src/mongoSchema/campagne.ts
  packages/lib/src/mongoSchema/index.ts
  packages/lib/src/routes/planMarketing/index.ts
  packages/lib/src/translation.ts
Labels: ADMIN, deploy

#4772 feat(api,admin): 39 - Suppression de 2 actions de la listes des TODO du TDB
  admin/src/scenes/dashboardV2/components/todos.constants.js
  api/src/services/dashboard/todo-sejour.service.js
  api/src/services/dashboard/todo.service.js
  packages/lib/src/constants/todo.constants.ts
Labels: deploy

#4785 fix(api): phase1 agreement template params cta
  api/src/controllers/young/index.ts
  api/src/controllers/young/phase1.ts
Labels: RUN, deploy, HOTFIX

#4784 feat(app): 240 - Adapter message sur Mon Compte au désistement du jeune lorsqu’il n’a pas confirmé son séjour
  app/src/scenes/home/components/ConfirmationNotice.tsx
  app/src/scenes/home/waitingAffectation.jsx
  app/src/scenes/phase1/scenes/affected/components/modals/AgreementModal.jsx
  app/src/scenes/phase1/scenes/affected/components/step/stepAgreement.tsx
  app/src/scenes/phase1/waitingAffectation.jsx
Labels: RUN, deploy, HOTFIX

#4788 fix(admin): 353 - Update SelectCohort sort and design
  admin/src/components/cohorts/SelectCohort.tsx
  admin/src/scenes/dsnj-export/index.tsx
  admin/src/scenes/goal/index.tsx
  admin/src/scenes/injep-export/index.tsx
  admin/src/scenes/plan-transport/table-repartition/NationalView.tsx
  api/src/planDeTransport/pointDeRassemblement/import/pointDeRassemblementImportMapper.ts
Labels: deploy

#4779 fix(admin): 249 - fix du compteur de volontaires sur la modale de changement de volontaires
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
Labels: bug

#4792 Revert "feat(admin): 252 - Ajout de tooltip informatif sur les nouvelles feature des paramétrages dynamiques
  admin/src/scenes/settings/operations/actions/Affectation/AffectationCLESimulationDromCom.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationCLESimulationMetropole.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationHTSSimulationMetropole.tsx
  admin/src/scenes/settings/operations/actions/Inscription/BasculeJeune/BasculeJeuneNonValides.tsx
  admin/src/scenes/settings/operations/actions/Inscription/BasculeJeune/BasculeJeuneValides.tsx
  packages/ds/src/admin/ui/Tooltip.tsx
  packages/lib/src/common.ts
Labels: Pull request title validation

#4795 fix(admin): SelectCohort griser les cohorts uniquement à J+15 après séjour
  admin/src/components/cohorts/SelectCohort.tsx
Labels: RUN, HOTFIX

#4793 feat(admin): 252 - Ajout de tooltip informatif sur les nouvelles feature des paramétrages dynamiques
  admin/src/scenes/settings/operations/actions/Affectation/AffectationCLESimulationDromCom.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationCLESimulationMetropole.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationHTSSimulationMetropole.tsx
  admin/src/scenes/settings/operations/actions/Inscription/BasculeJeune/BasculeJeuneNonValides.tsx
  admin/src/scenes/settings/operations/actions/Inscription/BasculeJeune/BasculeJeuneValides.tsx
  packages/ds/src/admin/ui/Tooltip.tsx
Labels: deploy

#4796 fix(admin): affichage d'un toast d'erreur lorsque le changement de status d'un jeune échoue
  admin/src/scenes/phase0/components/YoungHeader.jsx
Labels: RUN, HOTFIX

#4798 fix(admin): affecter comme sa classe un jeune à moitier affecté
  admin/src/scenes/volontaires/components/phase1/Details.tsx
Labels: bypass title, RUN, HOTFIX
