Repository betagouv/service-national-universel, pull requests merged in 2025-05, with the labels that each got.

#4979 chore(admin): Ne pas capturer sur Sentry les erreurs non pertinentes
  admin/src/services/react-query.ts
  app/src/services/react-query.ts
  packages/lib/src/constants/errors.ts
Labels: bypass title

#4978 fix(admin): 713 - Permission modifier une structure
  admin/src/scenes/structure/view/detailsV2.jsx
Labels: QA OK

#4969 feat(api,admin): 540 - update de la fonction mascarade (front et back)
  admin/src/app.jsx
  admin/src/components/RestorePreviousSignin/index.tsx
  admin/src/components/drawer/SideBar.tsx
  admin/src/components/drawer/components/Profil.jsx
  admin/src/redux/auth/actions.ts
  admin/src/redux/auth/reducer.ts
  admin/src/scenes/phase0/components/sections/SectionParents.jsx
  admin/src/types.ts
  admin/src/utils/broadcastChannel.ts
  admin/src/utils/signinAs.ts
  api/src/__tests__/referent-auth.test.ts
  api/src/__tests__/young-auth.test.ts
  api/src/auth.ts
  api/src/controllers/request.ts
  api/src/controllers/signin.js
  api/src/models/referent.ts
  api/src/passport.js
  api/src/referent/referentController.ts
  packages/lib/src/mongoSchema/referent.ts
Labels: deploy

#4993 feat(admin): 550 - ajouter des tooltips dans les historiques
  admin/src/components/UserCard.jsx
  admin/src/components/views/Historic2/components/Event.jsx
  admin/src/components/views/HistoricServerDriven.tsx
  admin/src/scenes/classe/components/HistoryRow.tsx
  admin/src/scenes/classe/view/Inscriptions.tsx
  admin/src/scenes/utilisateur/edit/history.jsx
  admin/src/utils/index.jsx
Labels: deploy

#4983 fix(api, app, lib): 707 - Mieux distinguer les permissions liées à la phase Engagement
  admin/src/scenes/volontaires/components/Toolbox.jsx
  admin/src/scenes/volontaires/view/customMission.jsx
  admin/src/scenes/volontaires/view/proposalMission.jsx
  api/src/application/applicationController.ts
  api/src/application/applicationService.ts
  api/src/equivalence/equivalenceController.ts
  app/src/Espace.jsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/phase2/scenes/Home/index.jsx
  app/src/utils/index.js
  packages/lib/src/sessions.ts
Labels: bug, VOLONTAIRES, Phase 2, deploy

#4940 fix(app): 648 - Préinscription : Corriger l'erreur "undefined" dans la page de sélection de l'école
  app/src/components/dsfr/forms/AsyncCombobox.tsx
  app/src/scenes/inscription2023/components/SchoolInFrance.tsx
  app/src/scenes/inscription2023/components/ShoolInFrance.jsx
  app/src/scenes/inscription2023/steps/correction/stepEligibilite.jsx
  app/src/scenes/inscription2023/utils/index.ts
  app/src/scenes/inscription2023/utils/useSchools.ts
  app/src/scenes/preinscription/steps/stepEligibilite.jsx
  app/tsconfig.json
Labels: bug, Phase 0, Jeune, deploy

#4999 fix(admin): 762 - Améliorer la liste de propositions de missions
  admin/src/scenes/missions/view/propose-mission.jsx
  admin/src/scenes/missions/view/propose-mission/YoungCard.tsx
  admin/src/scenes/missions/view/propose-mission/index.tsx
  admin/src/scenes/missions/view/propose-mission/useCreateApplicationForYoung.ts
  admin/src/scenes/missions/view/propose-mission/utils.ts
  admin/src/scenes/volontaires/view/proposalMission.jsx
  admin/src/services/applicationService.ts
  packages/ds/src/admin/ui/Button.tsx
Labels: deploy

#4948 refactor(app): 648 - Mon profil : Corriger les erreurs undefined
  app/package.json
  app/src/components/forms/ErrorMessage.jsx
  app/src/components/forms/ErrorMessage.tsx
  app/src/components/forms/inputs/Checkbox.tsx
  app/src/components/forms/inputs/Input.jsx
  app/src/components/forms/inputs/Input.tsx
  app/src/components/forms/inputs/InputPassword.jsx
  app/src/components/forms/inputs/InputPassword.tsx
  app/src/components/forms/inputs/InputPhone.tsx
  app/src/components/forms/inputs/RadioButton.tsx
  app/src/components/forms/inputs/RadioButtonGroup.jsx
  app/src/components/forms/inputs/Select.jsx
  app/src/components/forms/inputs/Select.tsx
  app/src/components/forms/inputs/Textarea.tsx
  app/src/components/forms/layout/FormRow.jsx
  app/src/components/forms/layout/Label.jsx
  app/src/components/nav/MobileMenu.tsx
  app/src/components/nav/Tabs.tsx
  app/src/hooks/usePermissions.ts
  app/src/scenes/account/components/BackLink.jsx
  app/src/scenes/account/components/SectionTitle.jsx
  app/src/scenes/account/index.tsx
  app/src/scenes/account/lib/repository.ts
  app/src/scenes/account/lib/useUpdateAccount.ts
  app/src/scenes/account/lib/useUpdatePassword.ts
  app/src/scenes/account/scenes/general/components/ChangeAddressModal/ChooseCohortModalContent.jsx
  app/src/scenes/account/scenes/general/index.jsx
  app/src/scenes/account/scenes/general/index.tsx
  app/src/scenes/account/scenes/password/index.jsx
  app/src/scenes/account/scenes/password/index.tsx
  app/src/scenes/account/scenes/representants/index.jsx
  app/src/scenes/account/scenes/representants/index.tsx
  app/src/scenes/account/scenes/school-situation/index.tsx
  app/src/scenes/account/scenes/special-situations/index.tsx
  app/src/scenes/account/scenes/withdrawn/components/Withdrawal.jsx
  app/src/scenes/account/scenes/withdrawn/components/Withdrawal.tsx
  app/src/scenes/account/scenes/withdrawn/index.tsx
  app/src/scenes/phase2/scenes/MesEngagements/components/Preferences/index.jsx
  app/src/utils/form-validation.utils.js
  app/src/utils/form-validation.utils.ts
  package-lock.json
Labels: bug, Jeune, deploy

#5011 feat(admin,apiv2,lib): 665 - inscription individuelle manuelle #5008
  admin/src/scenes/classe/header/ButtonInscriptionManuelle.tsx
  admin/src/scenes/classe/header/index.tsx
  admin/src/scenes/classe/index.tsx
  admin/src/scenes/classe/inscriptionManuelle/InscriptionManuelleForm.tsx
  admin/src/scenes/classe/inscriptionManuelle/InscriptionManuellePage.tsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/settings/general/components/phase0/getManualInscriptionTogglesByCohortType.tsx
  admin/src/services/classeService.ts
  apiv2/src/admin/Admin.module.ts
  apiv2/src/admin/core/sejours/cle/classe/importEnMasse/useCase/ImporterClasseEnMasse.spec.ts
  apiv2/src/admin/core/sejours/cle/classe/importEnMasse/useCase/ImporterClasseEnMasse.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/InscrireEleveManuellement.spec.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/InscrireEleveManuellement.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.model.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.service.ts
  apiv2/src/admin/infra/sejours/cle/classe/api/Classe.controller.ts
  apiv2/src/admin/infra/sejours/cle/classe/api/Classe.validation.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/test/admin/setUpAdminTest.ts
  packages/lib/src/index.ts
  packages/lib/src/routes/cle/classe/InscriptionManuelle.ts
  packages/lib/src/routes/cle/classe/index.ts
  packages/lib/src/translation.ts
  packages/lib/src/utils/string.ts
Labels: ADMIN

#5004 feat(admin): 753 - Donner la possibilité aux superviseurs de créer une nouvelle mission
  admin/src/scenes/missions/create.jsx
  admin/src/scenes/structure/view/ActionButton.tsx
  admin/src/scenes/structure/view/detailsV2.jsx
  admin/src/scenes/structure/view/wrapperv2.jsx
  packages/lib/src/roles.ts
Labels: deploy

#5019 Merge production sur main
  api/migrations/20250523082833-lignesbus-fusion-ara.js
Labels: bypass title

#5027 Fix inscription manuelle qa
  admin/src/scenes/classe/index.tsx
  admin/src/scenes/classe/inscriptionManuelle/InscriptionManuelleForm.tsx
  admin/src/scenes/classe/inscriptionManuelle/InscriptionManuellePage.tsx
  admin/src/scenes/phase0/components/sections/SectionParents.tsx
  admin/src/scenes/phase0/view.tsx
  admin/src/scenes/settings/general/components/phase0/getManualInscriptionTogglesByCohortType.tsx
  apiv2/src/admin/core/sejours/jeune/Jeune.model.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.service.ts
  apiv2/src/admin/infra/sejours/jeune/repository/Jeune.mapper.ts
  packages/lib/src/translation.ts
Labels: Pull request title validation

#5035 fix(api): 826 - Desistement paca juillet
  api/migrations/20250528071041-826-desistement-paca-juillet.js
Labels: RUN, HOTFIX
