Repository betagouv/service-national-universel, pull requests merged in 2025-06, with the labels that each got.

#5038 feat(api): 770 - update le status_equivalence du jeune lorsque celui-ci supprime sa demande d'equivalence
  api/src/equivalence/equivalenceController.ts
Labels: deploy

#5046 chore(all): Merge Main to Production
  admin/src/hooks/useBrevoCSVGenerator.ts
  admin/src/hooks/useBrevoRecipients.ts
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/volontaires/utils/index.js
  api/src/controllers/elasticsearch/populate/populateYoung.js
  api/src/controllers/elasticsearch/young.js
  packages/lib/src/excelExports.ts
Labels: bypass title

#5039 feat(apiv2): 629 - Pouvoir envoyer un mail test depuis la plateforme admin
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifique.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifiqueForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagnesGeneriques.tsx
  admin/src/scenes/planMarketing/hooks/SendMailTest.ts
  admin/src/services/planMarketingService.ts
  apiv2/src/notification/core/Notification.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevo.mapper.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevoCatcher.provider.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.spec.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/infra/api/Campagne.controller.ts
  apiv2/src/plan-marketing/plan-marketing.module.ts
  packages/lib/src/routes/planMarketing/index.ts
Labels: deploy

#5059 feat(apiv2): 733 - Envoyer les identifiants de connexion dans les cam…
  apiv2/src/plan-marketing/core/ListeDiffusion.model.ts
  apiv2/src/plan-marketing/core/useCase/CreerListeDiffusion.spec.ts
  apiv2/src/plan-marketing/core/useCase/CreerListeDiffusion.ts
Labels: deploy

#5061 feat(admin,api): 846 - On ne veut plus controler la capacite max du centre lors de la modif et/ou l'import des sessions pour faire du surbooking
  admin/src/scenes/centersV2/components/sessions/SessionList.tsx
  api/src/controllers/session-phase1.ts
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
Labels: deploy

#5074 feat(api): 904 - Ajout de nouveaux PDR
  api/migrations/20250620072651-904-nouveaux-pdr.js
Labels: deploy

#5083 fix(api): Petit fix pour pouvoir lancer facilement le support en local et accepter les alias dans les mail de connexion
  api/src/config.ts
  api/src/controllers/SNUpport.ts
Labels: bypass title

#5086 feat(api): 878 - Ajouter RL pour template 1257 et 1253
  api/src/__tests__/application.test.ts
  api/src/application/applicationController.ts
Labels: deploy

#5095 fix(api): migration pour désister les LC d’Occitanie+Nouvelle-Aquitaine
  api/migrations/20250626132340-desiste-lc-occitanie.js
Labels: RUN, deploy

#5098 feat(api): migration pour maj correspondance IDF771161
  api/migrations/20250626161934-927-changement-pdr-IDF771161.js
Labels: RUN, deploy
