Repository betagouv/service-national-universel, pull requests merged in 2025-03, with the labels that each got.

#4794 feat(admin): 351 - Ajouter des tooltips sur la modale de création de liste de diffusion
  admin/src/components/modals/ModalCreationListeBrevo.tsx
Labels: deploy

#4783 fix(admin,api): 342 - Supprimer le bouton pour Mettre à jour le classes depuis la page Classe
  admin/src/scenes/classe/Import.tsx
  admin/src/scenes/classe/index.tsx
  admin/src/scenes/classe/list.tsx
  api/src/__tests__/cle/classeImportAuto.test.ts
  api/src/cle/classe/importAuto/classeImportAutoController.ts
  api/src/cle/classe/importAuto/classeImportAutoMapper.ts
  api/src/cle/classe/importAuto/classeImportAutoService.test.ts
  api/src/cle/classe/importAuto/classeImportAutoService.ts
  api/src/cle/classe/importAuto/classeImportAutoType.ts
  api/src/cle/index.ts
Labels: deploy, QA OK

#4801 fix(apiv2): Synchroniser les places dans les centres lors d'un désistement post-affectation
  apiv2/src/admin/core/sejours/phase1/desistement/Desistement.service.spec.ts
  apiv2/src/admin/core/sejours/phase1/desistement/Desistement.service.ts
  apiv2/src/admin/core/sejours/phase1/desistement/DesisterPostAffectation.ts
Labels: bypass title, Phase 1

#4786 fix(app): 338 - fix order for Programs
  app/src/scenes/phase2/scenes/Home/components/Programs.jsx
Labels: deploy

#4805 feat(apiv2, admin): 344 - Pouvoir télécharger la liste des volontaires avant désistement post-affectation
  admin/src/scenes/settings/operations/actions/Desistement/DesistementModal.tsx
  admin/src/scenes/settings/operations/actions/Desistement/DesistementPreview.tsx
  admin/src/scenes/settings/operations/traitements/TraitementsSubTab.tsx
  admin/src/scenes/settings/operations/traitements/desistement/DesistementResultCell.tsx
  admin/src/utils/file.ts
  apiv2/src/admin/core/sejours/phase1/desistement/Desistement.service.ts
  apiv2/src/admin/core/sejours/phase1/desistement/DesisterPostAffectation.ts
  packages/lib/src/dto/phase1/desistement/DesistementTaskDto.ts
  packages/lib/src/routes/phase1/desistement/index.ts
Labels: deploy

#4800 feat(admin,lib,apiv2): 283 - Gestion des listes de diffusion
  admin/src/app.jsx
  admin/src/components/filters-system-v2/components/filters/FilterPopOver.tsx
  admin/src/scenes/inscription/index.jsx
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagnesGeneriques.tsx
  admin/src/scenes/planMarketing/index.tsx
  admin/src/scenes/planMarketing/listeDiffusion/ListeDiffusion.tsx
  admin/src/scenes/planMarketing/listeDiffusion/ListeDiffusionForm.tsx
  admin/src/scenes/planMarketing/listeDiffusion/ListeDiffusionHook.ts
  admin/src/scenes/planMarketing/listeDiffusion/filters/ListeDiffusionFilters.tsx
  admin/src/scenes/planMarketing/listeDiffusion/filters/ListeDiffusionFiltersHook.ts
  admin/src/scenes/planMarketing/listeDiffusion/filters/ListeDiffusionFiltersWrapper.tsx
  admin/src/services/listeDiffusionService.ts
  apiv2/src/plan-marketing/core/ListeDiffusion.model.ts
  apiv2/src/plan-marketing/core/gateway/ListeDiffusion.gateway.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/core/service/ListeDiffusion.service.spec.ts
  apiv2/src/plan-marketing/core/service/ListeDiffusion.service.ts
  apiv2/src/plan-marketing/infra/ListeDiffusion.mapper.ts
  apiv2/src/plan-marketing/infra/ListeDiffusion.provider.ts
  apiv2/src/plan-marketing/infra/ListeDiffusionMongo.repository.ts
  apiv2/src/plan-marketing/infra/api/ListeDiffusion.controller.ts
  apiv2/src/plan-marketing/infra/api/ListeDiffusion.validation.ts
  apiv2/src/plan-marketing/plan-marketing.module.ts
  apiv2/src/shared/core/FunctionalException.ts
  packages/lib/src/domains/planMarketing/constants.ts
  packages/lib/src/mongoSchema/index.ts
  packages/lib/src/mongoSchema/listeDiffusion.ts
  packages/lib/src/routes/planMarketing/index.ts
  packages/lib/src/routes/planMarketing/listeDiffusion.ts
  packages/lib/src/translation.ts
Labels: deploy

#4806 fix(admin): fix des tooltip de lites de diffusion Brevo
  admin/src/components/modals/ModalCreationListeBrevo.tsx
  packages/ds/src/admin/ui/Tooltip.tsx
Labels: bypass title, deploy

#4817 fix(apiv2): Corriger le comportement de la connexion à brevo en cas d'absence de PJ
  apiv2/src/notification/infra/email/Email.consumer.ts
  apiv2/src/notification/infra/email/brevo/EmailBrevo.provider.ts
Labels: bypass title

#4818 feat(apiv2): 412 - bull dashboard for apiv2
  apiv2/package.json
  apiv2/src/admin/Admin.module.ts
  apiv2/src/config/configuration.ts
  apiv2/src/infra/Queue.module.ts
  apiv2/test/admin/setUpAdminTest.ts
  devops/local/docker-compose.yml
  package-lock.json
Labels: devOps, deploy

#4819 fix(admin): 125 - export structures wording
  admin/src/scenes/structure/listV3.jsx
Labels: deploy

#4811 fix(apiv2): 357 - Algo effectation HTS - cas limite changement departement
  admin/src/scenes/settings/operations/actions/Affectation/AffectationCLESimulationDromCom.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationCLESimulationMetropole.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationHTSSimulationDromCom.tsx
  admin/src/scenes/settings/operations/actions/Affectation/AffectationHTSSimulationMetropole.tsx
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.spec.ts
  apiv2/src/admin/core/sejours/phase1/affectation/SimulationAffectationHTS.service.ts
Labels: deploy

#4775 feat(api, admin): 42 - Permettre de changer de centre sur une ligne de transport
  admin/src/scenes/plan-transport/lib/useSessionsByCohort.ts
  admin/src/scenes/plan-transport/lib/useUpdateSessionSurLigneDeBus.ts
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreLabel.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/SessionSelector.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/index.tsx
  admin/src/services/sessionPhase1Service.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  packages/ds/src/admin/form/EditButton.tsx
  packages/ds/src/admin/index.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/dto/ligneDeBus.ts
Labels: Phase 1, deploy

#4814 feat(api): 298 - Ajouter les ref CLE aux notifs de changement de PDR + mettre les jeune en copie
  admin/src/scenes/plan-transport/ligne-bus/View/components/ConfirmChangesModal.tsx
  api/src/services/LigneDeBusService.ts
  packages/lib/src/constants/email.ts
Labels: deploy

#4804 fix(api): 355 - ajout d'un check dans le template de certificat phase 1 si le centre contient la mention "DOUBLONS NE PAS UTILISER""
  api/src/planDeTransport/planDeTransport/import/pdtImportService.ts
  api/src/templates/certificate/phase1.ts
Labels: deploy

#4813 fix(admin): 354 - add CAP for Old Young
  api/src/young/edition/youngEditionController.ts
Labels: deploy

#4833 fix(api): 431 - type transport autocar avec correspondance
  api/src/controllers/planDeTransport/import.ts
Labels: RUN, deploy

#4832 fix(api,apiv2): 426 - Reset des données d'affectation lors d'un desistement
  api/src/controllers/young/index.ts
  api/src/referent/referentController.ts
  apiv2/src/admin/core/sejours/phase1/desistement/Desistement.service.ts
Labels: RUN, deploy

#4835 feat(admin): 435 - toggle demo mode
  admin/src/components/drawer/SideBar.tsx
  admin/src/components/drawer/components/Header.tsx
Labels: deploy

#4824 feat(api, admin): 42, 298 - Changement de centre sur une ligne et évolutions des notifs de changements de PDR
  admin/src/scenes/plan-transport/lib/useSessionsByCohort.ts
  admin/src/scenes/plan-transport/lib/useUpdateSessionSurLigneDeBus.ts
  admin/src/scenes/plan-transport/ligne-bus/View/authorization.ts
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreLabel.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/SessionSelector.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/index.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/ConfirmChangesModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
  admin/src/services/sessionPhase1Service.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusNotificationService.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  api/src/services/LigneDeBusService.ts
  packages/ds/src/admin/form/EditButton.tsx
  packages/ds/src/admin/index.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/dto/ligneDeBus.ts
Labels: deploy

#4839 feat(admin,apiv2): 289-288 - mise à jour campagne spécifique et suppression du lien avec générique
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/mapper/CampagneSpecifiqueMapper.ts
  apiv2/package.json
  apiv2/src/plan-marketing/core/Campagne.model.ts
  apiv2/src/plan-marketing/core/gateway/Campagne.gateway.ts
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
  apiv2/src/plan-marketing/core/useCase/MettreAJourCampagne.spec.ts
  apiv2/src/plan-marketing/core/useCase/MettreAJourCampagne.ts
  apiv2/src/plan-marketing/infra/Campagne.mapper.ts
  apiv2/src/plan-marketing/infra/CampagneMongo.repository.ts
  apiv2/src/plan-marketing/infra/api/Campagne.controller.ts
  apiv2/src/plan-marketing/plan-marketing.module.ts
  apiv2/test/plan-marketing/CampagneHelper.ts
  apiv2/test/plan-marketing/CampagneMongo.repository.spec.ts
  apiv2/test/plan-marketing/setUpPlanMarketingTest.ts
  packages/lib/src/mongoSchema/campagne.ts
  packages/lib/src/routes/planMarketing/index.ts
Labels: ADMIN

#4843 feat(apiv2): 420 - elastic search in apiv2
  apiv2/package.json
  apiv2/src/App.module.ts
  apiv2/src/analytics/analytics.module.ts
  apiv2/src/analytics/core/SearchYoung.gateway.ts
  apiv2/src/analytics/infra/ElasticQuery.builder.ts
  apiv2/src/analytics/infra/ElasticQuery.ts
  apiv2/src/analytics/infra/SearchYoungElastic.repository.ts
  apiv2/src/analytics/infra/api/SearchYoung.controller.ts
  apiv2/src/analytics/infra/api/dto/SearchYoung.validation.ts
  apiv2/src/config/configuration.ts
  package-lock.json
  packages/lib/src/domains/analytics/constants.ts
  packages/lib/src/domains/index.ts
Labels: Tech

#4846 fix(api): 371 - Revoir le calcul des places disponibles au niveau centre des sessions
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
Labels: deploy

#4849 fix(api): 425 - keep IN_PROGRESS and REINSCRIPTION status when change cohort
  api/src/referent/referentController.ts
Labels: deploy

#4742 fix(apiv2): 242 - Correction mise à jour des classes
  apiv2/src/admin/core/referentiel/classe/useCase/DesisterClasses.spec.ts
  apiv2/src/admin/core/referentiel/classe/useCase/DesisterClasses.ts
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.spec.ts
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.ts
Labels: deploy

#4854 fix(api): 463 - erreurs lignes fusionnées
  api/migrations/20250318162852-463-fusion-defusion.js
Labels: RUN

#4851 chore(misc) - Backup services on Scaleway
  .github/workflows/scw-deploy.yml
  .github/workflows/scw-docker-build.yml
  devops/build/all/package.json
  devops/build/api/package.json
  devops/build/apiv2/package.json
  devops/build/build-all.sh
  devops/build/build.sh
  devops/build/docker/Dockerfile.api
  devops/build/docker/Dockerfile.apiv2
  devops/build/docker/Dockerfile.front
  devops/scripts/cc-watch-deploy.sh
  devops/scripts/scw/deploy.sh
  devops/scripts/scw/get-secrets-from-cc.sh
  devops/scripts/scw/update-secrets-from-cc.sh
Labels: bypass title

#4852 fix(admin): 456 - bug d'affichage sur la fiche d'une ligne fusionnée
  admin/src/scenes/plan-transport/ligne-bus/View/View.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre.jsx
  admin/src/scenes/plan-transport/ligne-bus/index.tsx
Labels: deploy

#4859 chore(misc) - Merge APIs on Scaleway containers
  .github/workflows/scw-deploy.yml
  .github/workflows/scw-docker-build.yml
  devops/build/docker/Dockerfile.apiv2
  devops/build/docker/Dockerfile.back
  devops/build/docker/Dockerfile.front
  devops/build/docker/back/ecosystem.api.config.js
  devops/build/docker/back/ecosystem.tasks.config.js
  devops/build/docker/back/nginx.conf
  devops/build/docker/back/package.json
  devops/build/docker/back/start-nginx.sh
  devops/scripts/scw/deploy.sh
  devops/scripts/scw/get-secrets-from-cc.sh
Labels: bypass title

#4853 fix(api): 471 - rendre le contact convocation plus lisible sur la convocation
  api/src/templates/convocation/cohesion.ts
Labels: deploy

#4858 fix(apiv2): 453 - fix import SI-SNU - mise à jour uniquement des jeunes de la classe qui sont dans la bonne cohort
  apiv2/src/admin/core/referentiel/classe/useCase/DesisterClasses.spec.ts
  apiv2/src/admin/core/referentiel/classe/useCase/DesisterClasses.ts
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.spec.ts
  apiv2/src/admin/core/referentiel/classe/useCase/ImporterClasses.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/AnnulerClasseDesistee.spec.ts
  apiv2/src/admin/core/sejours/cle/classe/useCase/AnnulerClasseDesistee.ts
  apiv2/src/admin/core/sejours/jeune/Jeune.gateway.ts
  apiv2/src/admin/infra/sejours/jeune/repository/mongo/JeuneMongo.repository.ts
Labels: deploy

#4865 fix(api): 491 - ajout pdr à 3 lignes
  api/migrations/20250321081246-491-ajout-pdr2-sur-lignes.js
Labels: RUN

#4855 fix(admin,api): 477 - Bien rattacher le centre à la CLE 18 Martinique
  admin/src/scenes/settings/general/GeneralTab.tsx
  api/src/cohort/cohortValidator.ts
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
  packages/ds/src/admin/ui/Tooltip.tsx
  packages/lib/src/dto/cohortDto.ts
  packages/lib/src/mongoSchema/cohort.ts
Labels: deploy

#4860 fix retour de tests PMR lot 2-B
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifique.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifiqueForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifiqueHook.ts
  admin/src/scenes/settings/index.tsx
  apiv2/src/plan-marketing/core/service/Campagne.service.ts
Labels: bypass title, deploy

#4869 feat(api, admin): 42, 298 - Changement de centre sur une ligne et évolutions des notifs de changements de PDR
  admin/src/scenes/plan-transport/lib/useSessionsByCohort.ts
  admin/src/scenes/plan-transport/lib/useUpdateSessionSurLigneDeBus.ts
  admin/src/scenes/plan-transport/ligne-bus/View/authorization.ts
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre.jsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreLabel.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/CentreModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/SessionSelector.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Centre/index.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/ConfirmChangesModal.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/PointDeRassemblement.tsx
  admin/src/services/sessionPhase1Service.ts
  api/src/__tests__/ligne-de-bus.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusController.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusNotificationService.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.test.ts
  api/src/planDeTransport/ligneDeBus/ligneDeBusService.ts
  api/src/services/LigneDeBusService.ts
  packages/ds/src/admin/form/EditButton.tsx
  packages/ds/src/admin/index.ts
  packages/lib/src/constants/email.ts
  packages/lib/src/dto/ligneDeBus.ts
Labels: deploy

#4834 feat(apiV2): 248 - persister le rapport apres le desistement post-affectation
  apiv2/src/admin/core/sejours/phase1/desistement/SimulationDesisterPostAffectation.ts
  apiv2/src/admin/core/sejours/phase1/desistement/SimulationDesisterPostAffectationTask.model.ts
  apiv2/src/admin/core/sejours/phase1/desistement/ValiderDesisterPostAffectation.spec.ts
  apiv2/src/admin/core/sejours/phase1/desistement/ValiderDesisterPostAffectation.ts
  apiv2/src/admin/core/sejours/phase1/desistement/ValiderDesisterPostAffectationTask.model.ts
  apiv2/src/shared/core/FunctionalException.ts
  apiv2/tsconfig.json
Labels: deploy

#4874 Production
  admin/src/scenes/volontaires/create.tsx
Labels: bypass title

#4878 fix(admin): 507 - bug sur l'affichage du nombre de volontaires sur la ligne de bus pour les ref dep/reg
  admin/src/scenes/plan-transport/ligne-bus/View/View.tsx
  admin/src/scenes/plan-transport/ligne-bus/View/components/Info.tsx
Labels: deploy

#4877 feat(admin): 287 - Calcul et affichage du nombre de destinataires via ES
  admin/src/components/modals/ModalCreationListeBrevo.tsx
  admin/src/hooks/useCohort.ts
  admin/src/scenes/planMarketing/campagne/CampagneForm.tsx
  admin/src/scenes/planMarketing/campagne/CampagneSpecifiqueForm.tsx
  admin/src/scenes/planMarketing/campagne/partials/DestinataireCount.tsx
  admin/src/scenes/planMarketing/campagne/partials/DestinataireLink.tsx
  admin/src/services/analyticsService.ts
  apiv2/src/analytics/core/SearchYoung.gateway.ts
  apiv2/src/analytics/infra/ElasticQuery.builder.ts
  apiv2/src/analytics/infra/ElasticQuery.ts
  apiv2/src/analytics/infra/SearchYoungElastic.repository.ts
  apiv2/src/analytics/infra/api/SearchYoung.controller.ts
  apiv2/src/analytics/infra/api/dto/SearchYoung.validation.ts
  packages/lib/src/domains/analytics/constants.ts
  packages/lib/src/routes/analytics/getYoungCount.ts
  packages/lib/src/routes/analytics/index.ts
  packages/lib/src/routes/index.ts
Labels: bypass title

#4836 fix(admin): 335 - Restreindre l'accès visiteur
  admin/src/app.jsx
Labels: ADMIN, WAITING FOR QA

#4880 feat(admin): Améliorer la lisibilité de l'historique des missions
  admin/src/components/views/Historic.jsx
  admin/src/components/views/lib/patchesRepository.ts
  admin/src/components/views/lib/patchesUtils.ts
  admin/src/components/views/lib/usePatches.ts
  admin/src/utils/translateFieldsModel.ts
Labels: bypass title

#4881 chore(misc): Environnement de tests sur CC
  .github/workflows/anonymize-cron.yml
  .github/workflows/deploy-environment.yml
  .github/workflows/destroy-environment.yml
  .github/workflows/env-deploy.yml
  .github/workflows/env-destroy.yml
  .github/workflows/env-stop-cron.yml
  .github/workflows/env-stop.yml
  .github/workflows/test-deploy-ci.yml
  .github/workflows/test-deploy-production.yml
  devops/scripts/cc-create-environment.sh
  devops/scripts/cc-environment-name.sh
  devops/scripts/cc-watch-deploy.sh
Labels: bypass title

#4856 feat(api): 397 - Permettre de détacher un centre d’une session lors de l’import des centres de sessions
  admin/src/scenes/centersV2/ImportCentresSession.tsx
  api/migrations/20250331122436-add_feature_flag_delete_centresession.js
  api/src/sessionPhase1/import/sessionPhase1Import.ts
  api/src/sessionPhase1/import/sessionPhase1ImportController.ts
  api/src/sessionPhase1/import/sessionPhase1ImportMapper.ts
  api/src/sessionPhase1/import/sessionPhase1ImportService.ts
  packages/lib/src/constants/featureFlags.ts
Labels: QA OK
