Repository betagouv/service-national-universel, pull requests merged in 2025-07, with the labels that each got.

#5117 fix(apiv2): improve filter handling in ElasticsearchQueryBuilder
  apiv2/src/analytics/infra/ElasticQuery.builder.ts
Labels: bypass title, RUN, HOTFIX

#5135 feat(api): 929 - Distinguer les missions PM et autres lors de l'envoie de mails
  admin/src/services/applicationService.ts
  api/src/application/applicationController.ts
  api/src/crons/applicationWaitingAcceptationOutdated.ts
  api/src/young/email/youngEmailService.ts
  packages/lib/src/constants/email.ts
Labels: deploy

#5150 Change uptime provider to internal kibana + ES
  apiv2/src/admin/Admin.module.ts
  apiv2/src/infra/HealthCheck.controller.ts
  apiv2/test/health/HealthCheck.controller.spec.ts
  devops/heartbeat/Dockerfile
  devops/heartbeat/entrypoint.sh
  devops/heartbeat/heartbeat.yml.template
Labels: bypass title
